/**
 * Sitemap Index — lists all 10 child sitemaps generated by app/sitemap.ts
 *
 * Next.js 14 generateSitemaps() creates /sitemap/0.xml through /sitemap/9.xml
 * but does NOT auto-generate a /sitemap.xml index. This route fills that gap.
 */

export const revalidate = 3600;

export async function GET() {
  const baseUrl = 'https://www.lessoncraftstudio.com';
  const lastmod = new Date(process.env.BUILD_DATE || '2026-03-20').toISOString();

  const sitemapIds = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  const entries = sitemapIds
    .map(
      (id) => `  <sitemap>
    <loc>${baseUrl}/sitemap/${id}.xml</loc>
    <lastmod>${lastmod}</lastmod>
  </sitemap>`
    )
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</sitemapindex>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=UTF-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  });
}
