/**
 * Sitemap Index — lists the child sitemaps generated by app/sitemap.ts.
 *
 * Next.js 14 generateSitemaps() creates /sitemap/N.xml per shard but does
 * NOT auto-generate a /sitemap.xml index. This route fills that gap by
 * reading the canonical shard list from app/sitemap.ts (§10.4 read-from-SoT).
 *
 * Per CLAUDE.md §17.10.1 the sitemap is a 4-shard index. Arc 6c (`85f090a3`)
 * introduced shards 1-3 in sitemap.ts; this route was previously hardcoded
 * to `[0]` from the pre-Arc-6c teardown era and never updated, leaving
 * shards 1-3 invisible to Google.
 */

export const revalidate = 3600;

// Canonical 5-shard list. Phase 4 SEO-thumbnail commission: shards 0 + 1
// are served by custom routes (app/sitemap/0.xml/route.ts + 1.xml/route.ts)
// to emit per-URL <image:image> entries. Shards 2 + 3 + 4 served by Next.js
// sitemap convention from app/sitemap.ts (4 = deck-landing pages, Gate-1
// browse-layer ruling 2026-06-12). Hard-coded here so the index references
// all five shards regardless of generateSitemaps()'s return.
// SEO RESCUE Part 2 Wave A (2026-06-14): shards 0 + 1 (deck pages) are DROPPED
// from the index — the individual `/decks/<slug>/` pages are near-duplicate,
// image-only thin assets dominating GSC's "Crawled – not indexed" bucket, so we
// stop promoting them and concentrate crawl on the unique topic hubs (shards 2/3)
// + the /worksheets/ landings (shard 4). The 0.xml/1.xml routes now emit empty
// urlsets (EMIT_DECK_SITEMAP=false). To revert: restore [0,1,2,3,4] + the flag.
const SITEMAP_SHARD_IDS = [2, 3, 4];

export async function GET() {
  const baseUrl = 'https://www.lessoncraftstudio.com';
  const lastmod = new Date(process.env.BUILD_DATE || '2026-03-20').toISOString();

  const sitemapIds = SITEMAP_SHARD_IDS;

  const entries = sitemapIds
    .map(
      (id) => `  <sitemap>
    <loc>${baseUrl}/sitemap/${id}.xml</loc>
    <lastmod>${lastmod}</lastmod>
  </sitemap>`
    )
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</sitemapindex>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=UTF-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  });
}
