/**
 * Sitemap Index — lists the child sitemaps generated by app/sitemap.ts.
 *
 * Next.js 14 generateSitemaps() creates /sitemap/N.xml per shard but does
 * NOT auto-generate a /sitemap.xml index. This route fills that gap by
 * reading the canonical shard list from app/sitemap.ts (§10.4 read-from-SoT).
 *
 * Per CLAUDE.md §17.10.1 the sitemap is a 4-shard index. Arc 6c (`85f090a3`)
 * introduced shards 1-3 in sitemap.ts; this route was previously hardcoded
 * to `[0]` from the pre-Arc-6c teardown era and never updated, leaving
 * shards 1-3 invisible to Google.
 */

export const revalidate = 3600;

// Canonical 4-shard list. Phase 4 SEO-thumbnail commission: shards 0 + 1
// are served by custom routes (app/sitemap/0.xml/route.ts + 1.xml/route.ts)
// to emit per-URL <image:image> entries. Shards 2 + 3 served by Next.js
// sitemap convention from app/sitemap.ts. Hard-coded here so the index
// references all four shards regardless of generateSitemaps()'s return.
const SITEMAP_SHARD_IDS = [0, 1, 2, 3];

export async function GET() {
  const baseUrl = 'https://www.lessoncraftstudio.com';
  const lastmod = new Date(process.env.BUILD_DATE || '2026-03-20').toISOString();

  const sitemapIds = SITEMAP_SHARD_IDS;

  const entries = sitemapIds
    .map(
      (id) => `  <sitemap>
    <loc>${baseUrl}/sitemap/${id}.xml</loc>
    <lastmod>${lastmod}</lastmod>
  </sitemap>`
    )
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</sitemapindex>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=UTF-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  });
}
