// Auto-generated by scripts/build-visual-assignments.js
// Maps each guide/bundle/idea/start page to 4 visual showcase HTML sections
// from "visuals to enrich the pages/" folder

export interface VisualAssignment {
  /** Path relative to "visuals to enrich the pages/" */
  file: string;
  /** Which app this visual comes from */
  app: string;
  /** Section type: hero | features | progression | fun */
  type: string;
}

export interface PageVisualConfig {
  pageType: 'guide' | 'bundle' | 'idea' | 'start';
  pageId: string;
  visuals: [VisualAssignment, VisualAssignment, VisualAssignment, VisualAssignment];
}

export const pageVisualAssignments: PageVisualConfig[] = [
  {
    pageType: 'guide',
    pageId: 'sell-math-worksheets-etsy',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'subtraction/002.html', app: 'subtraction', type: 'features' },
      { file: 'math-puzzle/003.html', app: 'math-puzzle', type: 'progression' },
      { file: 'math-worksheet/004.html', app: 'math-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'sell-word-search-etsy',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'crossword/002.html', app: 'crossword', type: 'features' },
      { file: 'word-scramble/003.html', app: 'word-scramble', type: 'progression' },
      { file: 'cryptogram/004.html', app: 'cryptogram', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'start-etsy-printable-shop',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-etsy-coloring-pages',
    visuals: [
      { file: 'coloring/001.html', app: 'coloring', type: 'hero' },
      { file: 'draw-and-color/002.html', app: 'draw-and-color', type: 'features' },
      { file: 'big-small/003.html', app: 'big-small', type: 'progression' },
      { file: 'alphabet-train/004.html', app: 'alphabet-train', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'sell-educational-printables-etsy',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'price-etsy-printables',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'sudoku/003.html', app: 'sudoku', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'etsy-seo-educational-printables',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'sudoku/004.html', app: 'sudoku', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-etsy-worksheet-bundles',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'subtraction/002.html', app: 'subtraction', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'math-activity-books-kdp',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'subtraction/002.html', app: 'subtraction', type: 'features' },
      { file: 'math-puzzle/003.html', app: 'math-puzzle', type: 'progression' },
      { file: 'math-worksheet/004.html', app: 'math-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'publish-puzzle-books-kdp',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'crossword/002.html', app: 'crossword', type: 'features' },
      { file: 'sudoku/003.html', app: 'sudoku', type: 'progression' },
      { file: 'math-puzzle/004.html', app: 'math-puzzle', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'word-search-books-kdp',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'crossword/002.html', app: 'crossword', type: 'features' },
      { file: 'math-puzzle/003.html', app: 'math-puzzle', type: 'progression' },
      { file: 'bingo/004.html', app: 'bingo', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'make-money-kdp-activity-books',
    visuals: [
      { file: 'math-worksheet/001.html', app: 'math-worksheet', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'sudoku/003.html', app: 'sudoku', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'kdp-formatting-worksheets',
    visuals: [
      { file: 'math-worksheet/001.html', app: 'math-worksheet', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'writing/004.html', app: 'writing', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'best-kdp-activity-book-niches',
    visuals: [
      { file: 'math-worksheet/001.html', app: 'math-worksheet', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'sudoku/004.html', app: 'sudoku', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'sudoku-books-kdp',
    visuals: [
      { file: 'sudoku/001.html', app: 'sudoku', type: 'hero' },
      { file: 'math-puzzle/002.html', app: 'math-puzzle', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'kdp-vs-etsy-printables',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'math-puzzle/004.html', app: 'math-puzzle', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-sell-tpt-resources',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'tpt-store-optimization',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'math-puzzle/002.html', app: 'math-puzzle', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'crossword/004.html', app: 'crossword', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'sell-printables-gumroad',
    visuals: [
      { file: 'coloring/001.html', app: 'coloring', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'math-worksheet/003.html', app: 'math-worksheet', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'sell-creative-fabrica',
    visuals: [
      { file: 'coloring/001.html', app: 'coloring', type: 'hero' },
      { file: 'matching/002.html', app: 'matching', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'drawing-lines/004.html', app: 'drawing-lines', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-addition-worksheets',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'math-worksheet/002.html', app: 'math-worksheet', type: 'features' },
      { file: 'code-addition/003.html', app: 'code-addition', type: 'progression' },
      { file: 'subtraction/004.html', app: 'subtraction', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-subtraction-worksheets',
    visuals: [
      { file: 'subtraction/001.html', app: 'subtraction', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'math-worksheet/003.html', app: 'math-worksheet', type: 'progression' },
      { file: 'code-addition/004.html', app: 'code-addition', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-word-search-puzzles',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'crossword/002.html', app: 'crossword', type: 'features' },
      { file: 'word-scramble/003.html', app: 'word-scramble', type: 'progression' },
      { file: 'cryptogram/004.html', app: 'cryptogram', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-crossword-puzzles',
    visuals: [
      { file: 'crossword/001.html', app: 'crossword', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'word-scramble/003.html', app: 'word-scramble', type: 'progression' },
      { file: 'cryptogram/004.html', app: 'cryptogram', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-math-puzzle-worksheets',
    visuals: [
      { file: 'math-puzzle/001.html', app: 'math-puzzle', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'subtraction/003.html', app: 'subtraction', type: 'progression' },
      { file: 'code-addition/004.html', app: 'code-addition', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-handwriting-sheets',
    visuals: [
      { file: 'writing/001.html', app: 'writing', type: 'hero' },
      { file: 'alphabet-train/002.html', app: 'alphabet-train', type: 'features' },
      { file: 'drawing-lines/003.html', app: 'drawing-lines', type: 'progression' },
      { file: 'word-guess/004.html', app: 'word-guess', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-coloring-pages',
    visuals: [
      { file: 'coloring/001.html', app: 'coloring', type: 'hero' },
      { file: 'draw-and-color/002.html', app: 'draw-and-color', type: 'features' },
      { file: 'drawing-lines/003.html', app: 'drawing-lines', type: 'progression' },
      { file: 'pattern-worksheet/004.html', app: 'pattern-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-bingo-cards',
    visuals: [
      { file: 'bingo/001.html', app: 'bingo', type: 'hero' },
      { file: 'matching/002.html', app: 'matching', type: 'features' },
      { file: 'picture-sort/003.html', app: 'picture-sort', type: 'progression' },
      { file: 'grid-match/004.html', app: 'grid-match', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-matching-worksheets',
    visuals: [
      { file: 'matching/001.html', app: 'matching', type: 'hero' },
      { file: 'bingo/002.html', app: 'bingo', type: 'features' },
      { file: 'grid-match/003.html', app: 'grid-match', type: 'progression' },
      { file: 'shadow-match/004.html', app: 'shadow-match', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-pattern-worksheets',
    visuals: [
      { file: 'pattern-worksheet/001.html', app: 'pattern-worksheet', type: 'hero' },
      { file: 'pattern-train/002.html', app: 'pattern-train', type: 'features' },
      { file: 'big-small/003.html', app: 'big-small', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-picture-sudoku',
    visuals: [
      { file: 'sudoku/001.html', app: 'sudoku', type: 'hero' },
      { file: 'pattern-worksheet/002.html', app: 'pattern-worksheet', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'bingo/004.html', app: 'bingo', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-maze-worksheets',
    visuals: [
      { file: 'picture-path/001.html', app: 'picture-path', type: 'hero' },
      { file: 'sudoku/002.html', app: 'sudoku', type: 'features' },
      { file: 'treasure-hunt/003.html', app: 'treasure-hunt', type: 'progression' },
      { file: 'find-objects/004.html', app: 'find-objects', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-hidden-object-worksheets',
    visuals: [
      { file: 'find-objects/001.html', app: 'find-objects', type: 'hero' },
      { file: 'find-and-count/002.html', app: 'find-and-count', type: 'features' },
      { file: 'picture-path/003.html', app: 'picture-path', type: 'progression' },
      { file: 'wordsearch/004.html', app: 'wordsearch', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-size-comparison-worksheets',
    visuals: [
      { file: 'big-small/001.html', app: 'big-small', type: 'hero' },
      { file: 'more-less/002.html', app: 'more-less', type: 'features' },
      { file: 'pattern-worksheet/003.html', app: 'pattern-worksheet', type: 'progression' },
      { file: 'odd-one-out/004.html', app: 'odd-one-out', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-counting-worksheets',
    visuals: [
      { file: 'chart-count/001.html', app: 'chart-count', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'more-less/003.html', app: 'more-less', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-drawing-worksheets',
    visuals: [
      { file: 'draw-and-color/001.html', app: 'draw-and-color', type: 'hero' },
      { file: 'drawing-lines/002.html', app: 'drawing-lines', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'pattern-train/004.html', app: 'pattern-train', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-sorting-worksheets',
    visuals: [
      { file: 'picture-sort/001.html', app: 'picture-sort', type: 'hero' },
      { file: 'matching/002.html', app: 'matching', type: 'features' },
      { file: 'odd-one-out/003.html', app: 'odd-one-out', type: 'progression' },
      { file: 'bingo/004.html', app: 'bingo', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-shadow-matching-worksheets',
    visuals: [
      { file: 'shadow-match/001.html', app: 'shadow-match', type: 'hero' },
      { file: 'matching/002.html', app: 'matching', type: 'features' },
      { file: 'picture-sort/003.html', app: 'picture-sort', type: 'progression' },
      { file: 'odd-one-out/004.html', app: 'odd-one-out', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-odd-one-out-puzzles',
    visuals: [
      { file: 'odd-one-out/001.html', app: 'odd-one-out', type: 'hero' },
      { file: 'shadow-match/002.html', app: 'shadow-match', type: 'features' },
      { file: 'missing-pieces/003.html', app: 'missing-pieces', type: 'progression' },
      { file: 'picture-sort/003.html', app: 'picture-sort', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-missing-pieces-puzzles',
    visuals: [
      { file: 'missing-pieces/001.html', app: 'missing-pieces', type: 'hero' },
      { file: 'odd-one-out/002.html', app: 'odd-one-out', type: 'features' },
      { file: 'shadow-match/003.html', app: 'shadow-match', type: 'progression' },
      { file: 'grid-match/004.html', app: 'grid-match', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-treasure-hunt-worksheets',
    visuals: [
      { file: 'treasure-hunt/001.html', app: 'treasure-hunt', type: 'hero' },
      { file: 'find-objects/002.html', app: 'find-objects', type: 'features' },
      { file: 'picture-path/003.html', app: 'picture-path', type: 'progression' },
      { file: 'grid-match/004.html', app: 'grid-match', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-alphabet-worksheets',
    visuals: [
      { file: 'alphabet-train/001.html', app: 'alphabet-train', type: 'hero' },
      { file: 'writing/002.html', app: 'writing', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'pattern-train/004.html', app: 'pattern-train', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-preposition-worksheets',
    visuals: [
      { file: 'prepositions/001.html', app: 'prepositions', type: 'hero' },
      { file: 'alphabet-train/002.html', app: 'alphabet-train', type: 'features' },
      { file: 'word-guess/003.html', app: 'word-guess', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-cryptogram-puzzles',
    visuals: [
      { file: 'cryptogram/001.html', app: 'cryptogram', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'word-scramble/003.html', app: 'word-scramble', type: 'progression' },
      { file: 'word-guess/004.html', app: 'word-guess', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-chart-count-worksheets',
    visuals: [
      { file: 'chart-count/001.html', app: 'chart-count', type: 'hero' },
      { file: 'big-small/002.html', app: 'big-small', type: 'features' },
      { file: 'pattern-train/003.html', app: 'pattern-train', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-worksheet-bundles',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'niche-selection-printables',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'coloring/002.html', app: 'coloring', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'create-printable-product-line',
    visuals: [
      { file: 'matching/001.html', app: 'matching', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'wordsearch/004.html', app: 'wordsearch', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'pricing-educational-printables',
    visuals: [
      { file: 'math-worksheet/001.html', app: 'math-worksheet', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'scale-printable-business-guide',
    visuals: [
      { file: 'draw-and-color/001.html', app: 'draw-and-color', type: 'hero' },
      { file: 'math-worksheet/002.html', app: 'math-worksheet', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'passive-income-worksheets',
    visuals: [
      { file: 'math-worksheet/001.html', app: 'math-worksheet', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'understanding-commercial-licenses',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'research-profitable-niches',
    visuals: [
      { file: 'matching/001.html', app: 'matching', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'math-worksheet/004.html', app: 'math-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'multilingual-printable-business',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'word-guess/002.html', app: 'word-guess', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'worksheets-multiple-languages',
    visuals: [
      { file: 'alphabet-train/001.html', app: 'alphabet-train', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'word-guess/003.html', app: 'word-guess', type: 'progression' },
      { file: 'prepositions/004.html', app: 'prepositions', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'copyright-printable-sellers',
    visuals: [
      { file: 'writing/001.html', app: 'writing', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'math-worksheet/004.html', app: 'math-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'customer-support-digital-products',
    visuals: [
      { file: 'matching/001.html', app: 'matching', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'math-worksheet/004.html', app: 'math-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'automate-printable-business',
    visuals: [
      { file: 'math-worksheet/001.html', app: 'math-worksheet', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'social-media-printable-marketing',
    visuals: [
      { file: 'bingo/001.html', app: 'bingo', type: 'hero' },
      { file: 'coloring/002.html', app: 'coloring', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'pinterest-marketing-worksheets',
    visuals: [
      { file: 'coloring/001.html', app: 'coloring', type: 'hero' },
      { file: 'bingo/002.html', app: 'bingo', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'email-marketing-printables',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'coloring/002.html', app: 'coloring', type: 'features' },
      { file: 'addition/003.html', app: 'addition', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'get-reviews-printable-products',
    visuals: [
      { file: 'matching/001.html', app: 'matching', type: 'hero' },
      { file: 'coloring/002.html', app: 'coloring', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'seasonal-marketing-printables',
    visuals: [
      { file: 'bingo/001.html', app: 'bingo', type: 'hero' },
      { file: 'coloring/002.html', app: 'coloring', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'find-and-count/004.html', app: 'find-and-count', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'digital-vs-physical-printables',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'coloring/002.html', app: 'coloring', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'bingo/004.html', app: 'bingo', type: 'fun' },
    ],
  },
  {
    pageType: 'guide',
    pageId: 'quality-standards-worksheets',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'math-worksheet/004.html', app: 'math-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'bundle',
    pageId: 'math-bundle',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'subtraction/002.html', app: 'subtraction', type: 'features' },
      { file: 'code-addition/003.html', app: 'code-addition', type: 'progression' },
      { file: 'more-less/004.html', app: 'more-less', type: 'fun' },
    ],
  },
  {
    pageType: 'bundle',
    pageId: 'literacy-bundle',
    visuals: [
      { file: 'alphabet-train/001.html', app: 'alphabet-train', type: 'hero' },
      { file: 'prepositions/002.html', app: 'prepositions', type: 'features' },
      { file: 'word-guess/003.html', app: 'word-guess', type: 'progression' },
      { file: 'word-scramble/004.html', app: 'word-scramble', type: 'fun' },
    ],
  },
  {
    pageType: 'bundle',
    pageId: 'visual-bundle',
    visuals: [
      { file: 'big-small/001.html', app: 'big-small', type: 'hero' },
      { file: 'pattern-train/002.html', app: 'pattern-train', type: 'features' },
      { file: 'pattern-worksheet/003.html', app: 'pattern-worksheet', type: 'progression' },
      { file: 'draw-and-color/004.html', app: 'draw-and-color', type: 'fun' },
    ],
  },
  {
    pageType: 'bundle',
    pageId: 'matching-bundle',
    visuals: [
      { file: 'matching/001.html', app: 'matching', type: 'hero' },
      { file: 'grid-match/002.html', app: 'grid-match', type: 'features' },
      { file: 'shadow-match/003.html', app: 'shadow-match', type: 'progression' },
      { file: 'bingo/004.html', app: 'bingo', type: 'fun' },
    ],
  },
  {
    pageType: 'bundle',
    pageId: 'puzzle-bundle',
    visuals: [
      { file: 'missing-pieces/001.html', app: 'missing-pieces', type: 'hero' },
      { file: 'odd-one-out/002.html', app: 'odd-one-out', type: 'features' },
      { file: 'sudoku/003.html', app: 'sudoku', type: 'progression' },
      { file: 'picture-path/004.html', app: 'picture-path', type: 'fun' },
    ],
  },
  {
    pageType: 'bundle',
    pageId: 'search-bundle',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'find-objects/002.html', app: 'find-objects', type: 'features' },
      { file: 'crossword/003.html', app: 'crossword', type: 'progression' },
      { file: 'treasure-hunt/004.html', app: 'treasure-hunt', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'farm-animals-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'ocean-animals-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'safari-animals-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'pets-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'dinosaur-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'birds-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'insects-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'forest-animals-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'christmas-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'halloween-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'easter-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'valentines-day-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'back-to-school-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'summer-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'winter-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'spring-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'thanksgiving-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'parents-day-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'space-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'transportation-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'food-cooking-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'sports-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'music-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'construction-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'pirates-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'fairy-tale-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'camping-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'underwater-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'preschool-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'kindergarten-printable-ideas',
    visuals: [
      { file: 'find-and-count/001.html', app: 'find-and-count', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'first-grade-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'second-grade-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'third-grade-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'homeschool-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'special-education-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'esl-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'summer-learning-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'math-facts-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'subscription-box-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'print-on-demand-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'digital-download-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'physical-printable-product-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'matching/003.html', app: 'matching', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'party-supply-printable-ideas',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'coloring/002.html', app: 'coloring', type: 'features' },
      { file: 'bingo/003.html', app: 'bingo', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'custom-worksheet-service-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'bingo/004.html', app: 'bingo', type: 'fun' },
    ],
  },
  {
    pageType: 'idea',
    pageId: 'bulk-licensing-printable-ideas',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'bingo/004.html', app: 'bingo', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'complete-guide-printable-business',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'matching/004.html', app: 'matching', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'create-worksheets-that-sell',
    visuals: [
      { file: 'addition/001.html', app: 'addition', type: 'hero' },
      { file: 'subtraction/002.html', app: 'subtraction', type: 'features' },
      { file: 'wordsearch/003.html', app: 'wordsearch', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'printable-business-blueprint',
    visuals: [
      { file: 'math-puzzle/001.html', app: 'math-puzzle', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'addition/004.html', app: 'addition', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'etsy-printable-business',
    visuals: [
      { file: 'coloring/001.html', app: 'coloring', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'addition/003.html', app: 'addition', type: 'progression' },
      { file: 'find-and-count/004.html', app: 'find-and-count', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'amazon-kdp-activity-books',
    visuals: [
      { file: 'sudoku/001.html', app: 'sudoku', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'math-puzzle/003.html', app: 'math-puzzle', type: 'progression' },
      { file: 'crossword/004.html', app: 'crossword', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'create-multilingual-worksheets',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'crossword/002.html', app: 'crossword', type: 'features' },
      { file: 'word-scramble/003.html', app: 'word-scramble', type: 'progression' },
      { file: 'alphabet-train/004.html', app: 'alphabet-train', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'commercial-license-guide',
    visuals: [
      { file: 'wordsearch/001.html', app: 'wordsearch', type: 'hero' },
      { file: 'addition/002.html', app: 'addition', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'crossword/004.html', app: 'crossword', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'printable-business-income',
    visuals: [
      { file: 'math-worksheet/001.html', app: 'math-worksheet', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'sudoku/004.html', app: 'sudoku', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'tools-for-printable-business',
    visuals: [
      { file: 'matching/001.html', app: 'matching', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'math-worksheet/003.html', app: 'math-worksheet', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'marketing-printable-business',
    visuals: [
      { file: 'bingo/001.html', app: 'bingo', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'coloring/003.html', app: 'coloring', type: 'progression' },
      { file: 'math-worksheet/004.html', app: 'math-worksheet', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'scaling-printable-business',
    visuals: [
      { file: 'draw-and-color/001.html', app: 'draw-and-color', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'math-worksheet/003.html', app: 'math-worksheet', type: 'progression' },
      { file: 'coloring/004.html', app: 'coloring', type: 'fun' },
    ],
  },
  {
    pageType: 'start',
    pageId: 'printable-business-legal',
    visuals: [
      { file: 'writing/001.html', app: 'writing', type: 'hero' },
      { file: 'wordsearch/002.html', app: 'wordsearch', type: 'features' },
      { file: 'math-worksheet/003.html', app: 'math-worksheet', type: 'progression' },
      { file: 'crossword/004.html', app: 'crossword', type: 'fun' },
    ],
  },
];
