/**
 * "New worksheets" strip on the /worksheets hub — v2 GROUPS: the 20 nt20
 * family cards, each with its variation landing slugs (chips). GENERATED by
 * scripts/seo-landing/gen-var-highlights.js from the landing corpora —
 * re-run it after landing content changes; missing slugs are omitted at
 * render, so trimming is always safe.
 */
export interface NewWorksheetGroup { base: string; variations: string[] }
export const NEW_WORKSHEET_GROUPS: Record<string, NewWorksheetGroup[]> = {
  "en": [
    {
      "base": "pre-writing-tracing-lines",
      "variations": [
        "tracing-zigzag-lines",
        "tracing-wavy-lines",
        "tracing-loops-and-spirals",
        "advanced-pre-writing-practice",
        "pre-writing-review"
      ]
    },
    {
      "base": "number-tracing-0-9",
      "variations": [
        "number-tracing-0-4",
        "number-tracing-5-9",
        "trace-and-write-numbers-0-9",
        "number-tracing-1-10",
        "teen-number-tracing-11-20"
      ]
    },
    {
      "base": "capital-letter-tracing",
      "variations": [
        "letter-tracing-g-to-l",
        "letter-tracing-m-to-r",
        "letter-tracing-s-to-z",
        "vowel-tracing-a-e-i-o-u",
        "big-letter-tracing-abcd"
      ]
    },
    {
      "base": "sight-words-read-trace-write",
      "variations": [
        "sight-words-set-2",
        "sight-words-set-3",
        "sight-words-set-4",
        "sight-words-set-5",
        "sight-words-set-6"
      ]
    },
    {
      "base": "cut-and-paste-sorting",
      "variations": [
        "cut-and-paste-vehicles",
        "cut-and-paste-fruits",
        "cut-and-paste-toys",
        "cut-and-paste-two-groups"
      ]
    },
    {
      "base": "color-by-code",
      "variations": [
        "color-by-shape-code",
        "color-by-number-1-6",
        "subtraction-color-by-code",
        "add-and-subtract-color-by-code",
        "color-by-code-sums-to-20"
      ]
    },
    {
      "base": "maze-worksheet",
      "variations": [
        "easy-maze",
        "hard-maze",
        "giant-maze",
        "animal-maze",
        "fruit-maze"
      ]
    },
    {
      "base": "number-bonds-to-10",
      "variations": [
        "number-bonds-to-5",
        "number-bonds-within-10",
        "number-bonds-to-20",
        "number-bonds-missing-whole",
        "make-ten-number-bonds"
      ]
    },
    {
      "base": "mental-math-within-20",
      "variations": [
        "mental-math-within-10",
        "missing-number-equations-to-20",
        "addition-facts-to-20",
        "subtraction-facts-to-20",
        "missing-number-equations-to-10"
      ]
    },
    {
      "base": "fact-families",
      "variations": [
        "fact-families-to-10",
        "fact-family-houses-to-20",
        "fact-house-practice-to-10",
        "fact-families-missing-partner",
        "multiplication-and-division-fact-families"
      ]
    },
    {
      "base": "number-words",
      "variations": [
        "number-words-to-20",
        "tens-in-words-to-100",
        "match-numbers-to-number-words",
        "number-words-to-50",
        "write-the-number-words"
      ]
    },
    {
      "base": "counting-coins",
      "variations": [
        "counting-coins-first-steps",
        "counting-money-all-coins",
        "coin-counting-practice",
        "counting-pennies-and-nickels",
        "which-purse-has-more-money"
      ]
    },
    {
      "base": "draw-the-clock-hands",
      "variations": [
        "draw-clock-hands-to-the-hour",
        "draw-clock-hands-half-past",
        "draw-clock-hands-quarter-hours",
        "draw-clock-hands-to-five-minutes",
        "draw-clock-hands-mixed-times"
      ]
    },
    {
      "base": "word-problems-with-pictures",
      "variations": [
        "addition-word-problems-with-pictures",
        "subtraction-word-problems-with-pictures",
        "word-problems-within-10",
        "word-problem-practice-three-stories",
        "animal-word-problems-with-pictures"
      ]
    },
    {
      "base": "column-addition-and-subtraction",
      "variations": [
        "2-digit-column-addition",
        "2-digit-column-subtraction",
        "3-digit-column-addition-and-subtraction",
        "3-digit-column-addition",
        "column-method-review"
      ]
    },
    {
      "base": "capacity-and-mass-metric",
      "variations": [
        "reading-measuring-jugs",
        "balance-scales-in-grams",
        "reading-scales-in-50-ml-steps",
        "measuring-jugs-to-2000-ml",
        "capacity-and-mass-with-animals"
      ]
    },
    {
      "base": "symmetry-drawing",
      "variations": [
        "easy-symmetry-drawing",
        "hard-symmetry-drawing",
        "mirror-pictures-heart-and-butterfly",
        "mirror-pictures-house-and-crown",
        "symmetry-mirror-below-the-line"
      ]
    },
    {
      "base": "reading-comprehension",
      "variations": [
        "red-kite-reading-comprehension",
        "lost-boot-reading-comprehension",
        "little-garden-reading-comprehension",
        "rainy-school-day-reading-comprehension",
        "birthday-surprise-reading-comprehension"
      ]
    },
    {
      "base": "regrouping-addition-and-subtraction",
      "variations": [
        "2-digit-addition-with-regrouping",
        "2-digit-subtraction-with-regrouping",
        "3-digit-addition-with-regrouping",
        "subtracting-across-zeros",
        "mixed-regrouping-review"
      ]
    },
    {
      "base": "times-tables-practice",
      "variations": [
        "times-table-of-2",
        "times-table-of-5",
        "times-table-of-10",
        "times-table-of-3",
        "times-table-of-4"
      ]
    }
  ],
  "de": [
    {
      "base": "schwunguebungen-vorschule",
      "variations": [
        "schwunguebungen-zacken-und-zickzack",
        "schwunguebungen-wellen-und-boegen",
        "schwunguebungen-schleifen-und-spiralen",
        "schwunguebungen-fuer-profis",
        "schwunguebungen-wiederholung"
      ]
    },
    {
      "base": "zahlen-schreiben-lernen",
      "variations": [
        "ziffern-schreiben-0-bis-4",
        "ziffern-schreiben-5-bis-9",
        "zahlen-nachspuren-und-schreiben",
        "zahlen-schreiben-1-bis-10",
        "zahlen-schreiben-11-bis-20"
      ]
    },
    {
      "base": "buchstaben-nachspuren",
      "variations": [
        "buchstaben-nachspuren-g-bis-l",
        "buchstaben-nachspuren-m-bis-r",
        "buchstaben-nachspuren-s-bis-z",
        "umlaute-nachspuren",
        "erste-buchstaben-abcd"
      ]
    },
    {
      "base": "lernwoerter-ueben",
      "variations": [
        "lernwoerter-liste-2",
        "lernwoerter-liste-3",
        "lernwoerter-liste-4",
        "lernwoerter-liste-5",
        "lernwoerter-liste-6"
      ]
    },
    {
      "base": "ausschneiden-und-aufkleben",
      "variations": [
        "ausschneiden-und-aufkleben-fahrzeuge",
        "ausschneiden-und-aufkleben-obst",
        "ausschneiden-und-aufkleben-spielzeug",
        "ausschneiden-und-sortieren-zwei-gruppen"
      ]
    },
    {
      "base": "rechnen-und-ausmalen",
      "variations": [
        "formen-nach-farbcode-ausmalen",
        "malen-nach-zahlen",
        "minus-rechnen-und-ausmalen",
        "plus-und-minus-ausmalen",
        "plusaufgaben-bis-20-ausmalen"
      ]
    },
    {
      "base": "labyrinth-arbeitsblaetter",
      "variations": [
        "leichtes-labyrinth",
        "schweres-labyrinth",
        "riesenlabyrinth",
        "labyrinth-tiere",
        "labyrinth-obst"
      ]
    },
    {
      "base": "zahlzerlegung-bis-10",
      "variations": [
        "zahlzerlegung-bis-5",
        "zahlen-bis-10-zerlegen",
        "zahlzerlegung-bis-20",
        "zahlzerlegung-das-ganze-fehlt",
        "verliebte-zahlen-zehnerfreunde"
      ]
    },
    {
      "base": "kopfrechnen-bis-20",
      "variations": [
        "kopfrechnen-bis-10",
        "platzhalteraufgaben-bis-20",
        "plusaufgaben-bis-20",
        "minusaufgaben-bis-20",
        "platzhalteraufgaben-bis-10"
      ]
    },
    {
      "base": "aufgabenfamilien",
      "variations": [
        "aufgabenfamilien-bis-10",
        "rechenhaeuser-bis-20",
        "rechenhaeuser-bis-10",
        "aufgabenfamilien-fehlende-mittelzahl",
        "aufgabenfamilien-mal-und-geteilt"
      ]
    },
    {
      "base": "zahlwoerter-lesen",
      "variations": [
        "zahlwoerter-bis-20",
        "zahlwoerter-zehner-bis-100",
        "zahlen-und-zahlwoerter-verbinden",
        "zahlwoerter-bis-50",
        "zahlwoerter-schreiben"
      ]
    },
    {
      "base": "rechnen-mit-geld",
      "variations": [
        "muenzen-zaehlen-erste-schritte",
        "geld-zaehlen-alle-muenzen",
        "muenzen-zaehlen-uebungsblatt",
        "zaehlen-mit-1-und-2-cent",
        "welcher-geldbeutel-hat-mehr"
      ]
    },
    {
      "base": "uhrzeiger-einzeichnen",
      "variations": [
        "uhrzeiger-einzeichnen-volle-stunden",
        "uhrzeiger-einzeichnen-halbe-stunden",
        "uhrzeiger-einzeichnen-viertelstunden",
        "uhrzeiger-einzeichnen-fuenf-minuten-schritte",
        "uhrzeiger-einzeichnen-gemischt"
      ]
    },
    {
      "base": "rechengeschichten-mit-bildern",
      "variations": [
        "rechengeschichten-plusaufgaben",
        "rechengeschichten-minusaufgaben",
        "rechengeschichten-bis-10",
        "drei-rechengeschichten",
        "rechengeschichten-mit-tieren"
      ]
    },
    {
      "base": "schriftlich-rechnen-ohne-uebertrag",
      "variations": [
        "schriftliche-addition-ohne-uebertrag",
        "schriftliche-subtraktion-ohne-uebertrag",
        "schriftlich-rechnen-dreistellig-gemischt",
        "dreistellige-zahlen-addieren",
        "schriftlich-rechnen-uebungsmix"
      ]
    },
    {
      "base": "milliliter-und-gramm",
      "variations": [
        "messbecher-ablesen-milliliter",
        "waagen-ablesen-gramm",
        "skalen-ablesen-50-ml-schritte",
        "messbecher-bis-2000-ml",
        "messbecher-und-waagen-tiere"
      ]
    },
    {
      "base": "symmetrie-spiegeln",
      "variations": [
        "leichte-spiegelbilder",
        "schwere-spiegelbilder",
        "spiegelbilder-herz-und-schmetterling",
        "spiegelbilder-haus-und-krone",
        "spiegeln-an-der-waagerechten-achse"
      ]
    },
    {
      "base": "lesetext-mit-fragen",
      "variations": [
        "lesetext-der-kleine-igel",
        "lesetext-bei-der-feuerwehr",
        "lesetext-ein-tag-am-meer",
        "lesetext-der-turnbeutel",
        "lesetext-der-schneetag"
      ]
    },
    {
      "base": "schriftlich-rechnen-mit-uebertrag",
      "variations": [
        "schriftliche-addition-mit-uebertrag",
        "schriftliche-subtraktion-mit-uebertrag",
        "schriftliche-addition-dreistellig",
        "subtrahieren-mit-nullen",
        "schriftlich-rechnen-gemischt"
      ]
    },
    {
      "base": "einmaleins-ueben",
      "variations": [
        "2er-einmaleins",
        "5er-einmaleins",
        "10er-einmaleins",
        "3er-einmaleins",
        "4er-einmaleins"
      ]
    }
  ],
  "es": [
    {
      "base": "grafomotricidad-trazos",
      "variations": [
        "grafomotricidad-rectas-y-zigzag",
        "grafomotricidad-ondas-y-curvas",
        "bucles-espirales-y-ochos",
        "grafomotricidad-avanzada",
        "repaso-de-trazos"
      ]
    },
    {
      "base": "numeros-punteados-0-9",
      "variations": [
        "numeros-punteados-0-4",
        "numeros-punteados-5-9",
        "repasa-y-escribe-los-numeros",
        "numeros-punteados-1-10",
        "numeros-punteados-11-20"
      ]
    },
    {
      "base": "abecedario-punteado-mayusculas",
      "variations": [
        "letras-punteadas-g-l",
        "letras-punteadas-m-r",
        "letras-punteadas-s-z",
        "la-letra-n-punteada",
        "mis-primeras-letras-a-b-c-d"
      ]
    },
    {
      "base": "palabras-de-uso-frecuente",
      "variations": [
        "palabras-frecuentes-lista-2",
        "palabras-frecuentes-lista-3",
        "palabras-frecuentes-lista-4",
        "palabras-frecuentes-lista-5",
        "palabras-frecuentes-lista-6"
      ]
    },
    {
      "base": "recortar-y-pegar",
      "variations": [
        "recortar-y-pegar-vehiculos",
        "recortar-y-pegar-frutas",
        "recortar-y-pegar-juguetes",
        "recorta-y-pega-en-dos-grupos"
      ]
    },
    {
      "base": "colorear-por-numeros",
      "variations": [
        "colorear-segun-la-figura",
        "colorear-por-numeros-infantil",
        "colorear-con-restas",
        "colorear-sumas-y-restas",
        "colorear-sumas-hasta-20"
      ]
    },
    {
      "base": "laberintos-infantil",
      "variations": [
        "laberinto-facil-frutas",
        "laberinto-dificil-vehiculos",
        "laberinto-gigante-juguetes",
        "laberinto-de-animales",
        "laberinto-de-frutas"
      ]
    },
    {
      "base": "amigos-del-10",
      "variations": [
        "amigos-del-5",
        "descomposicion-hasta-10",
        "amigos-del-20",
        "las-partes-y-el-todo",
        "amigos-del-10-con-puntos"
      ]
    },
    {
      "base": "calculo-mental-hasta-20",
      "variations": [
        "calculo-mental-hasta-10",
        "el-numero-que-falta-hasta-20",
        "sumas-mentales-hasta-20",
        "restas-mentales-hasta-20",
        "el-numero-que-falta-hasta-10"
      ]
    },
    {
      "base": "familias-de-operaciones",
      "variations": [
        "casitas-de-operaciones-hasta-10",
        "casitas-de-operaciones-hasta-20",
        "mas-casitas-de-sumas-y-restas",
        "casitas-el-numero-escondido",
        "familias-de-multiplicar-y-dividir"
      ]
    },
    {
      "base": "numeros-en-letras",
      "variations": [
        "numeros-en-letras-hasta-20",
        "las-decenas-en-letras",
        "une-numeros-con-palabras",
        "numeros-en-letras-hasta-50",
        "escribe-los-numeros-en-letras"
      ]
    },
    {
      "base": "contar-monedas",
      "variations": [
        "contar-monedas-primeros-pasos",
        "contar-con-todas-las-monedas",
        "practica-de-contar-monedas",
        "monedas-de-1-y-2-centimos",
        "que-monedero-tiene-mas-dinero"
      ]
    },
    {
      "base": "dibujar-las-agujas-del-reloj",
      "variations": [
        "dibujar-las-agujas-en-punto",
        "dibujar-las-agujas-y-media",
        "dibujar-las-agujas-y-cuarto",
        "dibujar-las-agujas-de-5-en-5",
        "repaso-de-las-horas-del-reloj"
      ]
    },
    {
      "base": "problemas-de-suma-y-resta",
      "variations": [
        "problemas-de-sumas-con-dibujos",
        "problemas-de-restas-con-dibujos",
        "problemas-hasta-10",
        "tres-problemas-con-dibujos",
        "problemas-con-dibujos-de-animales"
      ]
    },
    {
      "base": "sumas-y-restas-sin-llevar",
      "variations": [
        "sumas-sin-llevar-de-dos-cifras",
        "restas-sin-llevar-de-dos-cifras",
        "sumas-y-restas-de-tres-cifras-sin-llevar",
        "sumas-sin-llevar-de-tres-cifras",
        "repaso-de-cuentas-sin-llevar"
      ]
    },
    {
      "base": "capacidad-y-masa",
      "variations": [
        "leer-jarras-medidoras-ml",
        "leer-la-balanza-en-gramos",
        "escalas-con-marcas-de-50-ml",
        "jarras-medidoras-hasta-2000-ml",
        "capacidad-y-masa-con-animales"
      ]
    },
    {
      "base": "simetria-en-cuadricula",
      "variations": [
        "simetria-en-cuadricula-facil",
        "simetria-en-cuadricula-dificil",
        "simetria-corazon-y-mariposa",
        "simetria-casa-y-corona",
        "simetria-con-eje-horizontal"
      ]
    },
    {
      "base": "comprension-lectora",
      "variations": [
        "comprension-lectora-la-caracola",
        "comprension-lectora-el-huerto",
        "comprension-lectora-la-tormenta",
        "comprension-lectora-el-tren",
        "comprension-lectora-el-teatro"
      ]
    },
    {
      "base": "sumas-y-restas-con-llevadas",
      "variations": [
        "sumas-con-llevadas-dos-cifras",
        "restas-con-llevadas",
        "sumas-con-llevadas-tres-cifras",
        "restas-con-llevadas-y-ceros",
        "repaso-sumas-y-restas-con-llevadas"
      ]
    },
    {
      "base": "tablas-de-multiplicar",
      "variations": [
        "tabla-del-2",
        "tabla-del-5",
        "tabla-del-10",
        "tabla-del-3",
        "tabla-del-4"
      ]
    }
  ],
  "fr": [
    {
      "base": "graphisme-maternelle",
      "variations": [
        "graphisme-lignes-et-zigzags",
        "graphisme-vagues-et-ponts",
        "graphisme-boucles-et-spirales",
        "graphisme-traces-difficiles",
        "graphisme-la-grande-revision"
      ]
    },
    {
      "base": "ecriture-des-chiffres",
      "variations": [
        "ecriture-des-chiffres-0-4",
        "ecriture-des-chiffres-5-9",
        "repasser-et-ecrire-les-chiffres",
        "ecriture-des-nombres-1-10",
        "ecriture-des-nombres-11-20"
      ]
    },
    {
      "base": "ecriture-lettres-capitales",
      "variations": [
        "ecriture-des-lettres-g-l",
        "ecriture-des-lettres-m-r",
        "ecriture-des-lettres-s-z",
        "ecriture-des-lettres-accentuees",
        "premieres-lettres-a-b-c-d"
      ]
    },
    {
      "base": "mots-outils",
      "variations": [
        "mots-outils-liste-2",
        "mots-outils-liste-3",
        "mots-outils-liste-4",
        "mots-outils-liste-5",
        "mots-outils-liste-6"
      ]
    },
    {
      "base": "decoupage-collage",
      "variations": [
        "decoupage-collage-vehicules",
        "decoupage-collage-fruits",
        "decoupage-collage-jouets",
        "decoupage-collage-deux-groupes"
      ]
    },
    {
      "base": "coloriage-magique",
      "variations": [
        "coloriage-magique-des-formes",
        "coloriage-par-numeros",
        "coloriage-magique-soustraction",
        "coloriage-magique-addition-et-soustraction",
        "coloriage-magique-sommes-11-20"
      ]
    },
    {
      "base": "labyrinthe-maternelle",
      "variations": [
        "labyrinthe-facile",
        "labyrinthe-difficile",
        "labyrinthe-geant",
        "labyrinthe-des-animaux",
        "labyrinthe-des-fruits"
      ]
    },
    {
      "base": "complements-a-10",
      "variations": [
        "complements-a-5",
        "decomposition-des-nombres-jusqu-a-10",
        "complements-a-20",
        "complements-trouver-le-tout",
        "complements-a-10-avec-points"
      ]
    },
    {
      "base": "calcul-mental-cp",
      "variations": [
        "calcul-mental-jusqu-a-10",
        "nombre-manquant-jusqu-a-20",
        "calcul-mental-additions-jusqu-a-20",
        "calcul-mental-soustractions-jusqu-a-20",
        "nombre-manquant-jusqu-a-10"
      ]
    },
    {
      "base": "familles-operations",
      "variations": [
        "familles-operations-jusqu-a-10",
        "familles-operations-jusqu-a-20",
        "maisons-des-nombres-jusqu-a-10",
        "familles-operations-nombre-cache",
        "familles-multiplication-division"
      ]
    },
    {
      "base": "nombres-en-lettres",
      "variations": [
        "nombres-en-lettres-jusqu-a-20",
        "dizaines-en-lettres",
        "relier-nombres-et-mots",
        "nombres-en-lettres-jusqu-a-50",
        "ecrire-les-nombres-en-lettres"
      ]
    },
    {
      "base": "compter-la-monnaie",
      "variations": [
        "compter-la-monnaie-premiers-pas",
        "compter-toutes-les-pieces",
        "entrainement-compter-les-pieces",
        "compter-les-petites-pieces",
        "porte-monnaie-le-plus-d-argent"
      ]
    },
    {
      "base": "dessiner-les-aiguilles",
      "variations": [
        "dessiner-les-aiguilles-heures-piles",
        "dessiner-les-aiguilles-et-demie",
        "dessiner-les-aiguilles-et-quart",
        "dessiner-les-aiguilles-de-5-en-5",
        "dessiner-les-aiguilles-revision"
      ]
    },
    {
      "base": "petits-problemes",
      "variations": [
        "problemes-d-addition-en-images",
        "problemes-de-soustraction-en-images",
        "petits-problemes-jusqu-a-10",
        "trois-petits-problemes-en-images",
        "petits-problemes-animaux"
      ]
    },
    {
      "base": "operations-posees-sans-retenue",
      "variations": [
        "additions-posees-sans-retenue",
        "soustractions-posees-sans-retenue",
        "operations-posees-3-chiffres",
        "additions-posees-3-chiffres",
        "operations-posees-revision"
      ]
    },
    {
      "base": "masses-et-contenances",
      "variations": [
        "lire-le-verre-doseur-millilitres",
        "lire-la-balance-en-grammes",
        "lire-les-petites-graduations",
        "verres-doseurs-jusqu-a-2000-ml",
        "masses-et-contenances-animaux"
      ]
    },
    {
      "base": "symetrie-quadrillage",
      "variations": [
        "symetrie-quadrillage-facile",
        "symetrie-quadrillage-difficile",
        "symetrie-coeur-et-papillon",
        "symetrie-maison-et-couronne",
        "symetrie-axe-horizontal"
      ]
    },
    {
      "base": "lecture-comprehension",
      "variations": [
        "lecture-ce1-crabe-de-la-plage",
        "lecture-ce1-escargot-du-potager",
        "lecture-ce1-nuit-en-camping",
        "lecture-ce1-marche-du-samedi",
        "lecture-ce1-spectacle-de-l-ecole"
      ]
    },
    {
      "base": "operations-posees-avec-retenue",
      "variations": [
        "addition-avec-retenue",
        "soustraction-avec-retenue",
        "addition-3-chiffres-avec-retenue",
        "soustraction-avec-des-zeros",
        "additions-et-soustractions-avec-retenue"
      ]
    },
    {
      "base": "tables-de-multiplication",
      "variations": [
        "table-de-2",
        "table-de-5",
        "table-de-10",
        "table-de-3",
        "table-de-4"
      ]
    }
  ],
  "pt": [
    {
      "base": "grafismo-tracados",
      "variations": [
        "grafismo-retas-e-ziguezagues",
        "grafismo-ondas-e-curvas",
        "grafismo-lacos-e-espirais",
        "grafismo-avancado",
        "revisao-de-tracados"
      ]
    },
    {
      "base": "numeros-pontilhados",
      "variations": [
        "numeros-pontilhados-0-a-4",
        "numeros-pontilhados-5-a-9",
        "cubra-e-escreva-os-numeros",
        "numeros-pontilhados-1-a-10",
        "numeros-pontilhados-11-a-20"
      ]
    },
    {
      "base": "letras-pontilhadas",
      "variations": [
        "letras-pontilhadas-g-a-m",
        "letras-pontilhadas-n-a-s",
        "letras-pontilhadas-s-a-z",
        "letras-k-w-y",
        "primeiras-letras-abcd"
      ]
    },
    {
      "base": "palavras-frequentes",
      "variations": [
        "palavras-frequentes-lista-2",
        "palavras-frequentes-lista-3",
        "palavras-frequentes-lista-4",
        "palavras-frequentes-lista-5",
        "palavras-frequentes-lista-6"
      ]
    },
    {
      "base": "recorte-e-colagem",
      "variations": [
        "recorte-e-colagem-veiculos",
        "recorte-e-colagem-frutas",
        "recorte-e-colagem-brinquedos",
        "recorte-e-cole-em-dois-grupos"
      ]
    },
    {
      "base": "pinte-conforme-o-resultado",
      "variations": [
        "pinte-conforme-a-forma",
        "colorir-por-numeros",
        "colorir-com-continhas-de-menos",
        "colorir-com-mais-e-menos",
        "colorir-somas-ate-20"
      ]
    },
    {
      "base": "labirintos",
      "variations": [
        "labirinto-facil",
        "labirinto-dificil",
        "labirinto-gigante",
        "labirinto-de-animais",
        "labirinto-de-frutas"
      ]
    },
    {
      "base": "amigos-do-10",
      "variations": [
        "amigos-do-5",
        "amigos-dos-numeros-5-a-10",
        "amigos-do-20",
        "qual-e-o-todo",
        "amigos-do-10-com-bolinhas"
      ]
    },
    {
      "base": "calculo-mental-ate-20",
      "variations": [
        "calculo-mental-ate-10",
        "numero-que-falta-ate-20",
        "continhas-de-mais-ate-20",
        "continhas-de-menos-ate-20",
        "numero-que-falta-ate-10"
      ]
    },
    {
      "base": "familia-de-fatos",
      "variations": [
        "familia-de-fatos-ate-10",
        "familia-de-fatos-ate-20",
        "casinhas-matematicas-ate-10",
        "casinhas-com-numero-escondido",
        "casinhas-de-multiplicar-e-dividir"
      ]
    },
    {
      "base": "numeros-por-extenso",
      "variations": [
        "numeros-por-extenso-ate-20",
        "dezenas-por-extenso-10-a-100",
        "ligue-o-numero-ao-nome",
        "numeros-por-extenso-ate-50",
        "escreva-os-numeros-por-extenso"
      ]
    },
    {
      "base": "contando-moedas",
      "variations": [
        "contando-moedas-primeiros-passos",
        "contando-dinheiro-todas-as-moedas",
        "treino-de-contar-moedas",
        "moedas-de-5-e-10-centavos",
        "qual-carteira-tem-mais-dinheiro"
      ]
    },
    {
      "base": "desenhe-os-ponteiros",
      "variations": [
        "horas-em-ponto-no-relogio",
        "meia-hora-no-relogio",
        "quartos-de-hora-no-relogio",
        "horas-de-5-em-5-minutos",
        "revisao-de-horas-no-relogio"
      ]
    },
    {
      "base": "situacoes-problema",
      "variations": [
        "situacoes-problema-de-adicao",
        "situacoes-problema-de-subtracao",
        "situacoes-problema-ate-10",
        "tres-situacoes-problema",
        "situacoes-problema-com-animais"
      ]
    },
    {
      "base": "continhas-armadas",
      "variations": [
        "adicao-armada-2-algarismos",
        "subtracao-armada-2-algarismos",
        "continhas-armadas-3-algarismos",
        "adicao-armada-3-algarismos",
        "revisao-de-continhas-armadas"
      ]
    },
    {
      "base": "medidas-de-capacidade-e-massa",
      "variations": [
        "leitura-de-jarras-em-ml",
        "balancas-em-gramas",
        "escalas-de-50-em-50-ml",
        "jarras-grandes-ate-2000-ml",
        "jarras-e-balancas-com-animais"
      ]
    },
    {
      "base": "simetria-na-malha",
      "variations": [
        "simetria-facil-na-malha",
        "simetria-dificil-na-malha",
        "simetria-coracao-e-borboleta",
        "simetria-casa-e-coroa",
        "simetria-com-linha-horizontal"
      ]
    },
    {
      "base": "interpretacao-de-texto",
      "variations": [
        "interpretacao-o-castelo-de-areia",
        "interpretacao-a-padaria-do-seu-jose",
        "interpretacao-um-dia-no-sitio",
        "interpretacao-a-bicicleta-nova",
        "interpretacao-a-festa-junina"
      ]
    },
    {
      "base": "continhas-com-reagrupamento",
      "variations": [
        "adicao-com-vai-um",
        "subtracao-com-emprestimo",
        "adicao-com-vai-um-3-algarismos",
        "subtracao-emprestando-do-zero",
        "revisao-vai-um-e-emprestimo"
      ]
    },
    {
      "base": "tabuada",
      "variations": [
        "tabuada-do-2",
        "tabuada-do-5",
        "tabuada-do-10",
        "tabuada-do-3",
        "tabuada-do-4"
      ]
    }
  ],
  "it": [
    {
      "base": "pregrafismo-percorsi",
      "variations": [
        "pregrafismo-linee-rette-e-zigzag",
        "pregrafismo-onde-e-linee-curve",
        "pregrafismo-occhielli-otto-e-spirali",
        "pregrafismo-avanzato-cinque-corsie",
        "pregrafismo-ripasso-cinque-tracciati"
      ]
    },
    {
      "base": "numeri-tratteggiati",
      "variations": [
        "numeri-tratteggiati-da-0-a-4",
        "numeri-tratteggiati-da-5-a-9",
        "ripassa-e-scrivi-i-numeri",
        "numeri-tratteggiati-da-1-a-10",
        "numeri-tratteggiati-da-11-a-20"
      ]
    },
    {
      "base": "lettere-maiuscole-tratteggiate",
      "variations": [
        "lettere-tratteggiate-da-g-a-n",
        "lettere-tratteggiate-da-o-a-t",
        "lettere-tratteggiate-da-r-a-z",
        "vocali-tratteggiate",
        "prime-lettere-abcd"
      ]
    },
    {
      "base": "parole-frequenti",
      "variations": [
        "parole-frequenti-serie-2",
        "parole-frequenti-serie-3",
        "parole-frequenti-serie-4",
        "parole-frequenti-serie-5",
        "parole-frequenti-serie-6"
      ]
    },
    {
      "base": "ritaglia-e-incolla",
      "variations": [
        "ritaglia-e-incolla-veicoli",
        "ritaglia-e-incolla-frutta",
        "ritaglia-e-incolla-giocattoli",
        "ritaglia-e-incolla-due-gruppi"
      ]
    },
    {
      "base": "calcola-e-colora",
      "variations": [
        "colora-in-base-alla-forma",
        "colora-con-i-numeri",
        "colora-con-le-sottrazioni",
        "colora-con-addizioni-e-sottrazioni",
        "colora-con-le-somme-fino-a-20"
      ]
    },
    {
      "base": "labirinti-per-bambini",
      "variations": [
        "labirinto-facile-frutta",
        "labirinto-difficile-veicoli",
        "labirinto-gigante-giocattoli",
        "labirinto-degli-animali",
        "labirinto-della-frutta"
      ]
    },
    {
      "base": "amici-del-10",
      "variations": [
        "amici-del-5-con-i-puntini",
        "scomposizioni-fino-a-10",
        "amici-del-20",
        "scomposizioni-trova-il-totale",
        "amici-del-10-con-i-puntini"
      ]
    },
    {
      "base": "calcolo-mentale-fino-a-20",
      "variations": [
        "calcolo-mentale-fino-a-10",
        "numero-mancante-fino-a-20",
        "addizioni-a-mente-fino-a-20",
        "sottrazioni-a-mente-fino-a-20",
        "numero-mancante-fino-a-10"
      ]
    },
    {
      "base": "famiglie-di-operazioni",
      "variations": [
        "famiglie-di-operazioni-fino-a-10",
        "famiglie-di-operazioni-fino-a-20",
        "casette-delle-operazioni-fino-a-10",
        "famiglie-con-il-numero-mancante",
        "famiglie-del-per-e-del-diviso"
      ]
    },
    {
      "base": "numeri-in-lettere",
      "variations": [
        "numeri-in-lettere-fino-a-20",
        "decine-in-lettere-da-10-a-100",
        "collega-numeri-e-parole",
        "numeri-in-lettere-fino-a-50",
        "scrivi-i-numeri-in-lettere"
      ]
    },
    {
      "base": "contare-le-monete",
      "variations": [
        "contare-le-monete-primi-passi",
        "contare-gli-euro-tutte-le-monete",
        "allenamento-con-le-monete",
        "monete-da-1-e-2-centesimi",
        "quale-borsellino-ha-di-piu"
      ]
    },
    {
      "base": "disegna-le-lancette",
      "variations": [
        "disegna-le-lancette-ore-in-punto",
        "disegna-le-lancette-e-mezza",
        "disegna-le-lancette-quarti-di-ora",
        "disegna-le-lancette-di-5-in-5-minuti",
        "disegna-le-lancette-ripasso"
      ]
    },
    {
      "base": "problemi-illustrati",
      "variations": [
        "problemi-di-addizione-illustrati",
        "problemi-di-sottrazione-illustrati",
        "problemi-illustrati-fino-a-10",
        "tre-problemi-illustrati",
        "problemi-illustrati-con-gli-animali"
      ]
    },
    {
      "base": "operazioni-in-colonna-senza-cambio",
      "variations": [
        "addizioni-in-colonna-a-due-cifre",
        "sottrazioni-in-colonna-a-due-cifre",
        "operazioni-in-colonna-a-tre-cifre",
        "addizioni-in-colonna-a-tre-cifre",
        "ripasso-operazioni-in-colonna"
      ]
    },
    {
      "base": "capacita-e-peso",
      "variations": [
        "capacita-in-millilitri",
        "il-peso-in-grammi",
        "misurare-con-precisione-tacche-da-50-ml",
        "capacita-fino-a-2000-ml",
        "capacita-e-peso-con-gli-animali"
      ]
    },
    {
      "base": "simmetria-sui-quadretti",
      "variations": [
        "simmetria-facile-sui-quadretti",
        "simmetria-difficile-sui-quadretti",
        "disegni-a-specchio-cuore-e-farfalla",
        "disegni-a-specchio-casa-e-corona",
        "simmetria-con-la-linea-orizzontale"
      ]
    },
    {
      "base": "comprensione-del-testo",
      "variations": [
        "comprensione-il-riccio-nel-giardino",
        "comprensione-orto-della-scuola",
        "comprensione-una-mattina-di-neve",
        "comprensione-sabato-al-mercato",
        "comprensione-gita-in-montagna"
      ]
    },
    {
      "base": "operazioni-in-colonna-con-il-cambio",
      "variations": [
        "addizioni-con-il-riporto",
        "sottrazioni-con-il-prestito",
        "addizioni-a-tre-cifre",
        "sottrazioni-con-gli-zeri",
        "ripasso-riporto-e-prestito"
      ]
    },
    {
      "base": "tabelline",
      "variations": [
        "tabellina-del-2",
        "tabellina-del-5",
        "tabellina-del-10",
        "tabellina-del-3",
        "tabellina-del-4"
      ]
    }
  ],
  "nl": [
    {
      "base": "schrijfpatronen-oefenen",
      "variations": [
        "schrijfpatronen-zigzaglijnen",
        "schrijfpatronen-golven-en-boogjes",
        "schrijfpatronen-lussen-en-achtjes",
        "moeilijke-schrijfpatronen",
        "schrijfpatronen-herhalen"
      ]
    },
    {
      "base": "cijfers-schrijven-0-tot-9",
      "variations": [
        "cijfers-schrijven-0-tot-4",
        "cijfers-schrijven-5-tot-9",
        "cijfers-natrekken-en-zelf-schrijven",
        "getallen-schrijven-1-tot-10",
        "getallen-schrijven-11-tot-20"
      ]
    },
    {
      "base": "hoofdletters-overtrekken",
      "variations": [
        "letters-overtrekken-g-tot-l",
        "letters-overtrekken-m-tot-r",
        "letters-overtrekken-s-tot-z",
        "letter-ij-schrijven",
        "hoofdletters-a-b-c-d"
      ]
    },
    {
      "base": "flitswoorden-oefenen",
      "variations": [
        "flitswoorden-lijst-2",
        "flitswoorden-lijst-3",
        "flitswoorden-lijst-4",
        "flitswoorden-lijst-5",
        "flitswoorden-lijst-6"
      ]
    },
    {
      "base": "knippen-sorteren-plakken",
      "variations": [
        "knippen-en-plakken-voertuigen",
        "knippen-en-plakken-fruit",
        "knippen-en-plakken-speelgoed",
        "knippen-en-plakken-twee-groepen"
      ]
    },
    {
      "base": "kleuren-op-code",
      "variations": [
        "kleuren-op-vormcode",
        "kleuren-op-nummer",
        "kleuren-met-aftreksommen",
        "kleuren-met-plus-en-minsommen",
        "kleuren-met-sommen-tot-20"
      ]
    },
    {
      "base": "doolhof-werkblad",
      "variations": [
        "makkelijk-doolhof",
        "moeilijk-doolhof",
        "reuzendoolhof",
        "doolhof-dieren",
        "doolhof-fruit"
      ]
    },
    {
      "base": "splitsen-tot-10",
      "variations": [
        "splitsen-van-5-met-stippen",
        "splitsen-van-5-tot-10",
        "splitsen-tot-20",
        "splitsen-geheel-ontbreekt",
        "splitsen-van-10-met-stippen"
      ]
    },
    {
      "base": "hoofdrekenen-tot-20",
      "variations": [
        "hoofdrekenen-tot-10",
        "stipsommen-tot-20",
        "optelsommen-tot-20",
        "aftreksommen-tot-20",
        "stipsommen-tot-10"
      ]
    },
    {
      "base": "rekenhuisjes",
      "variations": [
        "rekenhuisjes-tot-10",
        "rekenhuisjes-tot-20",
        "rekenhuisjes-tot-10-extra-oefenen",
        "rekenhuisjes-met-stipsommen",
        "rekenhuisjes-keer-en-delen"
      ]
    },
    {
      "base": "getallen-in-woorden",
      "variations": [
        "getallen-in-woorden-tot-20",
        "tientallen-in-woorden",
        "getal-en-woord-verbinden",
        "getallen-in-woorden-tot-50",
        "getallen-in-woorden-schrijven"
      ]
    },
    {
      "base": "munten-tellen-euro",
      "variations": [
        "munten-tellen-voor-beginners",
        "alle-euromunten-tellen",
        "geld-tellen-extra-oefenen",
        "tellen-met-centen",
        "welke-portemonnee-heeft-meer-geld"
      ]
    },
    {
      "base": "wijzers-tekenen-klokkijken",
      "variations": [
        "wijzers-tekenen-hele-uren",
        "wijzers-tekenen-halve-uren",
        "wijzers-tekenen-kwartieren",
        "wijzers-tekenen-per-vijf-minuten",
        "wijzers-tekenen-alle-tijden"
      ]
    },
    {
      "base": "verhaaltjessommen-met-plaatjes",
      "variations": [
        "verhaaltjessommen-optellen",
        "verhaaltjessommen-aftrekken",
        "verhaaltjessommen-tot-10",
        "drie-verhaaltjessommen",
        "verhaaltjessommen-met-dieren"
      ]
    },
    {
      "base": "sommen-onder-elkaar",
      "variations": [
        "optellen-onder-elkaar-tot-100",
        "aftrekken-onder-elkaar-tot-100",
        "sommen-onder-elkaar-tot-1000",
        "optellen-onder-elkaar-tot-1000",
        "onder-elkaar-rekenen-herhalen"
      ]
    },
    {
      "base": "maatbekers-en-weegschalen",
      "variations": [
        "maatbekers-aflezen",
        "weegschalen-aflezen-in-grammen",
        "maatbekers-aflezen-kleine-stapjes",
        "maatbekers-tot-2000-ml",
        "maatbekers-en-weegschalen-dieren"
      ]
    },
    {
      "base": "spiegeltekening-afmaken",
      "variations": [
        "makkelijke-spiegeltekeningen",
        "moeilijke-spiegeltekeningen",
        "spiegelen-hart-en-vlinder",
        "spiegelen-huis-en-kroon",
        "spiegelen-onder-de-spiegellijn"
      ]
    },
    {
      "base": "begrijpend-lezen-groep-4",
      "variations": [
        "begrijpend-lezen-de-rode-vlieger",
        "begrijpend-lezen-de-egel",
        "begrijpend-lezen-de-klassenvis",
        "begrijpend-lezen-noor-leert-fietsen",
        "begrijpend-lezen-de-bibliotheekbus"
      ]
    },
    {
      "base": "cijferend-rekenen-met-onthouden",
      "variations": [
        "optellen-met-onthouden",
        "aftrekken-met-lenen",
        "optellen-tot-1000-met-onthouden",
        "lenen-over-de-nul",
        "onthouden-en-lenen-oefenen"
      ]
    },
    {
      "base": "tafels-oefenen",
      "variations": [
        "tafel-van-2",
        "tafel-van-5",
        "tafel-van-10",
        "tafel-van-3",
        "tafel-van-4"
      ]
    }
  ],
  "sv": [
    {
      "base": "skrivovningar-spara-linjer",
      "variations": [
        "spara-raka-linjer-sicksack",
        "vagor-och-bagar",
        "oglor-attor-spiraler",
        "svara-sparlinjer",
        "blandade-sparlinjer"
      ]
    },
    {
      "base": "spara-siffror-0-9",
      "variations": [
        "spara-siffror-0-4",
        "spara-siffror-5-9",
        "spara-och-skriv-siffror",
        "spara-talen-1-10",
        "spara-talen-11-20"
      ]
    },
    {
      "base": "spara-stora-bokstaver",
      "variations": [
        "spara-bokstaver-g-l",
        "spara-bokstaver-m-r",
        "spara-bokstaver-s-z",
        "spara-a-a-o",
        "forsta-bokstaverna-abcd"
      ]
    },
    {
      "base": "ordbilder-las-spara-skriv",
      "variations": [
        "ordbilder-lista-2",
        "ordbilder-lista-3",
        "ordbilder-lista-4",
        "ordbilder-lista-5",
        "ordbilder-lista-6"
      ]
    },
    {
      "base": "klipp-och-klistra-sortering",
      "variations": [
        "klipp-och-klistra-fordon",
        "klipp-och-klistra-frukter",
        "klipp-och-klistra-leksaker",
        "klipp-och-klistra-tva-grupper"
      ]
    },
    {
      "base": "mala-efter-kod",
      "variations": [
        "mala-efter-figurkod",
        "farglagg-efter-siffror",
        "mala-efter-kod-subtraktion",
        "mala-efter-kod-plus-och-minus",
        "mala-efter-kod-summor-till-20"
      ]
    },
    {
      "base": "labyrinter-for-barn",
      "variations": [
        "latt-labyrint-frukter",
        "svar-labyrint-fordon",
        "jattelabyrint-leksaker",
        "labyrint-djur",
        "labyrint-frukter"
      ]
    },
    {
      "base": "tiokompisar",
      "variations": [
        "femkompisar",
        "talkamrater-till-10",
        "tjugokompisar",
        "talkamrater-hela-talet",
        "tiokompisar-med-prickar"
      ]
    },
    {
      "base": "huvudrakning-till-20",
      "variations": [
        "huvudrakning-till-10",
        "oppna-utsagor-till-20",
        "addition-till-20",
        "subtraktion-till-20",
        "oppna-utsagor-till-10"
      ]
    },
    {
      "base": "raknefamiljer",
      "variations": [
        "raknefamiljer-till-10",
        "raknefamiljer-till-20",
        "fler-raknefamiljer-till-10",
        "raknefamiljer-talet-i-mitten",
        "raknefamiljer-multiplikation-division"
      ]
    },
    {
      "base": "tal-med-bokstaver",
      "variations": [
        "tal-med-bokstaver-till-20",
        "hela-tiotal-med-bokstaver",
        "para-ihop-tal-och-ord",
        "tal-med-bokstaver-till-50",
        "skriv-talen-med-bokstaver"
      ]
    },
    {
      "base": "rakna-pengar-kronor",
      "variations": [
        "rakna-mynt-forsta-stegen",
        "rakna-pengar-alla-mynt",
        "trana-rakna-mynt",
        "enkronor-och-tvakronor",
        "vilken-bors-har-mest"
      ]
    },
    {
      "base": "rita-klockans-visare",
      "variations": [
        "rita-visarna-hela-timmar",
        "rita-visarna-halva-timmar",
        "rita-visarna-kvart-i-kvart-over",
        "rita-visarna-fem-minuter",
        "rita-visarna-blandade-tider"
      ]
    },
    {
      "base": "raknehandelser-med-bilder",
      "variations": [
        "raknehandelser-addition",
        "raknehandelser-subtraktion",
        "raknehandelser-till-10",
        "trana-raknehandelser",
        "raknehandelser-med-djur"
      ]
    },
    {
      "base": "uppstallning-utan-vaxling",
      "variations": [
        "addition-utan-vaxling",
        "subtraktion-utan-vaxling",
        "tresiffrig-uppstallning-utan-vaxling",
        "tresiffrig-addition-utan-vaxling",
        "uppstallning-repetition"
      ]
    },
    {
      "base": "volym-och-vikt",
      "variations": [
        "las-av-matkannan",
        "las-av-vagen-i-gram",
        "las-av-skalan-sma-steg",
        "matkannor-till-2000-ml",
        "volym-och-vikt-med-djur"
      ]
    },
    {
      "base": "symmetri-spegelbilder",
      "variations": [
        "latt-symmetri-i-rutnat",
        "svar-symmetri-i-rutnat",
        "spegelbilder-hjarta-och-fjaril",
        "spegelbilder-hus-och-krona",
        "spegla-under-linjen"
      ]
    },
    {
      "base": "lasforstaelse-korta-texter",
      "variations": [
        "lasforstaelse-simskolan",
        "lasforstaelse-bullar-hos-mormor",
        "lasforstaelse-biblioteket",
        "lasforstaelse-snolyktan",
        "lasforstaelse-farjan"
      ]
    },
    {
      "base": "uppstallning-med-vaxling",
      "variations": [
        "addition-med-vaxling",
        "subtraktion-med-vaxling",
        "tresiffrig-addition-med-vaxling",
        "subtraktion-over-noll",
        "blandad-vaxling-uppstallning"
      ]
    },
    {
      "base": "multiplikationstabeller",
      "variations": [
        "2ans-tabell",
        "5ans-tabell",
        "10ans-tabell",
        "3ans-tabell",
        "4ans-tabell"
      ]
    }
  ],
  "da": [
    {
      "base": "skriveforberedende-oevelser",
      "variations": [
        "lige-linjer-og-zigzag",
        "boelger-og-buer",
        "sloejfer-og-spiraler",
        "svaere-skrivemoenstre",
        "blandede-skriveoevelser"
      ]
    },
    {
      "base": "skriv-tallene-0-9",
      "variations": [
        "skriv-tallene-0-4",
        "skriv-tallene-5-9",
        "spor-og-skriv-tallene-selv",
        "skriv-tallene-1-10",
        "skriv-tallene-11-20"
      ]
    },
    {
      "base": "skriv-store-bogstaver",
      "variations": [
        "skriv-bogstaverne-g-til-l",
        "skriv-bogstaverne-m-til-r",
        "skriv-bogstaverne-s-til-z",
        "skriv-ae-oe-aa",
        "mine-foerste-bogstaver-abcd"
      ]
    },
    {
      "base": "hyppige-ord-laes-og-skriv",
      "variations": [
        "hyppige-ord-saet-2",
        "hyppige-ord-saet-3",
        "hyppige-ord-saet-4",
        "hyppige-ord-saet-5",
        "hyppige-ord-saet-6"
      ]
    },
    {
      "base": "klip-og-klistre-sortering",
      "variations": [
        "klip-og-klistre-koeretoejer",
        "klip-og-klistre-frugter",
        "klip-og-klistre-legetoej",
        "klip-og-sorter-i-to-grupper"
      ]
    },
    {
      "base": "regn-og-farvelaeg",
      "variations": [
        "farvelaeg-efter-figurkode",
        "farvelaeg-efter-tal",
        "farvelaeg-med-minusstykker",
        "farvelaeg-med-plus-og-minus",
        "farvelaeg-med-plus-til-20"
      ]
    },
    {
      "base": "labyrint-opgaveark",
      "variations": [
        "nem-labyrint-frugter",
        "svaer-labyrint-koeretoejer",
        "kaempelabyrint-legetoej",
        "labyrint-med-dyr",
        "labyrint-med-frugter"
      ]
    },
    {
      "base": "tiervenner-opgaveark",
      "variations": [
        "femvenner-med-taelleprikker",
        "talvenner-op-til-10",
        "tyvevenner-par-der-giver-20",
        "find-det-hele-tal",
        "tiervenner-med-taelleprikker"
      ]
    },
    {
      "base": "hovedregning-op-til-20",
      "variations": [
        "hovedregning-op-til-10",
        "manglende-tal-til-20",
        "plusstykker-op-til-20",
        "minusstykker-op-til-20",
        "manglende-tal-til-10"
      ]
    },
    {
      "base": "talfamilier-opgaveark",
      "variations": [
        "talfamilier-op-til-10",
        "talfamilier-op-til-20",
        "oev-talfamilier-op-til-10",
        "talfamilier-det-midterste-tal",
        "talfamilier-gange-og-division"
      ]
    },
    {
      "base": "tal-og-talord",
      "variations": [
        "talord-op-til-20",
        "talord-hele-tiere-til-100",
        "forbind-tal-og-talord",
        "talord-op-til-50",
        "skriv-talordene"
      ]
    },
    {
      "base": "taelle-moenter-kroner",
      "variations": [
        "taelle-moenter-nem-start",
        "taelle-moenter-alle-moenter",
        "oev-dig-i-at-taelle-penge",
        "taelle-med-de-smaa-moenter",
        "hvilken-pung-har-flest-penge"
      ]
    },
    {
      "base": "tegn-viserne-paa-uret",
      "variations": [
        "tegn-viserne-hele-timer",
        "tegn-viserne-halve-timer",
        "tegn-viserne-kvart-over-og-kvart-i",
        "tegn-viserne-fem-minutter",
        "tegn-viserne-blandede-klokkeslaet"
      ]
    },
    {
      "base": "regnehistorier-med-billeder",
      "variations": [
        "regnehistorier-med-plus",
        "regnehistorier-med-minus",
        "regnehistorier-op-til-10",
        "tre-regnehistorier-paa-en-side",
        "regnehistorier-med-dyr"
      ]
    },
    {
      "base": "plus-og-minus-med-opstilling",
      "variations": [
        "plus-med-tocifrede-tal",
        "minus-med-tocifrede-tal",
        "trecifrede-tal-i-opstilling",
        "plus-med-trecifrede-tal",
        "repetition-opstilling-uden-tierovergang"
      ]
    },
    {
      "base": "maalebaegre-og-vaegte",
      "variations": [
        "aflaes-maalebaegre-i-milliliter",
        "aflaes-vaegte-i-gram",
        "aflaes-skalaer-med-smaa-spring",
        "maalebaegre-op-til-2000-ml",
        "maalebaegre-og-vaegte-med-dyr"
      ]
    },
    {
      "base": "tegn-spejlbilledet",
      "variations": [
        "nem-symmetritegning",
        "svaer-symmetritegning",
        "spejlbilleder-hjerte-og-sommerfugl",
        "spejlbilleder-hus-og-krone",
        "spejling-under-stregen"
      ]
    },
    {
      "base": "laeseforstaaelse-opgaveark",
      "variations": [
        "laeseforstaaelse-elias-paa-stranden",
        "laeseforstaaelse-paa-biblioteket",
        "laeseforstaaelse-kaelkedag",
        "laeseforstaaelse-hos-bageren",
        "laeseforstaaelse-skovturen"
      ]
    },
    {
      "base": "opstilling-med-tierovergang",
      "variations": [
        "plus-med-tierovergang",
        "minus-med-tierovergang",
        "trecifret-plus-med-tierovergang",
        "minus-hen-over-nul",
        "repetition-med-tierovergang"
      ]
    },
    {
      "base": "den-lille-tabel",
      "variations": [
        "2-tabellen",
        "5-tabellen",
        "10-tabellen",
        "3-tabellen",
        "4-tabellen"
      ]
    }
  ],
  "no": [
    {
      "base": "skriveforberedende-ovelser",
      "variations": [
        "blyantloyper-rette-linjer-og-sikksakk",
        "blyantloyper-bolger-og-buer",
        "lokker-attetall-og-spiraler",
        "vanskelige-blyantloyper",
        "blyantloyper-repetisjon"
      ]
    },
    {
      "base": "spore-tall-0-til-9",
      "variations": [
        "spore-tallene-0-til-4",
        "spore-tallene-5-til-9",
        "spor-og-skriv-tallene",
        "spore-tallene-1-til-10",
        "spore-tallene-11-til-20"
      ]
    },
    {
      "base": "spore-store-bokstaver",
      "variations": [
        "spore-bokstavene-g-til-l",
        "spore-bokstavene-m-til-r",
        "spore-bokstavene-s-til-z",
        "spore-bokstavene-ae-o-a",
        "mine-forste-store-bokstaver"
      ]
    },
    {
      "base": "hoyfrekvente-ord",
      "variations": [
        "hoyfrekvente-ord-sett-2",
        "hoyfrekvente-ord-sett-3",
        "hoyfrekvente-ord-sett-4",
        "hoyfrekvente-ord-sett-5",
        "hoyfrekvente-ord-sett-6"
      ]
    },
    {
      "base": "klipp-og-lim-sortering",
      "variations": [
        "klipp-og-lim-kjoretoy",
        "klipp-og-lim-frukter",
        "klipp-og-lim-leker",
        "klipp-og-lim-to-grupper"
      ]
    },
    {
      "base": "regn-og-fargelegg",
      "variations": [
        "fargelegg-etter-figurkode",
        "fargelegg-etter-tall",
        "trekk-fra-og-fargelegg",
        "fargelegg-pluss-og-minus",
        "fargelegg-addisjon-til-20"
      ]
    },
    {
      "base": "labyrinter-for-barn",
      "variations": [
        "enkel-labyrint",
        "vanskelig-labyrint",
        "kjempelabyrint",
        "labyrint-med-dyr",
        "labyrint-med-frukter"
      ]
    },
    {
      "base": "tiervenner",
      "variations": [
        "femmervenner",
        "tallvenner-opp-til-10",
        "tallvenner-til-20",
        "tallvenner-finn-det-hele",
        "tiervenner-med-telleprikker"
      ]
    },
    {
      "base": "hoderegning-til-20",
      "variations": [
        "hoderegning-til-10",
        "finn-tallet-som-mangler-til-20",
        "hoderegning-addisjon-til-20",
        "hoderegning-subtraksjon-til-20",
        "finn-tallet-som-mangler-til-10"
      ]
    },
    {
      "base": "regnefamilier",
      "variations": [
        "regnefamilier-til-10",
        "regnefamilier-til-20",
        "regnehus-til-10",
        "regnefamilier-tallet-i-midten",
        "gange-og-delefamilier"
      ]
    },
    {
      "base": "tallord",
      "variations": [
        "tallord-til-20",
        "tallord-tiere-til-100",
        "koble-tall-og-tallord",
        "tallord-til-50",
        "skrive-tallord"
      ]
    },
    {
      "base": "regne-med-penger",
      "variations": [
        "telle-mynter-for-nybegynnere",
        "telle-alle-myntene",
        "ove-pa-a-telle-mynter",
        "telle-enkroner-og-femkroner",
        "hvilken-pung-har-mest-penger"
      ]
    },
    {
      "base": "laere-klokka",
      "variations": [
        "tegne-viserne-hele-timer",
        "tegne-viserne-halv-time",
        "tegne-viserne-kvart-over-og-kvart-pa",
        "tegne-viserne-fem-minutter",
        "tegne-viserne-blandede-klokkeslett"
      ]
    },
    {
      "base": "regnefortellinger",
      "variations": [
        "regnefortellinger-addisjon",
        "regnefortellinger-subtraksjon",
        "regnefortellinger-til-10",
        "tre-regnefortellinger",
        "regnefortellinger-med-dyr"
      ]
    },
    {
      "base": "oppstilt-addisjon-og-subtraksjon",
      "variations": [
        "oppstilt-addisjon-tosifret",
        "oppstilt-subtraksjon-tosifret",
        "tresifret-oppstilling-blandet",
        "tresifret-oppstilt-addisjon",
        "oppstilling-blandet-repetisjon"
      ]
    },
    {
      "base": "male-liter-og-gram",
      "variations": [
        "lese-av-litermal",
        "lese-av-skalvekt-i-gram",
        "lese-skala-med-sma-steg",
        "litermal-til-2000-ml",
        "male-liter-og-gram-med-dyr"
      ]
    },
    {
      "base": "symmetri-oppgaver",
      "variations": [
        "enkel-symmetri",
        "vanskelig-symmetri",
        "speilbilder-hjerte-og-sommerfugl",
        "speilbilder-hus-og-krone",
        "speiling-under-streken"
      ]
    },
    {
      "base": "leseforstaelse",
      "variations": [
        "leseforstaelse-mia-mater-fuglene",
        "leseforstaelse-akedag-i-bakken",
        "leseforstaelse-jakob-baker-boller",
        "leseforstaelse-pa-biblioteket",
        "leseforstaelse-fisketur-ved-fjellvannet"
      ]
    },
    {
      "base": "regning-med-tierovergang",
      "variations": [
        "addisjon-med-tierovergang",
        "subtraksjon-med-veksling",
        "tresifret-addisjon-med-tierovergang",
        "subtraksjon-med-veksling-over-null",
        "tierovergang-blandet-oving"
      ]
    },
    {
      "base": "gangetabellen",
      "variations": [
        "2-gangen",
        "5-gangen",
        "10-gangen",
        "3-gangen",
        "4-gangen"
      ]
    }
  ],
  "fi": [
    {
      "base": "kynaharjoitukset",
      "variations": [
        "kynaharjoitukset-siksakit-ja-sakarat",
        "kynaharjoitukset-aallot-ja-kaaret",
        "kynaharjoitukset-silmukat-ja-spiraalit",
        "vaativat-kynaharjoitukset",
        "kynaharjoitusten-kertaus"
      ]
    },
    {
      "base": "numeroiden-kirjoitusharjoitus-0-9",
      "variations": [
        "numeroiden-kirjoitusharjoitus-0-4",
        "numeroiden-kirjoitusharjoitus-5-9",
        "jaljenna-ja-kirjoita-numerot",
        "lukujen-kirjoitusharjoitus-1-10",
        "lukujen-kirjoitusharjoitus-11-20"
      ]
    },
    {
      "base": "isojen-kirjainten-jaljentaminen",
      "variations": [
        "kirjainten-kirjoitusharjoitus-g-l",
        "kirjainten-kirjoitusharjoitus-m-r",
        "kirjainten-kirjoitusharjoitus-s-o",
        "aakkoset-a-ja-o",
        "ensimmaiset-kirjaimet-a-b-c-d"
      ]
    },
    {
      "base": "yleisten-sanojen-harjoittelu",
      "variations": [
        "yleiset-sanat-sarja-2",
        "yleiset-sanat-sarja-3",
        "yleiset-sanat-sarja-4",
        "yleiset-sanat-sarja-5",
        "yleiset-sanat-sarja-6"
      ]
    },
    {
      "base": "leikkaa-lajittele-ja-liimaa",
      "variations": [
        "leikkaa-lajittele-ja-liimaa-ajoneuvot",
        "leikkaa-lajittele-ja-liimaa-hedelmat",
        "leikkaa-lajittele-ja-liimaa-lelut",
        "leikkaa-ja-liimaa-kahteen-ryhmaan"
      ]
    },
    {
      "base": "varita-koodin-mukaan",
      "variations": [
        "varita-muotokoodin-mukaan",
        "varita-numeroiden-mukaan",
        "vahenna-ja-varita",
        "laske-ja-varita-plus-ja-miinus",
        "varita-summien-mukaan-11-20"
      ]
    },
    {
      "base": "labyrintti-tehtavat",
      "variations": [
        "helppo-labyrintti",
        "vaikea-labyrintti",
        "jattilabyrintti",
        "labyrintti-elaimet",
        "labyrintti-hedelmat"
      ]
    },
    {
      "base": "kymppiparit",
      "variations": [
        "viisparit-hajotelmat-viiteen",
        "lukujen-hajotelmat-5-10",
        "kaksikymppiparit-hajotelmat-20",
        "hajotelmat-puuttuva-kokonaisuus",
        "kymppiparit-pisteiden-avulla"
      ]
    },
    {
      "base": "paassalaskut-0-20",
      "variations": [
        "paassalaskut-0-10",
        "puuttuvan-luvun-laskut-0-20",
        "yhteenlaskut-0-20-paassa",
        "vahennyslaskut-0-20-paassa",
        "puuttuvan-luvun-laskut-0-10"
      ]
    },
    {
      "base": "laskuperheet",
      "variations": [
        "laskuperheet-0-10",
        "laskuperheet-0-20",
        "laskuperhetalot-harjoitus-0-10",
        "laskuperheet-puuttuva-luku",
        "kerto-ja-jakolaskuperheet"
      ]
    },
    {
      "base": "lukusanat-tehtavat",
      "variations": [
        "lukusanat-0-20",
        "lukusanat-tasakymmenet",
        "yhdista-luku-ja-lukusana",
        "lukusanat-0-50",
        "kirjoita-lukusanat"
      ]
    },
    {
      "base": "rahalaskut-eurot-ja-sentit",
      "variations": [
        "rahalaskujen-ensiaskeleet",
        "rahalaskut-kaikki-kolikot",
        "kolikkolaskujen-harjoitus",
        "rahalaskut-5-ja-10-sentin-kolikot",
        "kummassa-kukkarossa-on-enemman"
      ]
    },
    {
      "base": "piirra-kellon-viisarit",
      "variations": [
        "piirra-viisarit-tasatunnit",
        "piirra-viisarit-puolitunnit",
        "piirra-viisarit-vartit",
        "piirra-viisarit-viiden-minuutin-tarkkuus",
        "piirra-viisarit-kellonaikojen-kertaus"
      ]
    },
    {
      "base": "sanalliset-tehtavat",
      "variations": [
        "sanalliset-yhteenlaskutehtavat",
        "sanalliset-vahennyslaskutehtavat",
        "sanalliset-tehtavat-0-10",
        "sanallisten-tehtavien-harjoitus",
        "sanalliset-tehtavat-elaimet"
      ]
    },
    {
      "base": "allekkain-laskeminen-ilman-kymmenylitysta",
      "variations": [
        "yhteenlasku-allekkain-2-numeroiset",
        "vahennyslasku-allekkain-2-numeroiset",
        "allekkain-laskeminen-3-numeroiset",
        "yhteenlasku-allekkain-3-numeroiset",
        "allekkain-laskemisen-kertaus"
      ]
    },
    {
      "base": "tilavuus-ja-massa-tehtavat",
      "variations": [
        "lue-mitta-astian-millilitrat",
        "lue-vaaka-grammat",
        "mitta-asteikot-50-ml-valein",
        "isot-mitta-astiat-2000-ml",
        "tilavuus-ja-massa-elaimet"
      ]
    },
    {
      "base": "taydenna-peilikuva",
      "variations": [
        "helpot-peilikuvat",
        "vaikeat-peilikuvat",
        "peilikuvat-sydan-ja-perhonen",
        "peilikuvat-talo-ja-kruunu",
        "peilikuva-vaakaviivan-alle"
      ]
    },
    {
      "base": "luetun-ymmartaminen",
      "variations": [
        "luetun-ymmartaminen-ensilumi",
        "luetun-ymmartaminen-kirjastoauto",
        "luetun-ymmartaminen-uimahallissa",
        "luetun-ymmartaminen-maatilan-retki",
        "luetun-ymmartaminen-yo-mokilla"
      ]
    },
    {
      "base": "allekkain-laskeminen-kymmenylityksella",
      "variations": [
        "yhteenlasku-allekkain-muistinumerolla",
        "vahennyslasku-allekkain-lainaamalla",
        "3-numeroinen-yhteenlasku-allekkain",
        "vahennyslasku-nollien-yli",
        "kymmenylityksen-kertaus"
      ]
    },
    {
      "base": "kertotauluharjoitukset",
      "variations": [
        "2n-kertotaulu",
        "5n-kertotaulu",
        "10n-kertotaulu",
        "3n-kertotaulu",
        "4n-kertotaulu"
      ]
    }
  ]
};
