/**
 * The two card strips on the /worksheets hub page 1. GENERATED by
 * scripts/seo-landing/gen-var-highlights.js from the landing corpora — re-run
 * it after landing content changes; missing slugs are omitted at render, so
 * trimming is always safe.
 *
 * NEW_WORKSHEET_GROUPS — the 21 nt20/lowercase family cards, each with its
 * variation landing slugs (chips).
 * MORE_TYPE_GROUPS — the 7 older families whose buckets are far too small to
 * reach page 1 through the size-ordered variety grid (arrays-multiplication,
 * fractions, geometry, graphing-data, number-charts, measurement,
 * telling-time), each card carrying that family's other grade bands as chips.
 */
export interface NewWorksheetGroup { base: string; variations: string[] }
export const NEW_WORKSHEET_GROUPS: Record<string, NewWorksheetGroup[]> = {
  "en": [
    {
      "base": "pre-writing-tracing-lines",
      "variations": [
        "tracing-zigzag-lines",
        "tracing-wavy-lines",
        "tracing-loops-and-spirals",
        "advanced-pre-writing-practice",
        "pre-writing-review"
      ]
    },
    {
      "base": "number-tracing-0-9",
      "variations": [
        "number-tracing-0-4",
        "number-tracing-5-9",
        "trace-and-write-numbers-0-9",
        "number-tracing-1-10",
        "teen-number-tracing-11-20"
      ]
    },
    {
      "base": "capital-letter-tracing",
      "variations": [
        "letter-tracing-g-to-l",
        "letter-tracing-m-to-r",
        "letter-tracing-s-to-z",
        "vowel-tracing-a-e-i-o-u",
        "big-letter-tracing-abcd"
      ]
    },
    {
      "base": "sight-words-read-trace-write",
      "variations": [
        "sight-words-set-2",
        "sight-words-set-3",
        "sight-words-set-4",
        "sight-words-set-5",
        "sight-words-set-6"
      ]
    },
    {
      "base": "cut-and-paste-sorting",
      "variations": [
        "cut-and-paste-vehicles",
        "cut-and-paste-fruits",
        "cut-and-paste-toys",
        "cut-and-paste-two-groups"
      ]
    },
    {
      "base": "color-by-code",
      "variations": [
        "color-by-shape-code",
        "color-by-number-1-6",
        "subtraction-color-by-code",
        "add-and-subtract-color-by-code",
        "color-by-code-sums-to-20"
      ]
    },
    {
      "base": "maze-worksheet",
      "variations": [
        "easy-maze",
        "hard-maze",
        "giant-maze",
        "animal-maze",
        "fruit-maze"
      ]
    },
    {
      "base": "number-bonds-to-10",
      "variations": [
        "number-bonds-to-5",
        "number-bonds-within-10",
        "number-bonds-to-20",
        "number-bonds-missing-whole",
        "make-ten-number-bonds"
      ]
    },
    {
      "base": "mental-math-within-20",
      "variations": [
        "mental-math-within-10",
        "missing-number-equations-to-20",
        "addition-facts-to-20",
        "subtraction-facts-to-20",
        "missing-number-equations-to-10"
      ]
    },
    {
      "base": "fact-families",
      "variations": [
        "fact-families-to-10",
        "fact-family-houses-to-20",
        "fact-house-practice-to-10",
        "fact-families-missing-partner",
        "multiplication-and-division-fact-families"
      ]
    },
    {
      "base": "number-words",
      "variations": [
        "number-words-to-20",
        "tens-in-words-to-100",
        "match-numbers-to-number-words",
        "number-words-to-50",
        "write-the-number-words"
      ]
    },
    {
      "base": "counting-coins",
      "variations": [
        "counting-coins-first-steps",
        "counting-money-all-coins",
        "coin-counting-practice",
        "counting-pennies-and-nickels",
        "which-purse-has-more-money"
      ]
    },
    {
      "base": "draw-the-clock-hands",
      "variations": [
        "draw-clock-hands-to-the-hour",
        "draw-clock-hands-half-past",
        "draw-clock-hands-quarter-hours",
        "draw-clock-hands-to-five-minutes",
        "draw-clock-hands-mixed-times"
      ]
    },
    {
      "base": "word-problems-with-pictures",
      "variations": [
        "addition-word-problems-with-pictures",
        "subtraction-word-problems-with-pictures",
        "word-problems-within-10",
        "word-problem-practice-three-stories",
        "animal-word-problems-with-pictures"
      ]
    },
    {
      "base": "column-addition-and-subtraction",
      "variations": [
        "2-digit-column-addition",
        "2-digit-column-subtraction",
        "3-digit-column-addition-and-subtraction",
        "3-digit-column-addition",
        "column-method-review"
      ]
    },
    {
      "base": "capacity-and-mass-metric",
      "variations": [
        "reading-measuring-jugs",
        "balance-scales-in-grams",
        "reading-scales-in-50-ml-steps",
        "measuring-jugs-to-2000-ml",
        "capacity-and-mass-with-animals"
      ]
    },
    {
      "base": "symmetry-drawing",
      "variations": [
        "easy-symmetry-drawing",
        "hard-symmetry-drawing",
        "mirror-pictures-heart-and-butterfly",
        "mirror-pictures-house-and-crown",
        "symmetry-mirror-below-the-line"
      ]
    },
    {
      "base": "reading-comprehension",
      "variations": [
        "red-kite-reading-comprehension",
        "lost-boot-reading-comprehension",
        "little-garden-reading-comprehension",
        "rainy-school-day-reading-comprehension",
        "birthday-surprise-reading-comprehension"
      ]
    },
    {
      "base": "regrouping-addition-and-subtraction",
      "variations": [
        "2-digit-addition-with-regrouping",
        "2-digit-subtraction-with-regrouping",
        "3-digit-addition-with-regrouping",
        "subtracting-across-zeros",
        "mixed-regrouping-review"
      ]
    },
    {
      "base": "times-tables-practice",
      "variations": [
        "times-table-of-2",
        "times-table-of-5",
        "times-table-of-10",
        "times-table-of-3",
        "times-table-of-4"
      ]
    },
    {
      "base": "lowercase-letter-tracing",
      "variations": [
        "lowercase-letter-tracing-g-to-l",
        "lowercase-letter-tracing-m-to-r",
        "lowercase-letter-tracing-s-to-z",
        "lowercase-vowel-tracing",
        "first-small-letters-tracing"
      ]
    },
    {
      "base": "trace-and-write-words-kindergarten",
      "variations": [
        "trace-and-write-first-words-fruits",
        "trace-once-write-it-twice",
        "trace-long-words-kindergarten"
      ]
    },
    {
      "base": "dot-to-dot-1-20",
      "variations": [
        "dot-to-dot-1-10",
        "dot-to-dot-11-20",
        "dot-to-dot-count-on-11-to-30"
      ]
    },
    {
      "base": "copy-the-grid-picture",
      "variations": [
        "copy-the-grid-picture-6x6",
        "grid-copy-with-letters-and-numbers",
        "copy-the-grid-picture-8x8"
      ]
    },
    {
      "base": "singular-and-plural-kindergarten",
      "variations": [
        "singular-and-plural-first-words",
        "singular-and-plural-longer-words"
      ]
    },
    {
      "base": "a-or-an-worksheet",
      "variations": [
        "a-or-an-four-picture-cards",
        "a-or-an-eight-picture-cards"
      ]
    },
    {
      "base": "read-and-color-1st-grade",
      "variations": [
        "read-and-color-four-sentences",
        "read-and-color-six-colors"
      ]
    },
    {
      "base": "number-of-the-day-1st-grade",
      "variations": [
        "number-of-the-day-teen-numbers",
        "number-of-the-day-ten-more-ten-less",
        "number-of-the-day-to-99"
      ]
    },
    {
      "base": "write-the-word-picture-spelling",
      "variations": [
        "write-the-word-first-letter-given",
        "write-the-word-with-a-word-bank",
        "write-the-word-no-word-bank"
      ]
    },
    {
      "base": "abc-order-1st-grade",
      "variations": [
        "abc-order-four-words",
        "abc-order-number-then-write",
        "abc-order-same-first-letter"
      ]
    },
    {
      "base": "number-walls-addition-pyramids",
      "variations": [
        "number-walls-to-10",
        "number-walls-four-rows",
        "number-walls-missing-brick"
      ]
    },
    {
      "base": "doubles-and-halves-1st-grade",
      "variations": [
        "doubles-and-halves-with-pictures",
        "doubles-and-halves-to-20"
      ]
    },
    {
      "base": "missing-numbers-on-a-number-line",
      "variations": [
        "number-line-to-10",
        "number-line-to-20-fewer-labels",
        "number-line-to-30"
      ]
    },
    {
      "base": "unscramble-the-sentence-1st-grade",
      "variations": []
    },
    {
      "base": "capital-letters-and-punctuation-fix-the-sentence",
      "variations": []
    },
    {
      "base": "nouns-verbs-adjectives-sort",
      "variations": []
    },
    {
      "base": "shopping-math-money-word-problems",
      "variations": []
    },
    {
      "base": "reading-a-calendar-2nd-grade",
      "variations": []
    },
    {
      "base": "picture-writing-prompt-2nd-grade",
      "variations": []
    },
    {
      "base": "grid-coordinates-color-the-squares",
      "variations": []
    },
    {
      "base": "multiplication-and-division-word-problems-3rd-grade",
      "variations": []
    }
  ],
  "de": [
    {
      "base": "schwunguebungen-vorschule",
      "variations": [
        "schwunguebungen-zacken-und-zickzack",
        "schwunguebungen-wellen-und-boegen",
        "schwunguebungen-schleifen-und-spiralen",
        "schwunguebungen-fuer-profis",
        "schwunguebungen-wiederholung"
      ]
    },
    {
      "base": "zahlen-schreiben-lernen",
      "variations": [
        "ziffern-schreiben-0-bis-4",
        "ziffern-schreiben-5-bis-9",
        "zahlen-nachspuren-und-schreiben",
        "zahlen-schreiben-1-bis-10",
        "zahlen-schreiben-11-bis-20"
      ]
    },
    {
      "base": "buchstaben-nachspuren",
      "variations": [
        "buchstaben-nachspuren-g-bis-l",
        "buchstaben-nachspuren-m-bis-r",
        "buchstaben-nachspuren-s-bis-z",
        "umlaute-nachspuren",
        "erste-buchstaben-abcd"
      ]
    },
    {
      "base": "lernwoerter-ueben",
      "variations": [
        "lernwoerter-liste-2",
        "lernwoerter-liste-3",
        "lernwoerter-liste-4",
        "lernwoerter-liste-5",
        "lernwoerter-liste-6"
      ]
    },
    {
      "base": "ausschneiden-und-aufkleben",
      "variations": [
        "ausschneiden-und-aufkleben-fahrzeuge",
        "ausschneiden-und-aufkleben-obst",
        "ausschneiden-und-aufkleben-spielzeug",
        "ausschneiden-und-sortieren-zwei-gruppen"
      ]
    },
    {
      "base": "rechnen-und-ausmalen",
      "variations": [
        "formen-nach-farbcode-ausmalen",
        "malen-nach-zahlen",
        "minus-rechnen-und-ausmalen",
        "plus-und-minus-ausmalen",
        "plusaufgaben-bis-20-ausmalen"
      ]
    },
    {
      "base": "labyrinth-arbeitsblaetter",
      "variations": [
        "leichtes-labyrinth",
        "schweres-labyrinth",
        "riesenlabyrinth",
        "labyrinth-tiere",
        "labyrinth-obst"
      ]
    },
    {
      "base": "zahlzerlegung-bis-10",
      "variations": [
        "zahlzerlegung-bis-5",
        "zahlen-bis-10-zerlegen",
        "zahlzerlegung-bis-20",
        "zahlzerlegung-das-ganze-fehlt",
        "verliebte-zahlen-zehnerfreunde"
      ]
    },
    {
      "base": "kopfrechnen-bis-20",
      "variations": [
        "kopfrechnen-bis-10",
        "platzhalteraufgaben-bis-20",
        "plusaufgaben-bis-20",
        "minusaufgaben-bis-20",
        "platzhalteraufgaben-bis-10"
      ]
    },
    {
      "base": "aufgabenfamilien",
      "variations": [
        "aufgabenfamilien-bis-10",
        "rechenhaeuser-bis-20",
        "rechenhaeuser-bis-10",
        "aufgabenfamilien-fehlende-mittelzahl",
        "aufgabenfamilien-mal-und-geteilt"
      ]
    },
    {
      "base": "zahlwoerter-lesen",
      "variations": [
        "zahlwoerter-bis-20",
        "zahlwoerter-zehner-bis-100",
        "zahlen-und-zahlwoerter-verbinden",
        "zahlwoerter-bis-50",
        "zahlwoerter-schreiben"
      ]
    },
    {
      "base": "rechnen-mit-geld",
      "variations": [
        "muenzen-zaehlen-erste-schritte",
        "geld-zaehlen-alle-muenzen",
        "muenzen-zaehlen-uebungsblatt",
        "zaehlen-mit-1-und-2-cent",
        "welcher-geldbeutel-hat-mehr"
      ]
    },
    {
      "base": "uhrzeiger-einzeichnen",
      "variations": [
        "uhrzeiger-einzeichnen-volle-stunden",
        "uhrzeiger-einzeichnen-halbe-stunden",
        "uhrzeiger-einzeichnen-viertelstunden",
        "uhrzeiger-einzeichnen-fuenf-minuten-schritte",
        "uhrzeiger-einzeichnen-gemischt"
      ]
    },
    {
      "base": "rechengeschichten-mit-bildern",
      "variations": [
        "rechengeschichten-plusaufgaben",
        "rechengeschichten-minusaufgaben",
        "rechengeschichten-bis-10",
        "drei-rechengeschichten",
        "rechengeschichten-mit-tieren"
      ]
    },
    {
      "base": "schriftlich-rechnen-ohne-uebertrag",
      "variations": [
        "schriftliche-addition-ohne-uebertrag",
        "schriftliche-subtraktion-ohne-uebertrag",
        "schriftlich-rechnen-dreistellig-gemischt",
        "dreistellige-zahlen-addieren",
        "schriftlich-rechnen-uebungsmix"
      ]
    },
    {
      "base": "milliliter-und-gramm",
      "variations": [
        "messbecher-ablesen-milliliter",
        "waagen-ablesen-gramm",
        "skalen-ablesen-50-ml-schritte",
        "messbecher-bis-2000-ml",
        "messbecher-und-waagen-tiere"
      ]
    },
    {
      "base": "symmetrie-spiegeln",
      "variations": [
        "leichte-spiegelbilder",
        "schwere-spiegelbilder",
        "spiegelbilder-herz-und-schmetterling",
        "spiegelbilder-haus-und-krone",
        "spiegeln-an-der-waagerechten-achse"
      ]
    },
    {
      "base": "lesetext-mit-fragen",
      "variations": [
        "lesetext-der-kleine-igel",
        "lesetext-bei-der-feuerwehr",
        "lesetext-ein-tag-am-meer",
        "lesetext-der-turnbeutel",
        "lesetext-der-schneetag"
      ]
    },
    {
      "base": "schriftlich-rechnen-mit-uebertrag",
      "variations": [
        "schriftliche-addition-mit-uebertrag",
        "schriftliche-subtraktion-mit-uebertrag",
        "schriftliche-addition-dreistellig",
        "subtrahieren-mit-nullen",
        "schriftlich-rechnen-gemischt"
      ]
    },
    {
      "base": "einmaleins-ueben",
      "variations": [
        "2er-einmaleins",
        "5er-einmaleins",
        "10er-einmaleins",
        "3er-einmaleins",
        "4er-einmaleins"
      ]
    },
    {
      "base": "kleinbuchstaben-nachspuren",
      "variations": [
        "kleinbuchstaben-nachspuren-g-bis-l",
        "kleinbuchstaben-nachspuren-m-bis-r",
        "kleinbuchstaben-nachspuren-s-bis-z",
        "umlaute-und-ss-nachspuren",
        "erste-kleinbuchstaben"
      ]
    },
    {
      "base": "woerter-nachspuren-tiere-vorschule",
      "variations": [
        "woerter-nachspuren-kurze-woerter-fruechte",
        "woerter-nachspuren-zweimal-selbst-schreiben-fahrzeuge",
        "woerter-nachspuren-lange-woerter-spielzeug"
      ]
    },
    {
      "base": "von-punkt-zu-punkt-bis-20",
      "variations": [
        "von-punkt-zu-punkt-bis-10",
        "von-punkt-zu-punkt-11-bis-20",
        "von-punkt-zu-punkt-11-bis-30"
      ]
    },
    {
      "base": "gitterbilder-abzeichnen-vorschule",
      "variations": [
        "gitterbilder-abzeichnen-6x6",
        "gitterbilder-mit-buchstabe-und-zahl",
        "gitterbilder-abzeichnen-8x8"
      ]
    },
    {
      "base": "einzahl-mehrzahl-fruechte-vorschule",
      "variations": [
        "einzahl-und-mehrzahl-kurze-woerter-tiere",
        "einzahl-und-mehrzahl-lange-woerter-fahrzeuge"
      ]
    },
    {
      "base": "der-die-das-tiere-vorschule",
      "variations": [
        "der-die-das-vier-bilder-tiere",
        "der-die-das-acht-bilder-fahrzeuge"
      ]
    },
    {
      "base": "lese-mal-blatt-fruechte-1-klasse",
      "variations": [
        "lese-mal-blatt-vier-saetze-tiere",
        "lese-mal-blatt-sechs-saetze-spielzeug"
      ]
    },
    {
      "base": "zahl-des-tages-1-klasse",
      "variations": [
        "zahl-des-tages-11-bis-19",
        "zahl-des-tages-zehn-mehr-zehn-weniger",
        "zahl-des-tages-bis-99"
      ]
    },
    {
      "base": "bilder-beschriften-fruechte-1-klasse",
      "variations": [
        "bilder-beschriften-erster-buchstabe-tiere",
        "bilder-beschriften-mit-wortspeicher-fahrzeuge",
        "bilder-beschriften-ohne-wortspeicher-spielzeug"
      ]
    },
    {
      "base": "alphabetisch-ordnen-tiere-1-klasse",
      "variations": [
        "alphabetisch-ordnen-nummerieren-fruechte",
        "alphabetisch-ordnen-und-abschreiben-fahrzeuge",
        "alphabetisch-ordnen-zweiter-buchstabe-spielzeug"
      ]
    },
    {
      "base": "zahlenmauern-bis-20-1-klasse",
      "variations": [
        "zahlenmauern-bis-10",
        "zahlenmauern-mit-vier-reihen",
        "zahlenmauern-fehlender-grundstein"
      ]
    },
    {
      "base": "verdoppeln-und-halbieren-1-klasse",
      "variations": [
        "verdoppeln-und-halbieren-mit-bildern-tiere",
        "verdoppeln-und-halbieren-bis-20"
      ]
    },
    {
      "base": "zahlenstrahl-ablesen-bis-20",
      "variations": [
        "zahlenstrahl-ablesen-bis-10",
        "zahlenstrahl-bis-20-wenige-zahlen",
        "zahlenstrahl-ablesen-bis-30"
      ]
    },
    {
      "base": "schuettelsaetze-tiere-1-klasse",
      "variations": []
    },
    {
      "base": "satzanfang-und-satzzeichen-2-klasse",
      "variations": []
    },
    {
      "base": "wortarten-nomen-verben-adjektive-2-klasse",
      "variations": []
    },
    {
      "base": "einkaufen-und-bezahlen-2-klasse",
      "variations": []
    },
    {
      "base": "kalender-lesen-2-klasse",
      "variations": []
    },
    {
      "base": "schreiben-zum-bild-fahrzeuge-2-klasse",
      "variations": []
    },
    {
      "base": "koordinaten-im-gitter-2-klasse",
      "variations": []
    },
    {
      "base": "sachaufgaben-malnehmen-und-teilen-3-klasse",
      "variations": []
    }
  ],
  "es": [
    {
      "base": "grafomotricidad-trazos",
      "variations": [
        "grafomotricidad-rectas-y-zigzag",
        "grafomotricidad-ondas-y-curvas",
        "bucles-espirales-y-ochos",
        "grafomotricidad-avanzada",
        "repaso-de-trazos"
      ]
    },
    {
      "base": "numeros-punteados-0-9",
      "variations": [
        "numeros-punteados-0-4",
        "numeros-punteados-5-9",
        "repasa-y-escribe-los-numeros",
        "numeros-punteados-1-10",
        "numeros-punteados-11-20"
      ]
    },
    {
      "base": "abecedario-punteado-mayusculas",
      "variations": [
        "letras-punteadas-g-l",
        "letras-punteadas-m-r",
        "letras-punteadas-s-z",
        "la-letra-n-punteada",
        "mis-primeras-letras-a-b-c-d"
      ]
    },
    {
      "base": "palabras-de-uso-frecuente",
      "variations": [
        "palabras-frecuentes-lista-2",
        "palabras-frecuentes-lista-3",
        "palabras-frecuentes-lista-4",
        "palabras-frecuentes-lista-5",
        "palabras-frecuentes-lista-6"
      ]
    },
    {
      "base": "recortar-y-pegar",
      "variations": [
        "recortar-y-pegar-vehiculos",
        "recortar-y-pegar-frutas",
        "recortar-y-pegar-juguetes",
        "recorta-y-pega-en-dos-grupos"
      ]
    },
    {
      "base": "colorear-por-numeros",
      "variations": [
        "colorear-segun-la-figura",
        "colorear-por-numeros-infantil",
        "colorear-con-restas",
        "colorear-sumas-y-restas",
        "colorear-sumas-hasta-20"
      ]
    },
    {
      "base": "laberintos-infantil",
      "variations": [
        "laberinto-facil-frutas",
        "laberinto-dificil-vehiculos",
        "laberinto-gigante-juguetes",
        "laberinto-de-animales",
        "laberinto-de-frutas"
      ]
    },
    {
      "base": "amigos-del-10",
      "variations": [
        "amigos-del-5",
        "descomposicion-hasta-10",
        "amigos-del-20",
        "las-partes-y-el-todo",
        "amigos-del-10-con-puntos"
      ]
    },
    {
      "base": "calculo-mental-hasta-20",
      "variations": [
        "calculo-mental-hasta-10",
        "el-numero-que-falta-hasta-20",
        "sumas-mentales-hasta-20",
        "restas-mentales-hasta-20",
        "el-numero-que-falta-hasta-10"
      ]
    },
    {
      "base": "familias-de-operaciones",
      "variations": [
        "casitas-de-operaciones-hasta-10",
        "casitas-de-operaciones-hasta-20",
        "mas-casitas-de-sumas-y-restas",
        "casitas-el-numero-escondido",
        "familias-de-multiplicar-y-dividir"
      ]
    },
    {
      "base": "numeros-en-letras",
      "variations": [
        "numeros-en-letras-hasta-20",
        "las-decenas-en-letras",
        "une-numeros-con-palabras",
        "numeros-en-letras-hasta-50",
        "escribe-los-numeros-en-letras"
      ]
    },
    {
      "base": "contar-monedas",
      "variations": [
        "contar-monedas-primeros-pasos",
        "contar-con-todas-las-monedas",
        "practica-de-contar-monedas",
        "monedas-de-1-y-2-centimos",
        "que-monedero-tiene-mas-dinero"
      ]
    },
    {
      "base": "dibujar-las-agujas-del-reloj",
      "variations": [
        "dibujar-las-agujas-en-punto",
        "dibujar-las-agujas-y-media",
        "dibujar-las-agujas-y-cuarto",
        "dibujar-las-agujas-de-5-en-5",
        "repaso-de-las-horas-del-reloj"
      ]
    },
    {
      "base": "problemas-de-suma-y-resta",
      "variations": [
        "problemas-de-sumas-con-dibujos",
        "problemas-de-restas-con-dibujos",
        "problemas-hasta-10",
        "tres-problemas-con-dibujos",
        "problemas-con-dibujos-de-animales"
      ]
    },
    {
      "base": "sumas-y-restas-sin-llevar",
      "variations": [
        "sumas-sin-llevar-de-dos-cifras",
        "restas-sin-llevar-de-dos-cifras",
        "sumas-y-restas-de-tres-cifras-sin-llevar",
        "sumas-sin-llevar-de-tres-cifras",
        "repaso-de-cuentas-sin-llevar"
      ]
    },
    {
      "base": "capacidad-y-masa",
      "variations": [
        "leer-jarras-medidoras-ml",
        "leer-la-balanza-en-gramos",
        "escalas-con-marcas-de-50-ml",
        "jarras-medidoras-hasta-2000-ml",
        "capacidad-y-masa-con-animales"
      ]
    },
    {
      "base": "simetria-en-cuadricula",
      "variations": [
        "simetria-en-cuadricula-facil",
        "simetria-en-cuadricula-dificil",
        "simetria-corazon-y-mariposa",
        "simetria-casa-y-corona",
        "simetria-con-eje-horizontal"
      ]
    },
    {
      "base": "comprension-lectora",
      "variations": [
        "comprension-lectora-la-caracola",
        "comprension-lectora-el-huerto",
        "comprension-lectora-la-tormenta",
        "comprension-lectora-el-tren",
        "comprension-lectora-el-teatro"
      ]
    },
    {
      "base": "sumas-y-restas-con-llevadas",
      "variations": [
        "sumas-con-llevadas-dos-cifras",
        "restas-con-llevadas",
        "sumas-con-llevadas-tres-cifras",
        "restas-con-llevadas-y-ceros",
        "repaso-sumas-y-restas-con-llevadas"
      ]
    },
    {
      "base": "tablas-de-multiplicar",
      "variations": [
        "tabla-del-2",
        "tabla-del-5",
        "tabla-del-10",
        "tabla-del-3",
        "tabla-del-4"
      ]
    },
    {
      "base": "minusculas-punteadas",
      "variations": [
        "minusculas-punteadas-g-a-l",
        "minusculas-punteadas-m-a-r",
        "minusculas-punteadas-s-a-z",
        "letra-n-minuscula-punteada",
        "primeras-minusculas-punteadas"
      ]
    },
    {
      "base": "repasar-y-escribir-palabras-preescolar",
      "variations": [
        "repasar-y-escribir-palabras-cortas-preescolar",
        "repasar-una-vez-y-escribir-dos-veces-preescolar",
        "repasar-y-escribir-palabras-largas-preescolar"
      ]
    },
    {
      "base": "unir-los-puntos-del-1-al-20-preescolar",
      "variations": [
        "unir-los-puntos-del-1-al-10-preescolar",
        "unir-los-puntos-del-11-al-20-preescolar",
        "unir-los-puntos-del-11-al-30-preescolar"
      ]
    },
    {
      "base": "copiar-en-la-cuadricula-preescolar",
      "variations": [
        "copiar-en-la-cuadricula-6x6-preescolar",
        "copiar-en-la-cuadricula-con-letras-y-numeros-preescolar",
        "copiar-en-la-cuadricula-8x8-preescolar"
      ]
    },
    {
      "base": "singular-y-plural-preescolar",
      "variations": [
        "singular-y-plural-palabras-cortas-preescolar",
        "singular-y-plural-palabras-largas-preescolar"
      ]
    },
    {
      "base": "el-o-la-articulos-preescolar",
      "variations": [
        "el-o-la-cuatro-dibujos-preescolar",
        "el-o-la-ocho-dibujos-preescolar"
      ]
    },
    {
      "base": "lee-y-colorea-primer-grado",
      "variations": [
        "lee-y-colorea-cuatro-frases-primer-grado",
        "lee-y-colorea-cantidades-hasta-5-primer-grado"
      ]
    },
    {
      "base": "el-numero-del-dia-primer-grado",
      "variations": [
        "el-numero-del-dia-del-11-al-19-primer-grado",
        "el-numero-del-dia-10-mas-y-10-menos-primer-grado",
        "el-numero-del-dia-numeros-de-dos-cifras-primer-grado"
      ]
    },
    {
      "base": "dictado-mudo-escribe-la-palabra-primer-grado",
      "variations": [
        "dictado-mudo-con-la-primera-letra-primer-grado",
        "dictado-mudo-con-banco-de-palabras-primer-grado",
        "dictado-mudo-sin-banco-de-palabras-primer-grado"
      ]
    },
    {
      "base": "orden-alfabetico-primer-grado",
      "variations": [
        "orden-alfabetico-numera-las-tarjetas-primer-grado",
        "orden-alfabetico-numera-y-copia-primer-grado",
        "orden-alfabetico-misma-letra-inicial-primer-grado"
      ]
    },
    {
      "base": "piramides-numericas-primer-grado",
      "variations": [
        "piramides-numericas-hasta-10-primer-grado",
        "piramides-numericas-de-cuatro-pisos-primer-grado",
        "piramides-numericas-falta-un-ladrillo-primer-grado"
      ]
    },
    {
      "base": "dobles-y-mitades-primer-grado",
      "variations": [
        "dobles-y-mitades-hasta-8-primer-grado",
        "dobles-y-mitades-hasta-20-primer-grado"
      ]
    },
    {
      "base": "recta-numerica-primer-grado",
      "variations": [
        "recta-numerica-del-0-al-10-primer-grado",
        "recta-numerica-del-0-al-20-con-pocas-etiquetas-primer-grado",
        "recta-numerica-del-0-al-30-primer-grado"
      ]
    },
    {
      "base": "ordena-la-frase-primer-grado",
      "variations": []
    },
    {
      "base": "mayusculas-y-puntuacion-segundo-grado",
      "variations": []
    },
    {
      "base": "sustantivo-verbo-adjetivo-segundo-grado",
      "variations": []
    },
    {
      "base": "problemas-con-dinero-segundo-grado",
      "variations": []
    },
    {
      "base": "lee-el-calendario-segundo-grado",
      "variations": []
    },
    {
      "base": "escribe-sobre-la-imagen-segundo-grado",
      "variations": []
    },
    {
      "base": "coordenadas-en-la-cuadricula-segundo-grado",
      "variations": []
    },
    {
      "base": "problemas-de-multiplicacion-y-division-tercer-grado",
      "variations": []
    }
  ],
  "fr": [
    {
      "base": "graphisme-maternelle",
      "variations": [
        "graphisme-lignes-et-zigzags",
        "graphisme-vagues-et-ponts",
        "graphisme-boucles-et-spirales",
        "graphisme-traces-difficiles",
        "graphisme-la-grande-revision"
      ]
    },
    {
      "base": "ecriture-des-chiffres",
      "variations": [
        "ecriture-des-chiffres-0-4",
        "ecriture-des-chiffres-5-9",
        "repasser-et-ecrire-les-chiffres",
        "ecriture-des-nombres-1-10",
        "ecriture-des-nombres-11-20"
      ]
    },
    {
      "base": "ecriture-lettres-capitales",
      "variations": [
        "ecriture-des-lettres-g-l",
        "ecriture-des-lettres-m-r",
        "ecriture-des-lettres-s-z",
        "ecriture-des-lettres-accentuees",
        "premieres-lettres-a-b-c-d"
      ]
    },
    {
      "base": "mots-outils",
      "variations": [
        "mots-outils-liste-2",
        "mots-outils-liste-3",
        "mots-outils-liste-4",
        "mots-outils-liste-5",
        "mots-outils-liste-6"
      ]
    },
    {
      "base": "decoupage-collage",
      "variations": [
        "decoupage-collage-vehicules",
        "decoupage-collage-fruits",
        "decoupage-collage-jouets",
        "decoupage-collage-deux-groupes"
      ]
    },
    {
      "base": "coloriage-magique",
      "variations": [
        "coloriage-magique-des-formes",
        "coloriage-par-numeros",
        "coloriage-magique-soustraction",
        "coloriage-magique-addition-et-soustraction",
        "coloriage-magique-sommes-11-20"
      ]
    },
    {
      "base": "labyrinthe-maternelle",
      "variations": [
        "labyrinthe-facile",
        "labyrinthe-difficile",
        "labyrinthe-geant",
        "labyrinthe-des-animaux",
        "labyrinthe-des-fruits"
      ]
    },
    {
      "base": "complements-a-10",
      "variations": [
        "complements-a-5",
        "decomposition-des-nombres-jusqu-a-10",
        "complements-a-20",
        "complements-trouver-le-tout",
        "complements-a-10-avec-points"
      ]
    },
    {
      "base": "calcul-mental-cp",
      "variations": [
        "calcul-mental-jusqu-a-10",
        "nombre-manquant-jusqu-a-20",
        "calcul-mental-additions-jusqu-a-20",
        "calcul-mental-soustractions-jusqu-a-20",
        "nombre-manquant-jusqu-a-10"
      ]
    },
    {
      "base": "familles-operations",
      "variations": [
        "familles-operations-jusqu-a-10",
        "familles-operations-jusqu-a-20",
        "maisons-des-nombres-jusqu-a-10",
        "familles-operations-nombre-cache",
        "familles-multiplication-division"
      ]
    },
    {
      "base": "nombres-en-lettres",
      "variations": [
        "nombres-en-lettres-jusqu-a-20",
        "dizaines-en-lettres",
        "relier-nombres-et-mots",
        "nombres-en-lettres-jusqu-a-50",
        "ecrire-les-nombres-en-lettres"
      ]
    },
    {
      "base": "compter-la-monnaie",
      "variations": [
        "compter-la-monnaie-premiers-pas",
        "compter-toutes-les-pieces",
        "entrainement-compter-les-pieces",
        "compter-les-petites-pieces",
        "porte-monnaie-le-plus-d-argent"
      ]
    },
    {
      "base": "dessiner-les-aiguilles",
      "variations": [
        "dessiner-les-aiguilles-heures-piles",
        "dessiner-les-aiguilles-et-demie",
        "dessiner-les-aiguilles-et-quart",
        "dessiner-les-aiguilles-de-5-en-5",
        "dessiner-les-aiguilles-revision"
      ]
    },
    {
      "base": "petits-problemes",
      "variations": [
        "problemes-d-addition-en-images",
        "problemes-de-soustraction-en-images",
        "petits-problemes-jusqu-a-10",
        "trois-petits-problemes-en-images",
        "petits-problemes-animaux"
      ]
    },
    {
      "base": "operations-posees-sans-retenue",
      "variations": [
        "additions-posees-sans-retenue",
        "soustractions-posees-sans-retenue",
        "operations-posees-3-chiffres",
        "additions-posees-3-chiffres",
        "operations-posees-revision"
      ]
    },
    {
      "base": "masses-et-contenances",
      "variations": [
        "lire-le-verre-doseur-millilitres",
        "lire-la-balance-en-grammes",
        "lire-les-petites-graduations",
        "verres-doseurs-jusqu-a-2000-ml",
        "masses-et-contenances-animaux"
      ]
    },
    {
      "base": "symetrie-quadrillage",
      "variations": [
        "symetrie-quadrillage-facile",
        "symetrie-quadrillage-difficile",
        "symetrie-coeur-et-papillon",
        "symetrie-maison-et-couronne",
        "symetrie-axe-horizontal"
      ]
    },
    {
      "base": "lecture-comprehension",
      "variations": [
        "lecture-ce1-crabe-de-la-plage",
        "lecture-ce1-escargot-du-potager",
        "lecture-ce1-nuit-en-camping",
        "lecture-ce1-marche-du-samedi",
        "lecture-ce1-spectacle-de-l-ecole"
      ]
    },
    {
      "base": "operations-posees-avec-retenue",
      "variations": [
        "addition-avec-retenue",
        "soustraction-avec-retenue",
        "addition-3-chiffres-avec-retenue",
        "soustraction-avec-des-zeros",
        "additions-et-soustractions-avec-retenue"
      ]
    },
    {
      "base": "tables-de-multiplication",
      "variations": [
        "table-de-2",
        "table-de-5",
        "table-de-10",
        "table-de-3",
        "table-de-4"
      ]
    },
    {
      "base": "ecriture-des-minuscules",
      "variations": [
        "ecriture-des-minuscules-g-a-l",
        "ecriture-des-minuscules-m-a-r",
        "ecriture-des-minuscules-s-a-z",
        "ecriture-des-minuscules-accentuees",
        "premieres-minuscules"
      ]
    },
    {
      "base": "repasser-et-ecrire-les-mots-animaux",
      "variations": []
    },
    {
      "base": "points-a-relier-1-a-20-maternelle",
      "variations": []
    },
    {
      "base": "reproduction-sur-quadrillage-maternelle",
      "variations": []
    },
    {
      "base": "singulier-et-pluriel-maternelle-fruits",
      "variations": []
    },
    {
      "base": "le-ou-la-entoure-l-article-animaux",
      "variations": []
    },
    {
      "base": "lis-et-colorie-cp-fruits",
      "variations": []
    },
    {
      "base": "le-nombre-du-jour-cp",
      "variations": []
    },
    {
      "base": "dictee-muette-cp-fruits",
      "variations": []
    },
    {
      "base": "ordre-alphabetique-cp-animaux",
      "variations": []
    },
    {
      "base": "pyramides-de-nombres-cp",
      "variations": []
    },
    {
      "base": "doubles-et-moities-cp-fruits",
      "variations": []
    },
    {
      "base": "droite-graduee-quel-nombre-cp",
      "variations": []
    },
    {
      "base": "phrases-melangees-cp-animaux",
      "variations": []
    },
    {
      "base": "majuscules-et-ponctuation-ce1-vehicules",
      "variations": []
    },
    {
      "base": "nature-des-mots-nom-verbe-adjectif-ce1",
      "variations": []
    },
    {
      "base": "problemes-de-monnaie-la-marchande-ce1",
      "variations": []
    },
    {
      "base": "lire-le-calendrier-ce1",
      "variations": []
    },
    {
      "base": "production-d-ecrit-a-partir-d-une-image-ce1",
      "variations": []
    },
    {
      "base": "pixel-art-reperage-sur-quadrillage-ce1",
      "variations": []
    },
    {
      "base": "problemes-de-multiplication-et-division-ce2",
      "variations": []
    }
  ],
  "pt": [
    {
      "base": "grafismo-tracados",
      "variations": [
        "grafismo-retas-e-ziguezagues",
        "grafismo-ondas-e-curvas",
        "grafismo-lacos-e-espirais",
        "grafismo-avancado",
        "revisao-de-tracados"
      ]
    },
    {
      "base": "numeros-pontilhados",
      "variations": [
        "numeros-pontilhados-0-a-4",
        "numeros-pontilhados-5-a-9",
        "cubra-e-escreva-os-numeros",
        "numeros-pontilhados-1-a-10",
        "numeros-pontilhados-11-a-20"
      ]
    },
    {
      "base": "letras-pontilhadas",
      "variations": [
        "letras-pontilhadas-g-a-m",
        "letras-pontilhadas-n-a-s",
        "letras-pontilhadas-s-a-z",
        "letras-k-w-y",
        "primeiras-letras-abcd"
      ]
    },
    {
      "base": "palavras-frequentes",
      "variations": [
        "palavras-frequentes-lista-2",
        "palavras-frequentes-lista-3",
        "palavras-frequentes-lista-4",
        "palavras-frequentes-lista-5",
        "palavras-frequentes-lista-6"
      ]
    },
    {
      "base": "recorte-e-colagem",
      "variations": [
        "recorte-e-colagem-veiculos",
        "recorte-e-colagem-frutas",
        "recorte-e-colagem-brinquedos",
        "recorte-e-cole-em-dois-grupos"
      ]
    },
    {
      "base": "pinte-conforme-o-resultado",
      "variations": [
        "pinte-conforme-a-forma",
        "colorir-por-numeros",
        "colorir-com-continhas-de-menos",
        "colorir-com-mais-e-menos",
        "colorir-somas-ate-20"
      ]
    },
    {
      "base": "labirintos",
      "variations": [
        "labirinto-facil",
        "labirinto-dificil",
        "labirinto-gigante",
        "labirinto-de-animais",
        "labirinto-de-frutas"
      ]
    },
    {
      "base": "amigos-do-10",
      "variations": [
        "amigos-do-5",
        "amigos-dos-numeros-5-a-10",
        "amigos-do-20",
        "qual-e-o-todo",
        "amigos-do-10-com-bolinhas"
      ]
    },
    {
      "base": "calculo-mental-ate-20",
      "variations": [
        "calculo-mental-ate-10",
        "numero-que-falta-ate-20",
        "continhas-de-mais-ate-20",
        "continhas-de-menos-ate-20",
        "numero-que-falta-ate-10"
      ]
    },
    {
      "base": "familia-de-fatos",
      "variations": [
        "familia-de-fatos-ate-10",
        "familia-de-fatos-ate-20",
        "casinhas-matematicas-ate-10",
        "casinhas-com-numero-escondido",
        "casinhas-de-multiplicar-e-dividir"
      ]
    },
    {
      "base": "numeros-por-extenso",
      "variations": [
        "numeros-por-extenso-ate-20",
        "dezenas-por-extenso-10-a-100",
        "ligue-o-numero-ao-nome",
        "numeros-por-extenso-ate-50",
        "escreva-os-numeros-por-extenso"
      ]
    },
    {
      "base": "contando-moedas",
      "variations": [
        "contando-moedas-primeiros-passos",
        "contando-dinheiro-todas-as-moedas",
        "treino-de-contar-moedas",
        "moedas-de-5-e-10-centavos",
        "qual-carteira-tem-mais-dinheiro"
      ]
    },
    {
      "base": "desenhe-os-ponteiros",
      "variations": [
        "horas-em-ponto-no-relogio",
        "meia-hora-no-relogio",
        "quartos-de-hora-no-relogio",
        "horas-de-5-em-5-minutos",
        "revisao-de-horas-no-relogio"
      ]
    },
    {
      "base": "situacoes-problema",
      "variations": [
        "situacoes-problema-de-adicao",
        "situacoes-problema-de-subtracao",
        "situacoes-problema-ate-10",
        "tres-situacoes-problema",
        "situacoes-problema-com-animais"
      ]
    },
    {
      "base": "continhas-armadas",
      "variations": [
        "adicao-armada-2-algarismos",
        "subtracao-armada-2-algarismos",
        "continhas-armadas-3-algarismos",
        "adicao-armada-3-algarismos",
        "revisao-de-continhas-armadas"
      ]
    },
    {
      "base": "medidas-de-capacidade-e-massa",
      "variations": [
        "leitura-de-jarras-em-ml",
        "balancas-em-gramas",
        "escalas-de-50-em-50-ml",
        "jarras-grandes-ate-2000-ml",
        "jarras-e-balancas-com-animais"
      ]
    },
    {
      "base": "simetria-na-malha",
      "variations": [
        "simetria-facil-na-malha",
        "simetria-dificil-na-malha",
        "simetria-coracao-e-borboleta",
        "simetria-casa-e-coroa",
        "simetria-com-linha-horizontal"
      ]
    },
    {
      "base": "interpretacao-de-texto",
      "variations": [
        "interpretacao-o-castelo-de-areia",
        "interpretacao-a-padaria-do-seu-jose",
        "interpretacao-um-dia-no-sitio",
        "interpretacao-a-bicicleta-nova",
        "interpretacao-a-festa-junina"
      ]
    },
    {
      "base": "continhas-com-reagrupamento",
      "variations": [
        "adicao-com-vai-um",
        "subtracao-com-emprestimo",
        "adicao-com-vai-um-3-algarismos",
        "subtracao-emprestando-do-zero",
        "revisao-vai-um-e-emprestimo"
      ]
    },
    {
      "base": "tabuada",
      "variations": [
        "tabuada-do-2",
        "tabuada-do-5",
        "tabuada-do-10",
        "tabuada-do-3",
        "tabuada-do-4"
      ]
    },
    {
      "base": "minusculas-pontilhadas",
      "variations": [
        "minusculas-pontilhadas-g-a-m",
        "minusculas-pontilhadas-n-a-s",
        "minusculas-pontilhadas-s-a-z",
        "minusculas-k-w-y-pontilhadas",
        "primeiras-minusculas-pontilhadas"
      ]
    },
    {
      "base": "palavras-pontilhadas-animais-educacao-infantil",
      "variations": [
        "palavras-pontilhadas-curtas-frutas-educacao-infantil",
        "palavras-pontilhadas-cobrir-uma-vez-escrever-duas",
        "palavras-pontilhadas-longas-brinquedos-educacao-infantil"
      ]
    },
    {
      "base": "ligue-os-pontos-1-a-20-educacao-infantil",
      "variations": [
        "ligue-os-pontos-de-1-a-10-educacao-infantil",
        "ligue-os-pontos-de-11-a-20-educacao-infantil",
        "ligue-os-pontos-de-11-a-30-educacao-infantil"
      ]
    },
    {
      "base": "copie-o-desenho-na-malha-quadriculada",
      "variations": [
        "copie-o-desenho-malha-6-por-6-sem-coordenadas",
        "copie-o-desenho-com-letras-e-numeros",
        "copie-o-desenho-malha-8-por-8"
      ]
    },
    {
      "base": "singular-e-plural-frutas-educacao-infantil",
      "variations": [
        "singular-e-plural-palavras-curtas-animais",
        "singular-e-plural-palavras-longas-veiculos"
      ]
    },
    {
      "base": "o-ou-a-artigo-animais-educacao-infantil",
      "variations": [
        "o-ou-a-quatro-figuras-animais",
        "o-ou-a-oito-figuras-veiculos"
      ]
    },
    {
      "base": "leia-e-pinte-frutas-1o-ano",
      "variations": [
        "leia-e-pinte-quatro-frases-animais-1o-ano",
        "leia-e-pinte-seis-frases-brinquedos-1o-ano"
      ]
    },
    {
      "base": "numero-do-dia-1o-ano",
      "variations": [
        "numero-do-dia-de-11-a-19-1o-ano",
        "numero-do-dia-10-a-mais-10-a-menos",
        "numero-do-dia-ate-99-1o-ano"
      ]
    },
    {
      "base": "escreva-o-nome-das-figuras-frutas-1o-ano",
      "variations": [
        "escreva-o-nome-com-banco-e-primeira-letra",
        "escreva-o-nome-com-banco-de-palavras-veiculos",
        "escreva-o-nome-sem-banco-brinquedos"
      ]
    },
    {
      "base": "ordem-alfabetica-animais-1o-ano",
      "variations": [
        "ordem-alfabetica-numere-quatro-palavras-frutas",
        "ordem-alfabetica-numere-e-copie-veiculos",
        "ordem-alfabetica-mesma-letra-inicial-brinquedos"
      ]
    },
    {
      "base": "piramide-de-numeros-1o-ano",
      "variations": [
        "piramide-de-numeros-ate-10-1o-ano",
        "piramide-de-numeros-quatro-andares",
        "piramide-de-numeros-tijolo-que-falta"
      ]
    },
    {
      "base": "dobro-e-metade-frutas-1o-ano",
      "variations": [
        "dobro-e-metade-com-figuras-animais",
        "dobro-e-metade-ate-20-so-com-numeros"
      ]
    },
    {
      "base": "reta-numerica-ate-20-1o-ano",
      "variations": [
        "reta-numerica-ate-10-1o-ano",
        "reta-numerica-ate-20-menos-numeros",
        "reta-numerica-ate-30-1o-ano"
      ]
    },
    {
      "base": "ordene-a-frase-animais-1o-ano",
      "variations": []
    },
    {
      "base": "letra-maiuscula-e-pontuacao-2o-ano",
      "variations": []
    },
    {
      "base": "substantivo-verbo-adjetivo-brinquedos-2o-ano",
      "variations": []
    },
    {
      "base": "problemas-com-dinheiro-vamos-as-compras-2o-ano",
      "variations": []
    },
    {
      "base": "leitura-de-calendario-2o-ano",
      "variations": []
    },
    {
      "base": "producao-de-texto-com-imagem-veiculos-2o-ano",
      "variations": []
    },
    {
      "base": "coordenadas-na-malha-quadriculada-2o-ano",
      "variations": []
    },
    {
      "base": "problemas-de-multiplicacao-e-divisao-3o-ano",
      "variations": []
    }
  ],
  "it": [
    {
      "base": "pregrafismo-percorsi",
      "variations": [
        "pregrafismo-linee-rette-e-zigzag",
        "pregrafismo-onde-e-linee-curve",
        "pregrafismo-occhielli-otto-e-spirali",
        "pregrafismo-avanzato-cinque-corsie",
        "pregrafismo-ripasso-cinque-tracciati"
      ]
    },
    {
      "base": "numeri-tratteggiati",
      "variations": [
        "numeri-tratteggiati-da-0-a-4",
        "numeri-tratteggiati-da-5-a-9",
        "ripassa-e-scrivi-i-numeri",
        "numeri-tratteggiati-da-1-a-10",
        "numeri-tratteggiati-da-11-a-20"
      ]
    },
    {
      "base": "lettere-maiuscole-tratteggiate",
      "variations": [
        "lettere-tratteggiate-da-g-a-n",
        "lettere-tratteggiate-da-o-a-t",
        "lettere-tratteggiate-da-r-a-z",
        "vocali-tratteggiate",
        "prime-lettere-abcd"
      ]
    },
    {
      "base": "parole-frequenti",
      "variations": [
        "parole-frequenti-serie-2",
        "parole-frequenti-serie-3",
        "parole-frequenti-serie-4",
        "parole-frequenti-serie-5",
        "parole-frequenti-serie-6"
      ]
    },
    {
      "base": "ritaglia-e-incolla",
      "variations": [
        "ritaglia-e-incolla-veicoli",
        "ritaglia-e-incolla-frutta",
        "ritaglia-e-incolla-giocattoli",
        "ritaglia-e-incolla-due-gruppi"
      ]
    },
    {
      "base": "calcola-e-colora",
      "variations": [
        "colora-in-base-alla-forma",
        "colora-con-i-numeri",
        "colora-con-le-sottrazioni",
        "colora-con-addizioni-e-sottrazioni",
        "colora-con-le-somme-fino-a-20"
      ]
    },
    {
      "base": "labirinti-per-bambini",
      "variations": [
        "labirinto-facile-frutta",
        "labirinto-difficile-veicoli",
        "labirinto-gigante-giocattoli",
        "labirinto-degli-animali",
        "labirinto-della-frutta"
      ]
    },
    {
      "base": "amici-del-10",
      "variations": [
        "amici-del-5-con-i-puntini",
        "scomposizioni-fino-a-10",
        "amici-del-20",
        "scomposizioni-trova-il-totale",
        "amici-del-10-con-i-puntini"
      ]
    },
    {
      "base": "calcolo-mentale-fino-a-20",
      "variations": [
        "calcolo-mentale-fino-a-10",
        "numero-mancante-fino-a-20",
        "addizioni-a-mente-fino-a-20",
        "sottrazioni-a-mente-fino-a-20",
        "numero-mancante-fino-a-10"
      ]
    },
    {
      "base": "famiglie-di-operazioni",
      "variations": [
        "famiglie-di-operazioni-fino-a-10",
        "famiglie-di-operazioni-fino-a-20",
        "casette-delle-operazioni-fino-a-10",
        "famiglie-con-il-numero-mancante",
        "famiglie-del-per-e-del-diviso"
      ]
    },
    {
      "base": "numeri-in-lettere",
      "variations": [
        "numeri-in-lettere-fino-a-20",
        "decine-in-lettere-da-10-a-100",
        "collega-numeri-e-parole",
        "numeri-in-lettere-fino-a-50",
        "scrivi-i-numeri-in-lettere"
      ]
    },
    {
      "base": "contare-le-monete",
      "variations": [
        "contare-le-monete-primi-passi",
        "contare-gli-euro-tutte-le-monete",
        "allenamento-con-le-monete",
        "monete-da-1-e-2-centesimi",
        "quale-borsellino-ha-di-piu"
      ]
    },
    {
      "base": "disegna-le-lancette",
      "variations": [
        "disegna-le-lancette-ore-in-punto",
        "disegna-le-lancette-e-mezza",
        "disegna-le-lancette-quarti-di-ora",
        "disegna-le-lancette-di-5-in-5-minuti",
        "disegna-le-lancette-ripasso"
      ]
    },
    {
      "base": "problemi-illustrati",
      "variations": [
        "problemi-di-addizione-illustrati",
        "problemi-di-sottrazione-illustrati",
        "problemi-illustrati-fino-a-10",
        "tre-problemi-illustrati",
        "problemi-illustrati-con-gli-animali"
      ]
    },
    {
      "base": "operazioni-in-colonna-senza-cambio",
      "variations": [
        "addizioni-in-colonna-a-due-cifre",
        "sottrazioni-in-colonna-a-due-cifre",
        "operazioni-in-colonna-a-tre-cifre",
        "addizioni-in-colonna-a-tre-cifre",
        "ripasso-operazioni-in-colonna"
      ]
    },
    {
      "base": "capacita-e-peso",
      "variations": [
        "capacita-in-millilitri",
        "il-peso-in-grammi",
        "misurare-con-precisione-tacche-da-50-ml",
        "capacita-fino-a-2000-ml",
        "capacita-e-peso-con-gli-animali"
      ]
    },
    {
      "base": "simmetria-sui-quadretti",
      "variations": [
        "simmetria-facile-sui-quadretti",
        "simmetria-difficile-sui-quadretti",
        "disegni-a-specchio-cuore-e-farfalla",
        "disegni-a-specchio-casa-e-corona",
        "simmetria-con-la-linea-orizzontale"
      ]
    },
    {
      "base": "comprensione-del-testo",
      "variations": [
        "comprensione-il-riccio-nel-giardino",
        "comprensione-orto-della-scuola",
        "comprensione-una-mattina-di-neve",
        "comprensione-sabato-al-mercato",
        "comprensione-gita-in-montagna"
      ]
    },
    {
      "base": "operazioni-in-colonna-con-il-cambio",
      "variations": [
        "addizioni-con-il-riporto",
        "sottrazioni-con-il-prestito",
        "addizioni-a-tre-cifre",
        "sottrazioni-con-gli-zeri",
        "ripasso-riporto-e-prestito"
      ]
    },
    {
      "base": "tabelline",
      "variations": [
        "tabellina-del-2",
        "tabellina-del-5",
        "tabellina-del-10",
        "tabellina-del-3",
        "tabellina-del-4"
      ]
    },
    {
      "base": "minuscole-tratteggiate",
      "variations": [
        "minuscole-tratteggiate-g-n",
        "minuscole-tratteggiate-o-t",
        "minuscole-tratteggiate-r-z",
        "vocali-minuscole-tratteggiate",
        "prime-minuscole-tratteggiate"
      ]
    },
    {
      "base": "ricalca-e-scrivi-le-parole-animali",
      "variations": []
    },
    {
      "base": "unisci-i-puntini-1-20",
      "variations": []
    },
    {
      "base": "riproduci-il-disegno-sui-quadretti",
      "variations": []
    },
    {
      "base": "singolare-e-plurale-frutta",
      "variations": []
    },
    {
      "base": "il-o-la-articoli-determinativi",
      "variations": []
    },
    {
      "base": "leggi-e-colora-frutta",
      "variations": []
    },
    {
      "base": "il-numero-del-giorno-classe-prima",
      "variations": []
    },
    {
      "base": "dettato-muto-frutta",
      "variations": []
    },
    {
      "base": "ordine-alfabetico-animali",
      "variations": []
    },
    {
      "base": "piramidi-di-numeri-fino-a-20",
      "variations": []
    },
    {
      "base": "doppio-e-meta-classe-prima",
      "variations": []
    },
    {
      "base": "linea-dei-numeri-fino-a-20",
      "variations": []
    },
    {
      "base": "riordina-la-frase-animali",
      "variations": []
    },
    {
      "base": "maiuscole-e-punteggiatura-classe-seconda",
      "variations": []
    },
    {
      "base": "nome-verbo-aggettivo-classe-seconda",
      "variations": []
    },
    {
      "base": "problemi-con-i-soldi-la-spesa",
      "variations": []
    },
    {
      "base": "leggere-il-calendario-classe-seconda",
      "variations": []
    },
    {
      "base": "scrivi-guardando-l-immagine-veicoli",
      "variations": []
    },
    {
      "base": "coordinate-sulla-griglia-pixel-art",
      "variations": []
    },
    {
      "base": "problemi-di-moltiplicazione-e-divisione-classe-terza",
      "variations": []
    }
  ],
  "nl": [
    {
      "base": "schrijfpatronen-oefenen",
      "variations": [
        "schrijfpatronen-zigzaglijnen",
        "schrijfpatronen-golven-en-boogjes",
        "schrijfpatronen-lussen-en-achtjes",
        "moeilijke-schrijfpatronen",
        "schrijfpatronen-herhalen"
      ]
    },
    {
      "base": "cijfers-schrijven-0-tot-9",
      "variations": [
        "cijfers-schrijven-0-tot-4",
        "cijfers-schrijven-5-tot-9",
        "cijfers-natrekken-en-zelf-schrijven",
        "getallen-schrijven-1-tot-10",
        "getallen-schrijven-11-tot-20"
      ]
    },
    {
      "base": "hoofdletters-overtrekken",
      "variations": [
        "letters-overtrekken-g-tot-l",
        "letters-overtrekken-m-tot-r",
        "letters-overtrekken-s-tot-z",
        "letter-ij-schrijven",
        "hoofdletters-a-b-c-d"
      ]
    },
    {
      "base": "flitswoorden-oefenen",
      "variations": [
        "flitswoorden-lijst-2",
        "flitswoorden-lijst-3",
        "flitswoorden-lijst-4",
        "flitswoorden-lijst-5",
        "flitswoorden-lijst-6"
      ]
    },
    {
      "base": "knippen-sorteren-plakken",
      "variations": [
        "knippen-en-plakken-voertuigen",
        "knippen-en-plakken-fruit",
        "knippen-en-plakken-speelgoed",
        "knippen-en-plakken-twee-groepen"
      ]
    },
    {
      "base": "kleuren-op-code",
      "variations": [
        "kleuren-op-vormcode",
        "kleuren-op-nummer",
        "kleuren-met-aftreksommen",
        "kleuren-met-plus-en-minsommen",
        "kleuren-met-sommen-tot-20"
      ]
    },
    {
      "base": "doolhof-werkblad",
      "variations": [
        "makkelijk-doolhof",
        "moeilijk-doolhof",
        "reuzendoolhof",
        "doolhof-dieren",
        "doolhof-fruit"
      ]
    },
    {
      "base": "splitsen-tot-10",
      "variations": [
        "splitsen-van-5-met-stippen",
        "splitsen-van-5-tot-10",
        "splitsen-tot-20",
        "splitsen-geheel-ontbreekt",
        "splitsen-van-10-met-stippen"
      ]
    },
    {
      "base": "hoofdrekenen-tot-20",
      "variations": [
        "hoofdrekenen-tot-10",
        "stipsommen-tot-20",
        "optelsommen-tot-20",
        "aftreksommen-tot-20",
        "stipsommen-tot-10"
      ]
    },
    {
      "base": "rekenhuisjes",
      "variations": [
        "rekenhuisjes-tot-10",
        "rekenhuisjes-tot-20",
        "rekenhuisjes-tot-10-extra-oefenen",
        "rekenhuisjes-met-stipsommen",
        "rekenhuisjes-keer-en-delen"
      ]
    },
    {
      "base": "getallen-in-woorden",
      "variations": [
        "getallen-in-woorden-tot-20",
        "tientallen-in-woorden",
        "getal-en-woord-verbinden",
        "getallen-in-woorden-tot-50",
        "getallen-in-woorden-schrijven"
      ]
    },
    {
      "base": "munten-tellen-euro",
      "variations": [
        "munten-tellen-voor-beginners",
        "alle-euromunten-tellen",
        "geld-tellen-extra-oefenen",
        "tellen-met-centen",
        "welke-portemonnee-heeft-meer-geld"
      ]
    },
    {
      "base": "wijzers-tekenen-klokkijken",
      "variations": [
        "wijzers-tekenen-hele-uren",
        "wijzers-tekenen-halve-uren",
        "wijzers-tekenen-kwartieren",
        "wijzers-tekenen-per-vijf-minuten",
        "wijzers-tekenen-alle-tijden"
      ]
    },
    {
      "base": "verhaaltjessommen-met-plaatjes",
      "variations": [
        "verhaaltjessommen-optellen",
        "verhaaltjessommen-aftrekken",
        "verhaaltjessommen-tot-10",
        "drie-verhaaltjessommen",
        "verhaaltjessommen-met-dieren"
      ]
    },
    {
      "base": "sommen-onder-elkaar",
      "variations": [
        "optellen-onder-elkaar-tot-100",
        "aftrekken-onder-elkaar-tot-100",
        "sommen-onder-elkaar-tot-1000",
        "optellen-onder-elkaar-tot-1000",
        "onder-elkaar-rekenen-herhalen"
      ]
    },
    {
      "base": "maatbekers-en-weegschalen",
      "variations": [
        "maatbekers-aflezen",
        "weegschalen-aflezen-in-grammen",
        "maatbekers-aflezen-kleine-stapjes",
        "maatbekers-tot-2000-ml",
        "maatbekers-en-weegschalen-dieren"
      ]
    },
    {
      "base": "spiegeltekening-afmaken",
      "variations": [
        "makkelijke-spiegeltekeningen",
        "moeilijke-spiegeltekeningen",
        "spiegelen-hart-en-vlinder",
        "spiegelen-huis-en-kroon",
        "spiegelen-onder-de-spiegellijn"
      ]
    },
    {
      "base": "begrijpend-lezen-groep-4",
      "variations": [
        "begrijpend-lezen-de-rode-vlieger",
        "begrijpend-lezen-de-egel",
        "begrijpend-lezen-de-klassenvis",
        "begrijpend-lezen-noor-leert-fietsen",
        "begrijpend-lezen-de-bibliotheekbus"
      ]
    },
    {
      "base": "cijferend-rekenen-met-onthouden",
      "variations": [
        "optellen-met-onthouden",
        "aftrekken-met-lenen",
        "optellen-tot-1000-met-onthouden",
        "lenen-over-de-nul",
        "onthouden-en-lenen-oefenen"
      ]
    },
    {
      "base": "tafels-oefenen",
      "variations": [
        "tafel-van-2",
        "tafel-van-5",
        "tafel-van-10",
        "tafel-van-3",
        "tafel-van-4"
      ]
    },
    {
      "base": "kleine-letters-overtrekken",
      "variations": [
        "kleine-letters-overtrekken-g-tot-l",
        "kleine-letters-overtrekken-m-tot-r",
        "kleine-letters-overtrekken-s-tot-z",
        "kleine-ij-overtrekken",
        "eerste-kleine-letters"
      ]
    },
    {
      "base": "woorden-overtrekken-dieren-kleuters",
      "variations": []
    },
    {
      "base": "van-stip-naar-stip-1-tot-20",
      "variations": []
    },
    {
      "base": "natekenen-op-ruitjes-kleuters",
      "variations": []
    },
    {
      "base": "enkelvoud-en-meervoud-fruit",
      "variations": []
    },
    {
      "base": "de-of-het-dieren-kleuters",
      "variations": []
    },
    {
      "base": "lees-en-kleur-fruit-groep-3",
      "variations": []
    },
    {
      "base": "getal-van-de-dag-groep-3",
      "variations": []
    },
    {
      "base": "schrijf-het-woord-bij-het-plaatje-fruit",
      "variations": []
    },
    {
      "base": "alfabetische-volgorde-dieren-groep-3",
      "variations": []
    },
    {
      "base": "rekenpiramide-tot-20-groep-3",
      "variations": []
    },
    {
      "base": "verdubbelen-en-halveren-groep-3",
      "variations": []
    },
    {
      "base": "getallenlijn-tot-20-groep-3",
      "variations": []
    },
    {
      "base": "husselzinnen-dieren-groep-3",
      "variations": []
    },
    {
      "base": "hoofdletters-en-leestekens-groep-4",
      "variations": []
    },
    {
      "base": "woordsoorten-groep-4-speelgoed",
      "variations": []
    },
    {
      "base": "rekenen-met-geld-boodschappen-groep-4",
      "variations": []
    },
    {
      "base": "kalender-lezen-groep-4",
      "variations": []
    },
    {
      "base": "schrijven-bij-een-plaatje-voertuigen",
      "variations": []
    },
    {
      "base": "coordinaten-in-het-rooster-groep-4",
      "variations": []
    },
    {
      "base": "verhaaltjessommen-vermenigvuldigen-en-delen",
      "variations": []
    }
  ],
  "sv": [
    {
      "base": "skrivovningar-spara-linjer",
      "variations": [
        "spara-raka-linjer-sicksack",
        "vagor-och-bagar",
        "oglor-attor-spiraler",
        "svara-sparlinjer",
        "blandade-sparlinjer"
      ]
    },
    {
      "base": "spara-siffror-0-9",
      "variations": [
        "spara-siffror-0-4",
        "spara-siffror-5-9",
        "spara-och-skriv-siffror",
        "spara-talen-1-10",
        "spara-talen-11-20"
      ]
    },
    {
      "base": "spara-stora-bokstaver",
      "variations": [
        "spara-bokstaver-g-l",
        "spara-bokstaver-m-r",
        "spara-bokstaver-s-z",
        "spara-a-a-o",
        "forsta-bokstaverna-abcd"
      ]
    },
    {
      "base": "ordbilder-las-spara-skriv",
      "variations": [
        "ordbilder-lista-2",
        "ordbilder-lista-3",
        "ordbilder-lista-4",
        "ordbilder-lista-5",
        "ordbilder-lista-6"
      ]
    },
    {
      "base": "klipp-och-klistra-sortering",
      "variations": [
        "klipp-och-klistra-fordon",
        "klipp-och-klistra-frukter",
        "klipp-och-klistra-leksaker",
        "klipp-och-klistra-tva-grupper"
      ]
    },
    {
      "base": "mala-efter-kod",
      "variations": [
        "mala-efter-figurkod",
        "farglagg-efter-siffror",
        "mala-efter-kod-subtraktion",
        "mala-efter-kod-plus-och-minus",
        "mala-efter-kod-summor-till-20"
      ]
    },
    {
      "base": "labyrinter-for-barn",
      "variations": [
        "latt-labyrint-frukter",
        "svar-labyrint-fordon",
        "jattelabyrint-leksaker",
        "labyrint-djur",
        "labyrint-frukter"
      ]
    },
    {
      "base": "tiokompisar",
      "variations": [
        "femkompisar",
        "talkamrater-till-10",
        "tjugokompisar",
        "talkamrater-hela-talet",
        "tiokompisar-med-prickar"
      ]
    },
    {
      "base": "huvudrakning-till-20",
      "variations": [
        "huvudrakning-till-10",
        "oppna-utsagor-till-20",
        "addition-till-20",
        "subtraktion-till-20",
        "oppna-utsagor-till-10"
      ]
    },
    {
      "base": "raknefamiljer",
      "variations": [
        "raknefamiljer-till-10",
        "raknefamiljer-till-20",
        "fler-raknefamiljer-till-10",
        "raknefamiljer-talet-i-mitten",
        "raknefamiljer-multiplikation-division"
      ]
    },
    {
      "base": "tal-med-bokstaver",
      "variations": [
        "tal-med-bokstaver-till-20",
        "hela-tiotal-med-bokstaver",
        "para-ihop-tal-och-ord",
        "tal-med-bokstaver-till-50",
        "skriv-talen-med-bokstaver"
      ]
    },
    {
      "base": "rakna-pengar-kronor",
      "variations": [
        "rakna-mynt-forsta-stegen",
        "rakna-pengar-alla-mynt",
        "trana-rakna-mynt",
        "enkronor-och-tvakronor",
        "vilken-bors-har-mest"
      ]
    },
    {
      "base": "rita-klockans-visare",
      "variations": [
        "rita-visarna-hela-timmar",
        "rita-visarna-halva-timmar",
        "rita-visarna-kvart-i-kvart-over",
        "rita-visarna-fem-minuter",
        "rita-visarna-blandade-tider"
      ]
    },
    {
      "base": "raknehandelser-med-bilder",
      "variations": [
        "raknehandelser-addition",
        "raknehandelser-subtraktion",
        "raknehandelser-till-10",
        "trana-raknehandelser",
        "raknehandelser-med-djur"
      ]
    },
    {
      "base": "uppstallning-utan-vaxling",
      "variations": [
        "addition-utan-vaxling",
        "subtraktion-utan-vaxling",
        "tresiffrig-uppstallning-utan-vaxling",
        "tresiffrig-addition-utan-vaxling",
        "uppstallning-repetition"
      ]
    },
    {
      "base": "volym-och-vikt",
      "variations": [
        "las-av-matkannan",
        "las-av-vagen-i-gram",
        "las-av-skalan-sma-steg",
        "matkannor-till-2000-ml",
        "volym-och-vikt-med-djur"
      ]
    },
    {
      "base": "symmetri-spegelbilder",
      "variations": [
        "latt-symmetri-i-rutnat",
        "svar-symmetri-i-rutnat",
        "spegelbilder-hjarta-och-fjaril",
        "spegelbilder-hus-och-krona",
        "spegla-under-linjen"
      ]
    },
    {
      "base": "lasforstaelse-korta-texter",
      "variations": [
        "lasforstaelse-simskolan",
        "lasforstaelse-bullar-hos-mormor",
        "lasforstaelse-biblioteket",
        "lasforstaelse-snolyktan",
        "lasforstaelse-farjan"
      ]
    },
    {
      "base": "uppstallning-med-vaxling",
      "variations": [
        "addition-med-vaxling",
        "subtraktion-med-vaxling",
        "tresiffrig-addition-med-vaxling",
        "subtraktion-over-noll",
        "blandad-vaxling-uppstallning"
      ]
    },
    {
      "base": "multiplikationstabeller",
      "variations": [
        "2ans-tabell",
        "5ans-tabell",
        "10ans-tabell",
        "3ans-tabell",
        "4ans-tabell"
      ]
    },
    {
      "base": "spara-sma-bokstaver",
      "variations": [
        "spara-sma-bokstaver-g-till-l",
        "spara-sma-bokstaver-m-till-r",
        "spara-sma-bokstaver-s-till-z",
        "spara-a-ring-a-prickar-o",
        "mina-forsta-sma-bokstaver"
      ]
    },
    {
      "base": "spara-och-skriv-ord-djur",
      "variations": []
    },
    {
      "base": "prick-till-prick-1-20",
      "variations": []
    },
    {
      "base": "rita-av-i-rutnatet",
      "variations": []
    },
    {
      "base": "singular-och-plural-frukter",
      "variations": []
    },
    {
      "base": "en-eller-ett-frukter",
      "variations": []
    },
    {
      "base": "las-och-mala-frukter",
      "variations": []
    },
    {
      "base": "dagens-tal-ak-1",
      "variations": []
    },
    {
      "base": "skriv-ordet-till-bilden-frukter",
      "variations": []
    },
    {
      "base": "alfabetisk-ordning-djur",
      "variations": []
    },
    {
      "base": "talpyramider-till-20",
      "variations": []
    },
    {
      "base": "dubbelt-och-halften-frukter",
      "variations": []
    },
    {
      "base": "las-av-tallinjen-0-20",
      "variations": []
    },
    {
      "base": "ordna-orden-till-en-mening-djur",
      "variations": []
    },
    {
      "base": "stor-bokstav-och-skiljetecken-fordon",
      "variations": []
    },
    {
      "base": "ordklasser-substantiv-verb-adjektiv",
      "variations": []
    },
    {
      "base": "rakna-med-pengar-kronor-frukter",
      "variations": []
    },
    {
      "base": "las-kalendern-ak-2",
      "variations": []
    },
    {
      "base": "skriv-till-bilden-fordon",
      "variations": []
    },
    {
      "base": "koordinater-i-rutnat-mala-rutorna",
      "variations": []
    },
    {
      "base": "raknehandelser-multiplikation-och-division",
      "variations": []
    }
  ],
  "da": [
    {
      "base": "skriveforberedende-oevelser",
      "variations": [
        "lige-linjer-og-zigzag",
        "boelger-og-buer",
        "sloejfer-og-spiraler",
        "svaere-skrivemoenstre",
        "blandede-skriveoevelser"
      ]
    },
    {
      "base": "skriv-tallene-0-9",
      "variations": [
        "skriv-tallene-0-4",
        "skriv-tallene-5-9",
        "spor-og-skriv-tallene-selv",
        "skriv-tallene-1-10",
        "skriv-tallene-11-20"
      ]
    },
    {
      "base": "skriv-store-bogstaver",
      "variations": [
        "skriv-bogstaverne-g-til-l",
        "skriv-bogstaverne-m-til-r",
        "skriv-bogstaverne-s-til-z",
        "skriv-ae-oe-aa",
        "mine-foerste-bogstaver-abcd"
      ]
    },
    {
      "base": "hyppige-ord-laes-og-skriv",
      "variations": [
        "hyppige-ord-saet-2",
        "hyppige-ord-saet-3",
        "hyppige-ord-saet-4",
        "hyppige-ord-saet-5",
        "hyppige-ord-saet-6"
      ]
    },
    {
      "base": "klip-og-klistre-sortering",
      "variations": [
        "klip-og-klistre-koeretoejer",
        "klip-og-klistre-frugter",
        "klip-og-klistre-legetoej",
        "klip-og-sorter-i-to-grupper"
      ]
    },
    {
      "base": "regn-og-farvelaeg",
      "variations": [
        "farvelaeg-efter-figurkode",
        "farvelaeg-efter-tal",
        "farvelaeg-med-minusstykker",
        "farvelaeg-med-plus-og-minus",
        "farvelaeg-med-plus-til-20"
      ]
    },
    {
      "base": "labyrint-opgaveark",
      "variations": [
        "nem-labyrint-frugter",
        "svaer-labyrint-koeretoejer",
        "kaempelabyrint-legetoej",
        "labyrint-med-dyr",
        "labyrint-med-frugter"
      ]
    },
    {
      "base": "tiervenner-opgaveark",
      "variations": [
        "femvenner-med-taelleprikker",
        "talvenner-op-til-10",
        "tyvevenner-par-der-giver-20",
        "find-det-hele-tal",
        "tiervenner-med-taelleprikker"
      ]
    },
    {
      "base": "hovedregning-op-til-20",
      "variations": [
        "hovedregning-op-til-10",
        "manglende-tal-til-20",
        "plusstykker-op-til-20",
        "minusstykker-op-til-20",
        "manglende-tal-til-10"
      ]
    },
    {
      "base": "talfamilier-opgaveark",
      "variations": [
        "talfamilier-op-til-10",
        "talfamilier-op-til-20",
        "oev-talfamilier-op-til-10",
        "talfamilier-det-midterste-tal",
        "talfamilier-gange-og-division"
      ]
    },
    {
      "base": "tal-og-talord",
      "variations": [
        "talord-op-til-20",
        "talord-hele-tiere-til-100",
        "forbind-tal-og-talord",
        "talord-op-til-50",
        "skriv-talordene"
      ]
    },
    {
      "base": "taelle-moenter-kroner",
      "variations": [
        "taelle-moenter-nem-start",
        "taelle-moenter-alle-moenter",
        "oev-dig-i-at-taelle-penge",
        "taelle-med-de-smaa-moenter",
        "hvilken-pung-har-flest-penge"
      ]
    },
    {
      "base": "tegn-viserne-paa-uret",
      "variations": [
        "tegn-viserne-hele-timer",
        "tegn-viserne-halve-timer",
        "tegn-viserne-kvart-over-og-kvart-i",
        "tegn-viserne-fem-minutter",
        "tegn-viserne-blandede-klokkeslaet"
      ]
    },
    {
      "base": "regnehistorier-med-billeder",
      "variations": [
        "regnehistorier-med-plus",
        "regnehistorier-med-minus",
        "regnehistorier-op-til-10",
        "tre-regnehistorier-paa-en-side",
        "regnehistorier-med-dyr"
      ]
    },
    {
      "base": "plus-og-minus-med-opstilling",
      "variations": [
        "plus-med-tocifrede-tal",
        "minus-med-tocifrede-tal",
        "trecifrede-tal-i-opstilling",
        "plus-med-trecifrede-tal",
        "repetition-opstilling-uden-tierovergang"
      ]
    },
    {
      "base": "maalebaegre-og-vaegte",
      "variations": [
        "aflaes-maalebaegre-i-milliliter",
        "aflaes-vaegte-i-gram",
        "aflaes-skalaer-med-smaa-spring",
        "maalebaegre-op-til-2000-ml",
        "maalebaegre-og-vaegte-med-dyr"
      ]
    },
    {
      "base": "tegn-spejlbilledet",
      "variations": [
        "nem-symmetritegning",
        "svaer-symmetritegning",
        "spejlbilleder-hjerte-og-sommerfugl",
        "spejlbilleder-hus-og-krone",
        "spejling-under-stregen"
      ]
    },
    {
      "base": "laeseforstaaelse-opgaveark",
      "variations": [
        "laeseforstaaelse-elias-paa-stranden",
        "laeseforstaaelse-paa-biblioteket",
        "laeseforstaaelse-kaelkedag",
        "laeseforstaaelse-hos-bageren",
        "laeseforstaaelse-skovturen"
      ]
    },
    {
      "base": "opstilling-med-tierovergang",
      "variations": [
        "plus-med-tierovergang",
        "minus-med-tierovergang",
        "trecifret-plus-med-tierovergang",
        "minus-hen-over-nul",
        "repetition-med-tierovergang"
      ]
    },
    {
      "base": "den-lille-tabel",
      "variations": [
        "2-tabellen",
        "5-tabellen",
        "10-tabellen",
        "3-tabellen",
        "4-tabellen"
      ]
    },
    {
      "base": "sma-bogstaver",
      "variations": [
        "sma-bogstaver-g-til-l",
        "sma-bogstaver-m-til-r",
        "sma-bogstaver-s-til-z",
        "sma-bogstaver-ae-oe-aa",
        "mine-forste-sma-bogstaver"
      ]
    },
    {
      "base": "skriv-ordene-efter-boernehaveklasse",
      "variations": []
    },
    {
      "base": "prik-til-prik-1-20",
      "variations": []
    },
    {
      "base": "tegn-efter-i-kvadratnet",
      "variations": []
    },
    {
      "base": "ental-og-flertal-boernehaveklasse",
      "variations": []
    },
    {
      "base": "en-eller-et-boernehaveklasse",
      "variations": []
    },
    {
      "base": "laes-og-farvelaeg-1-klasse",
      "variations": []
    },
    {
      "base": "dagens-tal-1-klasse",
      "variations": []
    },
    {
      "base": "skriv-ordet-til-billedet-1-klasse",
      "variations": []
    },
    {
      "base": "alfabetisk-raekkefoelge-1-klasse",
      "variations": []
    },
    {
      "base": "talpyramider-1-klasse",
      "variations": []
    },
    {
      "base": "det-dobbelte-og-det-halve-1-klasse",
      "variations": []
    },
    {
      "base": "tallinjen-0-20-1-klasse",
      "variations": []
    },
    {
      "base": "saet-ordene-i-raekkefoelge-1-klasse",
      "variations": []
    },
    {
      "base": "stort-bogstav-og-punktum-2-klasse",
      "variations": []
    },
    {
      "base": "ordklasser-navneord-udsagnsord-tillaegsord",
      "variations": []
    },
    {
      "base": "koebmandsregning-2-klasse",
      "variations": []
    },
    {
      "base": "laes-kalenderen-2-klasse",
      "variations": []
    },
    {
      "base": "skriv-til-billedet-2-klasse",
      "variations": []
    },
    {
      "base": "koordinater-i-kvadratnet-2-klasse",
      "variations": []
    },
    {
      "base": "regnehistorier-gange-og-division-3-klasse",
      "variations": []
    }
  ],
  "no": [
    {
      "base": "skriveforberedende-ovelser",
      "variations": [
        "blyantloyper-rette-linjer-og-sikksakk",
        "blyantloyper-bolger-og-buer",
        "lokker-attetall-og-spiraler",
        "vanskelige-blyantloyper",
        "blyantloyper-repetisjon"
      ]
    },
    {
      "base": "spore-tall-0-til-9",
      "variations": [
        "spore-tallene-0-til-4",
        "spore-tallene-5-til-9",
        "spor-og-skriv-tallene",
        "spore-tallene-1-til-10",
        "spore-tallene-11-til-20"
      ]
    },
    {
      "base": "spore-store-bokstaver",
      "variations": [
        "spore-bokstavene-g-til-l",
        "spore-bokstavene-m-til-r",
        "spore-bokstavene-s-til-z",
        "spore-bokstavene-ae-o-a",
        "mine-forste-store-bokstaver"
      ]
    },
    {
      "base": "hoyfrekvente-ord",
      "variations": [
        "hoyfrekvente-ord-sett-2",
        "hoyfrekvente-ord-sett-3",
        "hoyfrekvente-ord-sett-4",
        "hoyfrekvente-ord-sett-5",
        "hoyfrekvente-ord-sett-6"
      ]
    },
    {
      "base": "klipp-og-lim-sortering",
      "variations": [
        "klipp-og-lim-kjoretoy",
        "klipp-og-lim-frukter",
        "klipp-og-lim-leker",
        "klipp-og-lim-to-grupper"
      ]
    },
    {
      "base": "regn-og-fargelegg",
      "variations": [
        "fargelegg-etter-figurkode",
        "fargelegg-etter-tall",
        "trekk-fra-og-fargelegg",
        "fargelegg-pluss-og-minus",
        "fargelegg-addisjon-til-20"
      ]
    },
    {
      "base": "labyrinter-for-barn",
      "variations": [
        "enkel-labyrint",
        "vanskelig-labyrint",
        "kjempelabyrint",
        "labyrint-med-dyr",
        "labyrint-med-frukter"
      ]
    },
    {
      "base": "tiervenner",
      "variations": [
        "femmervenner",
        "tallvenner-opp-til-10",
        "tallvenner-til-20",
        "tallvenner-finn-det-hele",
        "tiervenner-med-telleprikker"
      ]
    },
    {
      "base": "hoderegning-til-20",
      "variations": [
        "hoderegning-til-10",
        "finn-tallet-som-mangler-til-20",
        "hoderegning-addisjon-til-20",
        "hoderegning-subtraksjon-til-20",
        "finn-tallet-som-mangler-til-10"
      ]
    },
    {
      "base": "regnefamilier",
      "variations": [
        "regnefamilier-til-10",
        "regnefamilier-til-20",
        "regnehus-til-10",
        "regnefamilier-tallet-i-midten",
        "gange-og-delefamilier"
      ]
    },
    {
      "base": "tallord",
      "variations": [
        "tallord-til-20",
        "tallord-tiere-til-100",
        "koble-tall-og-tallord",
        "tallord-til-50",
        "skrive-tallord"
      ]
    },
    {
      "base": "regne-med-penger",
      "variations": [
        "telle-mynter-for-nybegynnere",
        "telle-alle-myntene",
        "ove-pa-a-telle-mynter",
        "telle-enkroner-og-femkroner",
        "hvilken-pung-har-mest-penger"
      ]
    },
    {
      "base": "laere-klokka",
      "variations": [
        "tegne-viserne-hele-timer",
        "tegne-viserne-halv-time",
        "tegne-viserne-kvart-over-og-kvart-pa",
        "tegne-viserne-fem-minutter",
        "tegne-viserne-blandede-klokkeslett"
      ]
    },
    {
      "base": "regnefortellinger",
      "variations": [
        "regnefortellinger-addisjon",
        "regnefortellinger-subtraksjon",
        "regnefortellinger-til-10",
        "tre-regnefortellinger",
        "regnefortellinger-med-dyr"
      ]
    },
    {
      "base": "oppstilt-addisjon-og-subtraksjon",
      "variations": [
        "oppstilt-addisjon-tosifret",
        "oppstilt-subtraksjon-tosifret",
        "tresifret-oppstilling-blandet",
        "tresifret-oppstilt-addisjon",
        "oppstilling-blandet-repetisjon"
      ]
    },
    {
      "base": "male-liter-og-gram",
      "variations": [
        "lese-av-litermal",
        "lese-av-skalvekt-i-gram",
        "lese-skala-med-sma-steg",
        "litermal-til-2000-ml",
        "male-liter-og-gram-med-dyr"
      ]
    },
    {
      "base": "symmetri-oppgaver",
      "variations": [
        "enkel-symmetri",
        "vanskelig-symmetri",
        "speilbilder-hjerte-og-sommerfugl",
        "speilbilder-hus-og-krone",
        "speiling-under-streken"
      ]
    },
    {
      "base": "leseforstaelse",
      "variations": [
        "leseforstaelse-mia-mater-fuglene",
        "leseforstaelse-akedag-i-bakken",
        "leseforstaelse-jakob-baker-boller",
        "leseforstaelse-pa-biblioteket",
        "leseforstaelse-fisketur-ved-fjellvannet"
      ]
    },
    {
      "base": "regning-med-tierovergang",
      "variations": [
        "addisjon-med-tierovergang",
        "subtraksjon-med-veksling",
        "tresifret-addisjon-med-tierovergang",
        "subtraksjon-med-veksling-over-null",
        "tierovergang-blandet-oving"
      ]
    },
    {
      "base": "gangetabellen",
      "variations": [
        "2-gangen",
        "5-gangen",
        "10-gangen",
        "3-gangen",
        "4-gangen"
      ]
    },
    {
      "base": "sma-bokstaver",
      "variations": [
        "sma-bokstaver-g-til-l",
        "sma-bokstaver-m-til-r",
        "sma-bokstaver-s-til-z",
        "sma-bokstaver-ae-oe-aa",
        "mine-forste-sma-bokstaver"
      ]
    },
    {
      "base": "spor-og-skriv-ordene-dyr",
      "variations": []
    },
    {
      "base": "prikk-til-prikk-1-20",
      "variations": []
    },
    {
      "base": "tegn-etter-i-rutenett",
      "variations": []
    },
    {
      "base": "entall-og-flertall-frukt",
      "variations": []
    },
    {
      "base": "en-eller-et-frukt",
      "variations": []
    },
    {
      "base": "les-og-fargelegg-frukt",
      "variations": []
    },
    {
      "base": "dagens-tall-2-trinn",
      "variations": []
    },
    {
      "base": "skriv-ordet-til-bildet-frukt",
      "variations": []
    },
    {
      "base": "alfabetisk-rekkefolge-dyr",
      "variations": []
    },
    {
      "base": "tallpyramider-2-trinn",
      "variations": []
    },
    {
      "base": "det-dobbelte-og-halvparten",
      "variations": []
    },
    {
      "base": "les-av-tallinjen-0-20",
      "variations": []
    },
    {
      "base": "sett-ordene-i-riktig-rekkefolge",
      "variations": []
    },
    {
      "base": "stor-bokstav-og-punktum",
      "variations": []
    },
    {
      "base": "substantiv-verb-og-adjektiv",
      "variations": []
    },
    {
      "base": "regne-med-penger-3-trinn",
      "variations": []
    },
    {
      "base": "les-kalenderen",
      "variations": []
    },
    {
      "base": "skriv-til-bildet-kjoretoy",
      "variations": []
    },
    {
      "base": "koordinater-i-rutenett",
      "variations": []
    },
    {
      "base": "regnefortellinger-gange-og-dele",
      "variations": []
    }
  ],
  "fi": [
    {
      "base": "kynaharjoitukset",
      "variations": [
        "kynaharjoitukset-siksakit-ja-sakarat",
        "kynaharjoitukset-aallot-ja-kaaret",
        "kynaharjoitukset-silmukat-ja-spiraalit",
        "vaativat-kynaharjoitukset",
        "kynaharjoitusten-kertaus"
      ]
    },
    {
      "base": "numeroiden-kirjoitusharjoitus-0-9",
      "variations": [
        "numeroiden-kirjoitusharjoitus-0-4",
        "numeroiden-kirjoitusharjoitus-5-9",
        "jaljenna-ja-kirjoita-numerot",
        "lukujen-kirjoitusharjoitus-1-10",
        "lukujen-kirjoitusharjoitus-11-20"
      ]
    },
    {
      "base": "isojen-kirjainten-jaljentaminen",
      "variations": [
        "kirjainten-kirjoitusharjoitus-g-l",
        "kirjainten-kirjoitusharjoitus-m-r",
        "kirjainten-kirjoitusharjoitus-s-o",
        "aakkoset-a-ja-o",
        "ensimmaiset-kirjaimet-a-b-c-d"
      ]
    },
    {
      "base": "yleisten-sanojen-harjoittelu",
      "variations": [
        "yleiset-sanat-sarja-2",
        "yleiset-sanat-sarja-3",
        "yleiset-sanat-sarja-4",
        "yleiset-sanat-sarja-5",
        "yleiset-sanat-sarja-6"
      ]
    },
    {
      "base": "leikkaa-lajittele-ja-liimaa",
      "variations": [
        "leikkaa-lajittele-ja-liimaa-ajoneuvot",
        "leikkaa-lajittele-ja-liimaa-hedelmat",
        "leikkaa-lajittele-ja-liimaa-lelut",
        "leikkaa-ja-liimaa-kahteen-ryhmaan"
      ]
    },
    {
      "base": "varita-koodin-mukaan",
      "variations": [
        "varita-muotokoodin-mukaan",
        "varita-numeroiden-mukaan",
        "vahenna-ja-varita",
        "laske-ja-varita-plus-ja-miinus",
        "varita-summien-mukaan-11-20"
      ]
    },
    {
      "base": "labyrintti-tehtavat",
      "variations": [
        "helppo-labyrintti",
        "vaikea-labyrintti",
        "jattilabyrintti",
        "labyrintti-elaimet",
        "labyrintti-hedelmat"
      ]
    },
    {
      "base": "kymppiparit",
      "variations": [
        "viisparit-hajotelmat-viiteen",
        "lukujen-hajotelmat-5-10",
        "kaksikymppiparit-hajotelmat-20",
        "hajotelmat-puuttuva-kokonaisuus",
        "kymppiparit-pisteiden-avulla"
      ]
    },
    {
      "base": "paassalaskut-0-20",
      "variations": [
        "paassalaskut-0-10",
        "puuttuvan-luvun-laskut-0-20",
        "yhteenlaskut-0-20-paassa",
        "vahennyslaskut-0-20-paassa",
        "puuttuvan-luvun-laskut-0-10"
      ]
    },
    {
      "base": "laskuperheet",
      "variations": [
        "laskuperheet-0-10",
        "laskuperheet-0-20",
        "laskuperhetalot-harjoitus-0-10",
        "laskuperheet-puuttuva-luku",
        "kerto-ja-jakolaskuperheet"
      ]
    },
    {
      "base": "lukusanat-tehtavat",
      "variations": [
        "lukusanat-0-20",
        "lukusanat-tasakymmenet",
        "yhdista-luku-ja-lukusana",
        "lukusanat-0-50",
        "kirjoita-lukusanat"
      ]
    },
    {
      "base": "rahalaskut-eurot-ja-sentit",
      "variations": [
        "rahalaskujen-ensiaskeleet",
        "rahalaskut-kaikki-kolikot",
        "kolikkolaskujen-harjoitus",
        "rahalaskut-5-ja-10-sentin-kolikot",
        "kummassa-kukkarossa-on-enemman"
      ]
    },
    {
      "base": "piirra-kellon-viisarit",
      "variations": [
        "piirra-viisarit-tasatunnit",
        "piirra-viisarit-puolitunnit",
        "piirra-viisarit-vartit",
        "piirra-viisarit-viiden-minuutin-tarkkuus",
        "piirra-viisarit-kellonaikojen-kertaus"
      ]
    },
    {
      "base": "sanalliset-tehtavat",
      "variations": [
        "sanalliset-yhteenlaskutehtavat",
        "sanalliset-vahennyslaskutehtavat",
        "sanalliset-tehtavat-0-10",
        "sanallisten-tehtavien-harjoitus",
        "sanalliset-tehtavat-elaimet"
      ]
    },
    {
      "base": "allekkain-laskeminen-ilman-kymmenylitysta",
      "variations": [
        "yhteenlasku-allekkain-2-numeroiset",
        "vahennyslasku-allekkain-2-numeroiset",
        "allekkain-laskeminen-3-numeroiset",
        "yhteenlasku-allekkain-3-numeroiset",
        "allekkain-laskemisen-kertaus"
      ]
    },
    {
      "base": "tilavuus-ja-massa-tehtavat",
      "variations": [
        "lue-mitta-astian-millilitrat",
        "lue-vaaka-grammat",
        "mitta-asteikot-50-ml-valein",
        "isot-mitta-astiat-2000-ml",
        "tilavuus-ja-massa-elaimet"
      ]
    },
    {
      "base": "taydenna-peilikuva",
      "variations": [
        "helpot-peilikuvat",
        "vaikeat-peilikuvat",
        "peilikuvat-sydan-ja-perhonen",
        "peilikuvat-talo-ja-kruunu",
        "peilikuva-vaakaviivan-alle"
      ]
    },
    {
      "base": "luetun-ymmartaminen",
      "variations": [
        "luetun-ymmartaminen-ensilumi",
        "luetun-ymmartaminen-kirjastoauto",
        "luetun-ymmartaminen-uimahallissa",
        "luetun-ymmartaminen-maatilan-retki",
        "luetun-ymmartaminen-yo-mokilla"
      ]
    },
    {
      "base": "allekkain-laskeminen-kymmenylityksella",
      "variations": [
        "yhteenlasku-allekkain-muistinumerolla",
        "vahennyslasku-allekkain-lainaamalla",
        "3-numeroinen-yhteenlasku-allekkain",
        "vahennyslasku-nollien-yli",
        "kymmenylityksen-kertaus"
      ]
    },
    {
      "base": "kertotauluharjoitukset",
      "variations": [
        "2n-kertotaulu",
        "5n-kertotaulu",
        "10n-kertotaulu",
        "3n-kertotaulu",
        "4n-kertotaulu"
      ]
    },
    {
      "base": "pienten-kirjainten-kirjoittaminen",
      "variations": [
        "pienten-kirjainten-kirjoittaminen-g-l",
        "pienten-kirjainten-kirjoittaminen-m-r",
        "pienten-kirjainten-kirjoittaminen-s-a",
        "pienet-aakkoset-a-o",
        "ensimmaiset-pienet-kirjaimet"
      ]
    },
    {
      "base": "sanojen-jaljentaminen-esikoulu",
      "variations": []
    },
    {
      "base": "yhdista-pisteet-1-20",
      "variations": []
    },
    {
      "base": "piirra-mallin-mukaan-ruudukkoon",
      "variations": []
    },
    {
      "base": "yksikko-ja-monikko-esikoulu",
      "variations": []
    },
    {
      "base": "yksi-vai-monta",
      "variations": []
    },
    {
      "base": "lue-ja-varita-1-luokka",
      "variations": []
    },
    {
      "base": "paivan-luku-1-luokka",
      "variations": []
    },
    {
      "base": "kirjoita-kuvan-sana",
      "variations": []
    },
    {
      "base": "aakkosjarjestys-1-luokka",
      "variations": []
    },
    {
      "base": "lukupyramidi-20-asti",
      "variations": []
    },
    {
      "base": "tuplaa-ja-puolita",
      "variations": []
    },
    {
      "base": "lukusuora-0-20-mika-luku",
      "variations": []
    },
    {
      "base": "jarjesta-sanat-lauseeksi",
      "variations": []
    },
    {
      "base": "iso-alkukirjain-ja-piste",
      "variations": []
    },
    {
      "base": "substantiivi-verbi-vai-adjektiivi",
      "variations": []
    },
    {
      "base": "rahalaskut-kaupassa",
      "variations": []
    },
    {
      "base": "kalenterin-lukeminen",
      "variations": []
    },
    {
      "base": "kirjoita-kuvasta-ajoneuvot",
      "variations": []
    },
    {
      "base": "koordinaatit-ruudukossa",
      "variations": []
    },
    {
      "base": "sanalliset-kerto-ja-jakolaskut",
      "variations": []
    }
  ]
};
export const MORE_TYPE_GROUPS: Record<string, NewWorksheetGroup[]> = {
  "en": [
    {
      "base": "arrays-multiplication-grade-2",
      "variations": [
        "arrays-multiplication-grade-3"
      ]
    },
    {
      "base": "fractions-grade-2",
      "variations": [
        "fractions-grade-3"
      ]
    },
    {
      "base": "geometry-kindergarten",
      "variations": [
        "geometry-grade-2",
        "geometry-grade-3"
      ]
    },
    {
      "base": "graphing-data-grade-1",
      "variations": [
        "graphing-data-grade-2",
        "graphing-data-grade-3"
      ]
    },
    {
      "base": "number-charts-kindergarten",
      "variations": [
        "number-charts-grade-1",
        "number-charts-grade-2",
        "number-charts-grade-3"
      ]
    },
    {
      "base": "measurement-kindergarten",
      "variations": [
        "measurement-grade-1",
        "measurement-grade-2",
        "measurement-grade-3"
      ]
    },
    {
      "base": "telling-time-grade-1",
      "variations": [
        "telling-time-grade-2",
        "telling-time-grade-3"
      ]
    }
  ],
  "de": [
    {
      "base": "malfeld-einmaleins-klasse-2",
      "variations": [
        "einmaleins-malnehmen-teilen-klasse-3"
      ]
    },
    {
      "base": "bruchteile-klasse-2-anteile",
      "variations": [
        "brueche-klasse-3-zahlenstrahl"
      ]
    },
    {
      "base": "formen-vorschule-seiten-ecken",
      "variations": [
        "geometrie-klasse-2-koerper-symmetrie",
        "geometrie-klasse-3-vierecke-umfang"
      ]
    },
    {
      "base": "diagramme-klasse-1",
      "variations": [
        "diagramme-klasse-2",
        "diagramme-klasse-3"
      ]
    },
    {
      "base": "zahlenfolgen-vorschule",
      "variations": [
        "hundertertafel-klasse-1",
        "zahlenfolgen-klasse-2",
        "zahlenmuster-klasse-3"
      ]
    },
    {
      "base": "gewicht-vergleichen-vorschule",
      "variations": [
        "laenge-messen-klasse-1",
        "laenge-messen-lineal-klasse-2",
        "temperatur-volumen-klasse-3"
      ]
    },
    {
      "base": "uhrzeit-klasse-1-uhr-lesen",
      "variations": [
        "uhrzeit-klasse-2-fuenf-minuten",
        "uhrzeit-klasse-3-zeitspannen"
      ]
    }
  ],
  "es": [
    {
      "base": "arreglos-multiplicacion-segundo-grado",
      "variations": [
        "tablas-multiplicar-arreglos-tercer-grado"
      ]
    },
    {
      "base": "fracciones-partes-iguales-segundo-grado",
      "variations": [
        "fracciones-tercer-grado"
      ]
    },
    {
      "base": "figuras-geometricas-preescolar",
      "variations": [
        "cuerpos-geometricos-segundo-grado",
        "geometria-tercer-grado"
      ]
    },
    {
      "base": "graficas-pictogramas-primer-grado",
      "variations": [
        "graficas-de-barras-segundo-grado",
        "graficas-de-barras-con-escala-tercer-grado"
      ]
    },
    {
      "base": "numeros-que-faltan-preescolar",
      "variations": [
        "tabla-del-100-primer-grado",
        "contar-de-3-en-3-segundo-grado",
        "sucesiones-y-maquinas-de-numeros-tercer-grado"
      ]
    },
    {
      "base": "comparar-peso-pesado-ligero-preescolar",
      "variations": [
        "medir-longitud-cubos-primer-grado",
        "medir-comparar-longitudes-segundo-grado",
        "temperatura-volumen-comparar-tercer-grado"
      ]
    },
    {
      "base": "leer-el-reloj-primer-grado",
      "variations": [
        "la-hora-segundo-grado",
        "decir-la-hora-tercer-grado"
      ]
    }
  ],
  "fr": [
    {
      "base": "multiplication-en-reseaux-ce1",
      "variations": [
        "tables-de-multiplication-ce2-reseaux"
      ]
    },
    {
      "base": "fractions-parts-egales-ce1",
      "variations": [
        "fractions-ce2"
      ]
    },
    {
      "base": "geometrie-figures-maternelle",
      "variations": [
        "geometrie-solides-ce1",
        "geometrie-ce2"
      ]
    },
    {
      "base": "lire-des-graphiques-cp",
      "variations": [
        "diagrammes-en-barres-ce1",
        "graphiques-a-echelle-ce2"
      ]
    },
    {
      "base": "tableau-des-nombres-maternelle",
      "variations": [
        "tableau-des-nombres-cp",
        "tableau-des-nombres-ce1",
        "suites-numeriques-ce2"
      ]
    },
    {
      "base": "comparer-la-masse-maternelle-lourd-ou-leger",
      "variations": [
        "mesurer-les-longueurs-cp-cubes",
        "mesurer-comparer-longueurs-ce1-regle",
        "temperature-volume-ce2-chaud-froid"
      ]
    },
    {
      "base": "lire-l-heure-cp",
      "variations": [
        "lire-l-heure-ce1",
        "lire-l-heure-ce2"
      ]
    }
  ],
  "pt": [
    {
      "base": "disposicao-retangular-2-ano",
      "variations": [
        "tabuada-disposicao-retangular-3-ano"
      ]
    },
    {
      "base": "fracoes-partes-iguais-2-ano",
      "variations": [
        "fracoes-equivalentes-3-ano"
      ]
    },
    {
      "base": "formas-geometricas-educacao-infantil",
      "variations": [
        "solidos-geometricos-2-ano",
        "quadrilateros-perimetro-area-3-ano"
      ]
    },
    {
      "base": "atividades-graficos-1-ano",
      "variations": [
        "atividades-graficos-2-ano",
        "atividades-graficos-3-ano"
      ]
    },
    {
      "base": "atividades-quadro-numerico-educacao-infantil",
      "variations": [
        "atividades-quadro-numerico-1-ano",
        "atividades-quadro-numerico-2-ano",
        "atividades-quadro-numerico-3-ano"
      ]
    },
    {
      "base": "comparar-peso-educacao-infantil",
      "variations": [
        "medir-comprimento-1-ano",
        "medir-comprimento-regua-2-ano",
        "temperatura-volume-3-ano"
      ]
    },
    {
      "base": "ver-as-horas-1-ano",
      "variations": [
        "que-horas-sao-2-ano",
        "leitura-de-horas-3-ano"
      ]
    }
  ],
  "it": [
    {
      "base": "schede-schieramenti-moltiplicazione-classe-seconda",
      "variations": [
        "schede-tabelline-classe-terza"
      ]
    },
    {
      "base": "frazioni-parti-uguali-classe-seconda",
      "variations": [
        "frazioni-classe-terza"
      ]
    },
    {
      "base": "forme-geometriche-infanzia-lati-angoli",
      "variations": [
        "geometria-solidi-classe-seconda",
        "geometria-classe-terza-perimetro-area"
      ]
    },
    {
      "base": "grafici-classe-prima",
      "variations": [
        "grafici-classe-seconda",
        "grafici-in-scala-classe-terza"
      ]
    },
    {
      "base": "tabella-dei-numeri-infanzia",
      "variations": [
        "tabella-dei-numeri-classe-prima",
        "tabella-dei-numeri-classe-seconda",
        "successioni-numeriche-classe-terza"
      ]
    },
    {
      "base": "schede-pesante-leggero-infanzia",
      "variations": [
        "schede-misurare-lunghezze-classe-prima",
        "schede-misurare-righello-classe-seconda",
        "schede-temperatura-volume-classe-terza"
      ]
    },
    {
      "base": "leggere-l-ora-classe-prima",
      "variations": [
        "leggere-l-ora-classe-seconda",
        "leggere-l-ora-classe-terza"
      ]
    }
  ],
  "nl": [
    {
      "base": "keersommen-met-roosters-groep-4",
      "variations": [
        "tafels-groep-5"
      ]
    },
    {
      "base": "gelijke-delen-groep-4",
      "variations": [
        "breuken-groep-5"
      ]
    },
    {
      "base": "vormen-kleuters",
      "variations": [
        "meetkunde-groep-4",
        "meetkunde-groep-5"
      ]
    },
    {
      "base": "grafieken-lezen-groep-3",
      "variations": [
        "grafieken-groep-4",
        "grafieken-met-schaal-groep-5"
      ]
    },
    {
      "base": "getallen-invullen-kleuters",
      "variations": [
        "honderdveld-groep-3",
        "sprongen-tellen-groep-4",
        "getalpatronen-groep-5"
      ]
    },
    {
      "base": "zwaar-of-licht-kleuters",
      "variations": [
        "lengte-meten-groep-3",
        "meten-met-liniaal-groep-4",
        "temperatuur-en-inhoud-groep-5"
      ]
    },
    {
      "base": "klokkijken-groep-3",
      "variations": [
        "klokkijken-groep-4",
        "klokkijken-groep-5"
      ]
    }
  ],
  "sv": [
    {
      "base": "rader-och-kolumner-lika-grupper-ak-2",
      "variations": [
        "multiplikationstabellen-rader-kolumner-ak-3"
      ]
    },
    {
      "base": "brak-lika-delar-ak-2",
      "variations": [
        "brak-tallinjen-ak-3"
      ]
    },
    {
      "base": "geometri-former-forskola",
      "variations": [
        "geometri-kroppar-ak-2",
        "geometri-omkrets-area-ak-3"
      ]
    },
    {
      "base": "diagram-ak-1",
      "variations": [
        "diagram-ak-2",
        "diagram-ak-3"
      ]
    },
    {
      "base": "tal-som-saknas-forskola",
      "variations": [
        "hundraruta-ak-1",
        "hundraruta-ak-2",
        "talfoljder-ak-3"
      ]
    },
    {
      "base": "jamfora-vikt-tung-eller-latt-forskola",
      "variations": [
        "mata-langd-med-enheter-ak-1",
        "mata-med-linjal-jamfora-langder-ak-2",
        "temperatur-och-volym-jamfora-ak-3"
      ]
    },
    {
      "base": "klockan-arbetsblad-ak-1",
      "variations": [
        "klockan-fem-minuter-ak-2",
        "klockan-tidsskillnad-ak-3"
      ]
    }
  ],
  "da": [
    {
      "base": "raekker-og-soejler-2-klasse",
      "variations": [
        "gangetabel-3-klasse"
      ]
    },
    {
      "base": "broeker-lige-dele-2-klasse",
      "variations": [
        "broeker-tallinje-3-klasse"
      ]
    },
    {
      "base": "geometri-former-boernehaveklasse",
      "variations": [
        "geometri-rumlige-figurer-2-klasse",
        "geometri-omkreds-areal-3-klasse"
      ]
    },
    {
      "base": "diagrammer-1-klasse",
      "variations": [
        "diagrammer-2-klasse",
        "diagrammer-3-klasse"
      ]
    },
    {
      "base": "tal-der-mangler-boernehaveklasse",
      "variations": [
        "hundredfelt-1-klasse",
        "talfoelger-2-klasse",
        "talfoelger-3-klasse"
      ]
    },
    {
      "base": "maaling-tung-eller-let-boernehaveklasse",
      "variations": [
        "maale-laengde-med-enheder-1-klasse",
        "maale-med-lineal-2-klasse",
        "temperatur-og-rumfang-3-klasse"
      ]
    },
    {
      "base": "klokken-arbejdsark-1-klasse",
      "variations": [
        "klokken-fem-minutter-2-klasse",
        "klokken-paa-minuttet-3-klasse"
      ]
    }
  ],
  "no": [
    {
      "base": "rader-og-kolonner-3-trinn",
      "variations": [
        "gangetabellen-rader-kolonner-4-trinn"
      ]
    },
    {
      "base": "brok-like-deler-3-trinn",
      "variations": [
        "brok-tallinje-4-trinn"
      ]
    },
    {
      "base": "geometri-former-1-trinn",
      "variations": [
        "geometri-romfigurer-3-trinn",
        "geometri-omkrets-areal-4-trinn"
      ]
    },
    {
      "base": "diagram-2-trinn",
      "variations": [
        "diagram-3-trinn",
        "diagram-4-trinn"
      ]
    },
    {
      "base": "tall-som-mangler-1-trinn",
      "variations": [
        "hundrerutenett-2-trinn",
        "tallfolger-3-trinn",
        "tallmaskiner-4-trinn"
      ]
    },
    {
      "base": "maling-tung-eller-lett-1-trinn",
      "variations": [
        "maling-lengde-med-enheter-2-trinn",
        "maling-med-linjal-3-trinn",
        "maling-temperatur-og-volum-4-trinn"
      ]
    },
    {
      "base": "klokka-arbeidsark-2-trinn",
      "variations": [
        "klokka-fem-minutter-3-trinn",
        "klokka-tidsdifferanse-4-trinn"
      ]
    }
  ],
  "fi": [
    {
      "base": "rivit-ja-sarakkeet-2-luokka",
      "variations": [
        "kertotaulu-rivit-sarakkeet-3-luokka"
      ]
    },
    {
      "base": "murtoluvut-yhta-suuret-osat-2-luokka",
      "variations": [
        "murtoluvut-lukusuora-3-luokka"
      ]
    },
    {
      "base": "geometria-muodot-esikoulu",
      "variations": [
        "geometria-kappaleet-2-luokka",
        "geometria-piiri-ja-pinta-ala-3-luokka"
      ]
    },
    {
      "base": "diagrammit-tehtavat-1-luokka",
      "variations": [
        "diagrammit-tehtavat-2-luokka",
        "diagrammit-tehtavat-3-luokka"
      ]
    },
    {
      "base": "puuttuvat-luvut-esikoulu",
      "variations": [
        "lukutaulu-100-1-luokka",
        "lukujonot-2-luokka",
        "lukujonot-lukukoneet-3-luokka"
      ]
    },
    {
      "base": "vertaa-painoa-raskas-vai-kevyt-esikoulu",
      "variations": [
        "mittaa-pituutta-yksikoilla-1-luokka",
        "mittaa-viivaimella-2-luokka",
        "lampotila-ja-tilavuus-3-luokka"
      ]
    },
    {
      "base": "kellonajat-tehtavat-1-luokka",
      "variations": [
        "kellonajat-viisi-minuuttia-2-luokka",
        "kellonajat-aikavali-3-luokka"
      ]
    }
  ]
};
