import { registerThemeContent } from '../registry';
import type { EnrichedThemeContent } from '../types';

const content: EnrichedThemeContent = {
  // -- SEO fields --
  name: 'Følelser',
  title: 'Gratis følelsesarbejdsark til børn | LessonCraftStudio',
  description: 'Lav printbare følelsesarbejdsark til børn. Identifikation af følelser, ansigtsudtryk, empati og selvregulering. Matematik, læsning og puslespil til førskole og op til 3. klasse.',
  keywords: 'følelsesarbejdsark, følelsesaktiviteter for børn, socialt-emotionel læring arbejdsark, ansigtsudtryk aktiviteter, printbare følelsesarbejdsark',
  heading: 'Gratis følelsesarbejdsark til børn',

  // -- Rich narrative content --
  intro: 'Følelser er den usynlige motor bag enhver social interaktion, ethvert læringsøjeblik og enhver beslutning, et barn træffer i løbet af dagen. Et barn, der kan navngive, hvad det føler, er bedre rustet til at håndtere det, kommunikere det og forstå det hos andre. Følelsestematiske arbejdsark bringer denne afgørende livsfærdighed ind i klasselokalet og hjemmet ved at give børn en visuel, struktureret måde at udforske hele spektret af menneskelige følelser på. Vores printbare følelsesarbejdsark har udtryksfyxlde ansigtsillustrationee, der viser glæde, tristhed, vrede, overraskelse, frygt, afsky og snesevis af mere nuancerede følelser som frustration, begejstring, forlegenhed og stolthed. Matematikaktiviteter bruger følelsestematiske tælleenheder, der beder børn om at tælle glade ansigter, sammenligne grupper af triste og overraskede udtryk eller lægge antallet af rolige figurer sammen med antallet af begejstrede. Læse- og skrivearbejdsark introducerer følelsesordforråd, der rækker langt ud over glad og ked af det, og underviser i ord som ængstelig, taknemmelig, skuffet og selvsikker, der giver børn præcision i at beskrive deres indre verden. Puslespil og sorteringsaktiviteter beder børn om at matche ansigtsudtryk med situationer, identificere hvilken følelse der ikke hører til i en gruppe eller arrangere følelser på et spektrum fra mildest til stærkest. Den pædagogiske kraft i følelsesarbejdsark ligger i deres dobbelte formål: de opbygger faglige færdigheder, mens de samtidig udvikler social-emotionel kompetence. Et barn, der løser en ordsøgning med følelsesord, øver bogstavgenkendelse og visuel scanning, mens det også udvider sit emotionelle ordforråd. En sorteringsaktivitet, der grupperer positive og negative følelser, underviser i kategoriseringsevner sideløbende med selvbevidsthed. I den danske folkeskole, hvor trivsel og socialt-emotionel læring er integreret i Fælles Mål på tværs af alle fag, giver disse arbejdsark konkrete øvelsesmaterialer, der forstærker klassediskussioner, mindfulness-øvelser og konfliktløsningsstrategier. For lærere, der implementerer socialt-emotionelle læringsprogrammer, leverer disse arbejdsark praktisk materiale, der understøtter de daglige samtalecirkler og trivselsrutiner. Forældre vil finde følelsesarbejdsark særligt værdifulde i udfordrende udviklingsperioder, hvor børn kæmper med at udtrykke store følelser med ord i stedet for handlinger. Hvert arbejdsark er en samtalestarter om, hvordan følelser ser ud, hvordan de forandrer sig, og hvad vi kan gøre, når vi oplever dem.',

  educationalOverview: 'Følelsestematiske arbejdsark leverer usædvanligt kraftfulde pædagogiske resultater, fordi de befinder sig i skæringspunktet mellem faglig læring og socialt-emotionel udvikling, to domæner som forskning konsekvent viser er dybt forbundne. Børn, der kan identificere og regulere deres følelser, demonstrerer stærkere faglige præstationer, bedre kammeratskabsrelationer og mere robuste læringsadfærd. Emotionel læsefærdighed er evnen til at genkende, navngive og forstå følelser hos sig selv og andre, og arbejdsark giver et trygt, struktureret rum til at øve denne færdighed systematisk. Når elever sorterer ansigtsudtryk efter følelse, udøver de de samme klassifikationsevner, der bruges i naturfag og matematik, mens de opbygger empati og social kognition. Matchopgaver, der parrer følelser med scenarier, udvikler perspektivtagning, en kognitiv færdighed der understøtter både læseforståelse og social problemløsning. Ordforrådsdimensionen er særligt kraftfuld: forskning viser, at børn der kender flere følelsesord, oplever følelser med større nuance og håndterer dem mere effektivt. At gå fra et to-ords ordforråd bestående af glad og ked af det til en rig ordliste med lettet, overvældet, håbefuld og jaloux transformerer et barns evne til at kommunikere sine behov og forstå andre. Finmotoriske færdigheder udvikles gennem farvelægning af udtryksfyldte ansigter, sporring af følelsesord og tegning af ansigtstræk, der matcher specifikke følelser. For undervisning i overensstemmelse med Fælles Mål kobler følelsesarbejdsark sig til sundhedsundervisningsmål om mental trivsel, danskfaglige mål om ordforråd og karakteranalyse, samt mål for fællesskab og ansvarlig beslutningstagning.',

  parentGuide: 'Følelsesarbejdsark skaber naturlige broer til nogle af de vigtigste samtaler, du kan have med dit barn om følelser, relationer og selvregulering. Efter at have løst et ansigtsudtryks-matcharbejdsark kan I øve jer i at lave ansigterne sammen foran et spejl, overdrive hver følelse og tale om, hvornår I hver især har følt det sådan. Lav et familie-følelsesskema på køleskabet, hvor alle, forældre inkluderet, kan flytte deres navneskilt til den følelse, der bedst beskriver deres dag. Når dit barn oplever en stærk følelse, kan du referere til ordforrådet fra deres arbejdsark ved at sige det lyder som om, du måske føler dig frustreret, som er det ord, vi lærte. Læs billedbøger om karakterer, der oplever forskellige følelser, og hold pause, så dit barn kan identificere følelserne ved hjælp af deres arbejdsarksordforråd. Under bilture eller stille stunder kan I spille et følelsegættespil, hvor en person beskriver en situation, og den anden navngiver den følelse, de ville føle. For yngre børn bør arbejdsarksessionerne holdes på ti minutter, og du bør altid anerkende de følelser, de udtrykker, også de svære. Målet er ikke at eliminere negative følelser, men at hjælpe børn med at genkende, navngive og navigere dem. Når dit barn ser, at du også oplever et fuldt spektrum af følelser og taler åbent om dem, strækker arbejdsarkslæringen sig ind i autentisk emotionel intelligens, der vil gavne dem gennem hele livet.',

  // -- Curated apps (IDENTICAL to English) --
  curatedAppIds: [
    'coloring', 'draw-and-color', 'matching-app', 'picture-sort',
    'image-addition',
    'word-search', 'writing-app', 'word-guess',
    'odd-one-out', 'drawing-lines',
  ],
  appCategories: [
    { category: 'math', appIds: ['image-addition'] },
    { category: 'literacy', appIds: ['word-search', 'writing-app', 'word-guess'] },
    { category: 'visual', appIds: ['coloring', 'draw-and-color', 'matching-app', 'picture-sort'] },
    { category: 'puzzles', appIds: ['odd-one-out', 'drawing-lines'] },
  ],

  // -- Educational sections --
  teachingTips: [
    { title: 'Start hver dag med et følelsestjek', description: 'Sæt en følelsesplakat op nær indgangen til dit klasselokale med illustrerede ansigter, der viser forskellige følelser. Når eleverne ankommer, placerer de deres navnekort ved siden af den følelse, der matcher deres morgen. Brug disse data til at informere din undervisningstilgang for dagen, og par følelsesarbejdsark med de følelser, der er mest repræsenteret. Over tid udvikler børnene en vane med selvovervågning og ordforrådet til at formulere deres følelsesmæssige tilstand.', audience: 'teacher' },
    { title: 'Brug følelsessortering som konfliktløsningsværktøj', description: 'Når konflikter opstår i klasselokalet, kan du tage billedsorteringsarbejdsark frem, der viser forskellige følelsesudtryk. Bed hvert involveret barn identificere, hvilket ansigt der matcher, hvordan de følte sig under uenigheden. Dette flytter samtalen fra skyld til følelser og hjælper børn med at øve perspektivtagning i det øjeblik, det betyder mest. Følg op med et arbejdsark, der udforsker, hvad vi kan gøre, når vi føler det sådan.', audience: 'teacher' },
    { title: 'Lav en familiefølelsesbog', description: 'Efter at dit barn har løst et følelsesordforråds-arbejdsark, kan I starte en simpel følelsesbog sammen. Hver aften tegner eller skriver dit barn den stærkeste følelse, de oplevede den dag, og en sætning om, hvad der forårsagede den. Gennemgå dagbogen ugentligt for at opdage mønstre og fejre emotionel vækst. Denne praksis opbygger selvbevidsthed, skrivefærdigheder og giver dit barn et trygt rum til at bearbejde deres oplevelser.', audience: 'parent' },
    { title: 'Model emotionelt ordforråd i hverdagsøjeblikke', description: 'Når I løser følelsesarbejdsark sammen, kan du gøre en bevidst indsats for at bruge det samme ordforråd resten af dagen. I stedet for at sige jeg er glad, sig jeg føler mig taknemmelig for, at vi bruger tid sammen. I stedet for jeg er sur, sig jeg føler mig frustreret, fordi trafikken var langsom. Børn lærer emotionelt ordforråd mest effektivt, når de hører voksne bruge det autentisk, og omdanner dermed arbejdsarksord til levende sprog.', audience: 'both' },
  ],
  activities: [
    {
      title: 'Følelsesansigts-gallerivandring',
      description: 'Print store følelsesansigts-kort og sæt dem op rundt i lokalet i børnehøjde. Giv hver elev et klembræt med et registreringsark. Børnene går fra ansigt til ansigt, skriver følelsens navn og tegner eller skriver om en gang, de følte det sådan. Efter gallerivandringen samles I som gruppe, og frivillige deler en respons. Denne aktivitet opbygger emotionelt ordforråd, skrivefærdigheder og empati gennem delte oplevelser.',
      materials: ['store følelsesansigts-udprint', 'tape', 'klembrætter', 'registreringsark-arbejdsark', 'blyanter'],
      duration: '20-25 minutter',
      skillAreas: ['social', 'literacy'],
    },
    {
      title: 'Følelsestermometer-kreation',
      description: 'Giv hvert barn en papirstrimmel opdelt i fem sektioner, der repræsenterer følelsesintensitet fra rolig i bunden til overvældet i toppen. Børnene farvelægger hver sektion i en anden farve og skriver eller tegner et følelsesord for hvert niveau. Sæt en glidende papirpil på. Gennem dagen justerer børnene deres termometer for at vise deres aktuelle følelsesmæssige tilstand. Dette selvreguleringværktøj udspringer direkte af ordforråd lært i følelsesarbejdsark.',
      materials: ['forudskårne papirstrimler', 'farveblyanter eller tusser', 'papirpile', 'splitnitter', 'følelsesordliste'],
      duration: '15-20 minutter',
      skillAreas: ['social', 'creative'],
    },
    {
      title: 'Følelses-pantomime og optællingsskema',
      description: 'Skriv følelsesord på kort og læg dem med bagsiden opad. Børnene skiftes til at trække et kort og mime følelsen uden ord, mens klassekammeraterne gætter. Efter hver runde optælles følelsen på et klasseskema. Når alle kort er blevet mimet, analyserer I optællingsskemaet sammen: hvilke følelser var nemmest at gætte, hvilke var sværest, og hvorfor. Dette kombinerer socialt-emotionel læring med matematiske datafærdigheder og fysisk udtryk.',
      materials: ['følelsesordkort', 'optællingsskema-plakat', 'tusser', 'timer'],
      duration: '20-25 minutter',
      skillAreas: ['social', 'math'],
    },
  ],
  curriculumAlignment: [
    {
      standard: 'K.CC.B.4',
      framework: 'Common Core',
      description: 'Count emotion-themed objects to understand the relationship between numbers and quantities',
      relatedAppIds: ['image-addition'],
    },
    {
      standard: 'RL.K.3',
      framework: 'Common Core',
      description: 'Identify characters and their feelings in stories, using emotion vocabulary to describe character motivations',
      relatedAppIds: ['word-search', 'word-guess'],
    },
    {
      standard: 'L.1.5',
      framework: 'Common Core',
      description: 'Demonstrate understanding of shades of meaning among emotion words differing in intensity',
      relatedAppIds: ['writing-app', 'word-guess'],
    },
  ],

  // -- Grade-specific content --
  gradeContent: {
    'preschool': {
      intro: 'Førskolebørn i tre- til fireårsalderen er lige begyndt at forstå, at de hvirvlende fornemmelser inde i dem har navne, og at andre mennesker oplever de samme følelser. Denne spirende følelsesmæssige bevidsthed gør følelsesarbejdsark til et vigtigt udviklingsredskab på førskoleniveau. På dette trin genkender børn typisk basale følelser som glad, ked af det, sur og bange, men kæmper med noget mere nuanceret. Arbejdsark designet til førskolebørn bruger store, tydelige ansigtsudtryksillustrationeer, der overdriver følelsesmæssige signaler, så det bliver let for små børn at skelne mellem et smil og en rynket pande, store øjne og sammenknebne øjne. En typisk opgave kan vise fire ansigter og bede barnet om at sætte ring om det glade eller farvelægge det triste ansigt blåt. Matchopgaver parrer følelsesansigter med simple scenarier som at få en gave eller miste et legetøj, og hjælper børn med at forbinde følelser med årsager. At spore ordene glad, ked af det eller sur udvikler blyantsgreb og bogstavdannelse, mens det opbygger det tidligste emotionelle ordforråd. Førskoleårene er, når børn første gang støder på sociale konflikter i gruppesammenhænge, og at have bare et grundlæggende følelsesordforråd giver dem redskaber til at udtrykke frustration med ord i stedet for handlinger. I den danske folkeskoles førskoleordning, hvor trivsel og det hele barn er centrale begreber i Fælles Mål, understøtter disse arbejdsark den naturlige integration af social-emotionel udvikling med tidlig faglig læring. Lærere og forældre bør holde sessionerne meget korte, omkring fem til ti minutter, og altid følge op med et spørgsmål som har du nogensinde følt det sådan, for at gøre hvert arbejdsark til en kort, men meningsfuld samtale om barnets indre verden.',
      objectives: [
        { skill: 'Identificer og navngiv fire basale følelser ud fra ansigtsudtryk', area: 'cognitive' },
        { skill: 'Match følelsesansigter med simple hverdagsscenarier', area: 'social' },
        { skill: 'Spor følelsesordforrådsord med korrekt bogstavdannelse', area: 'literacy' },
      ],
      developmentalNotes: 'I tre- til fireårsalderen udvikler børn theory of mind, forståelsen af, at andre mennesker har tanker og følelser, der er forskellige fra deres egne. Følelsesmatchende arbejdsark understøtter direkte denne kognitive milepæl. Motorisk udvikling på dette trin betyder, at tykke konturer på følelsesansigter hjælper børn med at holde sig inden for linjerne ved farvelægning, og opbygger både finmotorisk kontrol og visuel opmærksomhed på ansigtsdetaljer.',
      teachingTips: [
        'Brug et spejl sammen med følelsesarbejdsark, så førskolebørn kan lave hvert ansigtsudtryk selv, før de identificerer det på papir, og dermed forbinde fysisk fornemmelse med visuel genkendelse.',
        'Begræns hvert arbejdsark til tre eller fire følelsesansigter for at undgå at overvælde førskolebarns opmærksomhedsspænd, og navngiv altid følelsen højt sammen, før barnet begynder opgaven.',
      ],
      faq: [
        { question: 'Kan treårige virkelig have gavn af følelsesarbejdsark?', answer: 'Ja. Selv i treårsalderen kan børn matche et smilende ansigt med glad og et grædende ansigt med ked af det. Førskole-følelsesarbejdsark bruger tydelige, simple illustrationer, der gør disse forbindelser visuelle og konkrete og lægger fundamentet for det rigere emotionelle ordforråd, der vil udvikle sig over de følgende år.' },
        { question: 'Hvordan hjælper følelsesarbejdsark med førskole-adfærdsudfordringer?', answer: 'De giver børn ord for, hvad de føler, hvilket reducerer frustrationsdrevne udbrud. Når et barn kan pege på et billede og sige jeg føler mig sur, har det taget det første skridt mod at håndtere den følelse konstruktivt. Arbejdsark øvet i rolige stunder bliver referenceredskaber, børn kan bruge under faktiske følelsesmæssige øjeblikke.' },
        { question: 'Bør jeg rette mit førskolebarn, hvis de navngiver en følelse forkert på et arbejdsark?', answer: 'Vejled forsigtigt i stedet for at rette. Sig jeg kan godt se, hvorfor du måske tror, det ansigt ser vred ud. Se på munden, er den bøjet op eller ned? Lad os finde ud af det sammen. Målet er at opbygge følelsesmæssige observationsevner, ikke at få et rigtigt svar, og hvert forsøg er et skridt mod større emotionel læsefærdighed.' },
      ],
    },
    'kindergarten': {
      intro: 'Børn i børnehaveklassen bringer en voksende social bevidsthed til følelsesarbejdsark, parate til at udvide sig ud over basale glad, ked af det og sur til et rigere ordforråd, der inkluderer overrasket, bekymret, begejstret, stolt og flov. Fem- og seksårige navigerer stadig mere komplekse kammeratskabsrelationer, håndterer forventningerne i en hel skoledag og begynder at forstå, at mennesker kan føle mere end én følelse på samme tid. Følelsesarbejdsark på dette niveau udnytter disse udviklingsmæssige spring ved at introducere nuanceret følelsesidentifikation, årsag-og-virkning-ræsonnement om følelser og tidlige empatiøvelser. Matematikaktiviteter beder børn om at tælle grupper af følelsesansigter, sammenligne hvor mange der er glade versus triste, eller løse simple additionsopgaver med følelsestematiske tælleenheder. Ordsøgninger med følelsesordforråd opbygger ordbilledsgenkendelse, mens de eksponerer børn for en bredere ordliste af følelser. Sorteringsarbejdsark, der beder børn om at kategorisere følelser som behagelige eller ubehagelige, introducerer konceptet om, at alle følelser er gyldige, selv når nogle er sværere at opleve. Tegneaktiviteter, hvor børn laver deres egne følelsesansigter til specifikke scenarier, udvikler både kreativt udtryk og perspektivtagningsevner. I den danske folkeskoles børnehaveklasse, hvor Fælles Mål vægter trivsel, sociale kompetencer og det hele barn, giver disse arbejdsark en struktureret ramme for at øve de emotionelle færdigheder, der er afgørende for succesfuld skolegang. Børnehaveklasseåret er et kritisk vindue for socialt-emotionel læring, fordi børn danner de kammeratskabsmønstre, der vil følge dem gennem folkeskolen, og arbejdsark, der opbygger empati og selvbevidsthed i denne periode, har varige effekter på social kompetence.',
      objectives: [
        { skill: 'Identificer og navngiv mindst otte forskellige følelser ud fra ansigtsudtryk og scenarier', area: 'social' },
        { skill: 'Sorter følelser i kategorier og forklar grupperingens rationale', area: 'cognitive' },
        { skill: 'Læs og skriv følelsesordforrådsord herunder overrasket, bekymret og stolt', area: 'literacy' },
      ],
      developmentalNotes: 'Børn i børnehaveklassen udvikler den kognitive fleksibilitet til at forstå, at følelser forandrer sig, og at den samme begivenhed kan forårsage forskellige følelser hos forskellige mennesker. Deres voksende ordforråd giver dem mulighed for at gå fra brede etiketter til mere specifikke følelsesord. Socialt lærer de at aflæse ansigtsudtryk og kropssprog i realtid, og arbejdsarksøvelse med illustrerede følelser skærper denne kritiske sociale færdighed.',
      teachingTips: [
        'Efter at have løst et følelsessorteringsarbejdsark kan du lade børnene mime hver følelse for en makker og diskutere, hvordan deres ansigt og krop ser ud, når de føler det sådan, og dermed forbinde visuel genkendelse med fysisk selvbevidsthed.',
        'Opret en klasseordvæg for følelser, der vokser, efterhånden som nyt ordforråd dukker op i arbejdsark, og opfordr børnene til at bruge disse præcise ord under dele-tid og konfliktløsning.',
      ],
      faq: [
        { question: 'Hvor mange følelser bør børnehaveklassebørn kunne identificere?', answer: 'Ved slutningen af børnehaveklassen kan de fleste børn pålideligt identificere og navngive otte til tolv følelser. Arbejdsark opbygger dette ordforråd gradvist, startende med de fire basale og tilføjer nuancerede følelser som overrasket, bekymret, stolt, flov og begejstret gennem gentagen visuel øvelse og kontekstuel matchning.' },
        { question: 'Hvordan understøtter følelsesarbejdsark læsefærdigheder i børnehaveklassen?', answer: 'Følelsesord er meget motiverende ordforråd, fordi de beskriver børns personlige oplevelser. Ordsøgninger, ordgættespil og skriveaktiviteter med følelsesord opbygger ordbilledsgenkendelse, fonetisk afkodning og skriveflydende, mens de udvider den emotionelle ordliste, børn har brug for til social succes.' },
        { question: 'Kan følelsesarbejdsark hjælpe generte eller ængstelige børnehaveklassebørn?', answer: 'Ja. Arbejdsark giver en lavtryksmåde at udforske følelser på papir, før de diskuteres mundtligt. Et genert barn, der farvelægger et bekymret ansigt og mærker det, er måske ikke klar til at dele verbalt, men har stadig øvet at identificere og navngive følelsen, og opbygger dermed fundamentet for fremtidig selvudtryk, når de føler sig trygge.' },
      ],
    },
    'first-grade': {
      intro: 'Elever i 1. klasse er parate til følelsesarbejdsark, der rækker ud over identifikation og ind i analyse, empati og strategiopbygning for selvregulering. Seks- og syvårige kan læse simple tekster selvstændigt, løse flertrinsopgaver og engagere sig i ægte perspektivtagning, når de vejledes af strukturerede aktiviteter. Følelsesarbejdsark på dette niveau præsenterer mere komplekse scenarier, hvor karakterer oplever blandede følelser, eller hvor den samme begivenhed udløser forskellige følelser hos forskellige mennesker, hvilket udfordrer børn til at tænke kritisk over den subjektive natur af følelsesmæssig oplevelse. Matematikarbejdsark bruger følelsestematisk dataindsamling, der beder børn om at undersøge klassekammerater om deres yndlingsfølelser, lave optællingsskemaer og sammenligne resultater. Læseaktiviteter inkluderer korte tekster om karakterer, der navigerer sociale dilemmaer, med forståelsesspørgsmål, der beder børn om at identificere følelser, forudsige reaktioner og foreslå strategier. Ordpuslespil har avanceret følelsesordforråd som overvældet, skuffet, beslutsom og medfølende, der udvider den ordliste, børn bruger til at beskrive deres stadig mere komplekse indre liv. I den danske folkeskoles 1. klasse, hvor Fælles Mål integrerer trivsel og sociale kompetencer på tværs af alle fag, giver disse arbejdsark en struktureret ramme for at udvikle de emotionelle og sociale færdigheder, der er afgørende for al anden læring. 1. klasse er, når børn begynder at internalisere selvregulreringsstrategier, og arbejdsark der præsenterer scenarier parret med håndteringsmuligheder, som at trække vejret dybt, tale med en ven eller tegne om sine følelser, giver børn en menu af sunde reaktioner, de kan øve på papir og anvende i virkeligheden. Den faglige stringens i 1. klasses indhold betyder, at hvert følelsesarbejdsark samtidig opbygger læseforståelse, skriveflydende og analytisk tænkning sideløbende med de social-emotionelle kompetencer, der gør al anden læring mulig.',
      objectives: [
        { skill: 'Analyser scenarier med blandede eller modstridende følelser og forklar karakterers perspektiver', area: 'social' },
        { skill: 'Læs korte tekster om følelsesmæssige situationer og besvar inferensbaserede forståelsesspørgsmål', area: 'literacy' },
        { skill: 'Indsaml og sammenlign data om følelser ved hjælp af optællingsskemaer og simple grafer', area: 'math' },
      ],
      developmentalNotes: 'Elever i 1. klasse har udviklet tilstrækkelig theory of mind til at forstå, at to mennesker kan føle forskelligt om den samme begivenhed. Deres voksende læseevne giver dem mulighed for at engagere sig selvstændigt med scenariebaserede arbejdsark. Følelsesmæssigt begynder de at internalisere selvregulreringsstrategier, og arbejdsark der præsenterer håndteringsevnemuligheder, giver dem en konkret reference, de kan visualisere under faktiske følelsesmæssige øjeblikke.',
      teachingTips: [
        'Brug følelseslæseforståelsestekster som springbrætter for klassediskussioner om, hvordan karakterer kunne reagere anderledes, og model processen med at generere og vurdere håndteringsstrategier.',
        'Lad eleverne lave deres egne følelses-scenariearbejdsark, som klassekammerater kan løse, hvilket uddyber både skrivefærdigheder og empati, da de skal forestille sig, hvordan forskellige situationer ville føles.',
      ],
      faq: [
        { question: 'Hvordan adskiller følelsesarbejdsark i 1. klasse sig fra børnehaveklassens?', answer: 'Arbejdsark i 1. klasse bevæger sig fra grundlæggende identifikation til analyse og strategi. I stedet for blot at navngive en følelse analyserer børn, hvorfor en karakter føler det sådan, overvejer hvordan andre måske føler anderledes, og vurderer håndteringsstrategier. Læsetekster og flertrinsscenarier erstatter simpel matchning, hvilket afspejler 1. klasses faglige og social-emotionelle modenhed.' },
        { question: 'Kan følelsesarbejdsark hjælpe med venskabsudfordringer i 1. klasse?', answer: 'Ja. Scenariebaserede arbejdsark præsenterer almindelige sociale situationer som at blive holdt udenfor, være uenig med en ven eller føle sig jaloux. Børn øver sig i at identificere de involverede følelser og vælge passende reaktioner på papir, og opbygger dermed en værktøjskasse af strategier, de kan trække på, når virkelige venskabsudfordringer opstår.' },
        { question: 'Hvordan opbygger følelsesarbejdsark skrivefærdigheder i 1. klasse?', answer: 'De giver stærkt motiverende skriveøvelser, fordi børn skriver om deres egne oplevelser og følelser. Aktiviteter, der beder børn om at beskrive en gang, de følte sig stolte, skrive om, hvad der hjælper dem med at føle sig rolige, eller skrive et brev til en ked-af-det-ven, udvikler sætningsflydende og personlige fortællefærdigheder, mens de styrker det emotionelle ordforråd.' },
      ],
    },
    'second-grade': {
      intro: 'Elever i 2. klasse bringer den læseforståelse, analytiske ræsonnement og skriveflydende, der er nødvendig for at engagere sig med følelsesarbejdsark på et virkelig transformativt niveau, hvor de bevæger sig fra at identificere følelser til at analysere følelsesmæssige situationer, vurdere håndteringsstrategier og skrive eftertænksomt om kompleksiteten i menneskelig følelsesmæssig oplevelse. Syv- og otteårige kan læse tekster med flere afsnit selvstændigt, konstruere organiserede skriftlige svar og tænke kritisk over, hvorfor mennesker føler forskelligt i den samme situation, hvilket gør dem parate til social-emotionelle læringsaktiviteter, der udvikler både faglige færdigheder og emotionel intelligens samtidig. Læseaktiviteter præsenterer længere fortællescenarier, hvor karakterer står over for realistiske sociale dilemmaer, som at blive udelukket fra et spil, modtage kritik af deres arbejde eller være vidne til, at en ven behandles uretfærdigt, og forståelsesspørgsmål kræver, at eleverne identificerer flere følelser, en karakter kan opleve, analyserer hvorfor forskellige karakterer reagerer forskelligt og vurderer, hvilke håndteringsstrategier der ville være mest effektive. Matematikaktiviteter bruger følelsesdata på et mere sofistikeret niveau, præsenterer undersøgelsesresultater om, hvordan elever på en skole føler om forskellige situationer, og beder børn om at fortolke søjlediagrammer, beregne forskelle og drage evidensbaserede konklusioner om følelsesmæssige mønstre. Ordforrådet udvides dramatisk til at inkludere nuancerede ord som splittet, empatisk, modstandsdygtig, overvældet, taknemmelig og ængstelig, der giver eleverne præcisionsinstrumenter til at beskrive deres indre verden. I den danske folkeskoles 2. klasse, hvor Fælles Mål vægter trivsel, fællesskab og tværfaglige kompetencer, giver disse arbejdsark en struktureret ramme for at integrere social-emotionel læring med faglig progression. 2. klasse er et afgørende tidspunkt for emotionel udvikling, fordi børn danner de selvreguleringsvaner og sociale ræsonneringsmønstre, der vil definere deres tilgang til relationer gennem hele folkeskolen og videre, hvilket gør disse arbejdsark til en investering i både faglig præstation og livslang emotionel trivsel.',
      objectives: [
        { skill: 'Analyser flerkarakter-scenarier for at identificere forskellige emotionelle perspektiver og vurdere passende reaktioner', area: 'social' },
        { skill: 'Læs fortælletekster om følelsesmæssige situationer og skriv karakteranalyseafsnit med belæg fra teksten', area: 'literacy' },
        { skill: 'Fortolk følelsesrelaterede undersøgelsesdata fra grafer og diagrammer og drag evidensbaserede konklusioner om mønstre', area: 'math' },
      ],
      developmentalNotes: 'Elever i 2. klasse har udviklet tilstrækkelig theory of mind til at forstå, at den samme begivenhed kan producere forskellige følelser hos forskellige mennesker baseret på deres perspektiver og erfaringer. Deres skrivefærdigheder giver dem mulighed for at formulere nuanceret følelsesmæssigt ræsonnement i organiserede afsnit. Socialt er de i stigende grad bevidste om gruppedynamikker, retfærdighed og sociale normer, hvilket gør scenariebaserede arbejdsark om inklusion, konflikt og empati både aktuelle og dybt engagerende.',
      teachingTips: [
        'Præsenter et scenarie med to karakterer, der føler forskelligt om den samme begivenhed, og lad eleverne skrive et afsnit fra hver karakters perspektiv, og dermed opbygge empati og perspektivtagning gennem struktureret skriveøvelse.',
        'Lav en klassefølelseundersøgelse, hvor eleverne anonymt rapporterer, hvordan de føler om forskellige skolesituationer, og brug derefter de samlede data i en matematiklektion om at fortolke søjlediagrammer og diskutere, hvad mønstrene afslører om fælles oplevelser.',
      ],
      faq: [
        { question: 'Hvordan adskiller følelsesarbejdsark i 2. klasse sig fra tidligere klassetrin i faglig stringens?', answer: 'De bevæger sig fra identifikation til analyse og vurdering. I stedet for at navngive en følelse analyserer eleverne, hvorfor karakterer føler forskelligt om den samme begivenhed, vurderer flere håndteringsstrategier og argumenterer skriftligt for den mest effektive, og fortolker følelsesdata fra grafer. Læseteksterne er fortællinger med flere afsnit, der kræver inferens, og skriveopgaverne kræver organiserede afsnit med belæg.' },
        { question: 'Kan følelsesarbejdsark hjælpe elever i 2. klasse med at navigere mobning og udelukkelse?', answer: 'Ja. Scenariebaserede arbejdsark præsenterer realistiske situationer med udelukkelse, drilleri og uretfærdighed i et struktureret format, der giver eleverne mulighed for at analysere de involverede følelser, overveje flere perspektiver og vurdere reaktionsstrategier, før de møder lignende situationer i virkeligheden. Denne øvelse-på-papir-tilgang opbygger både emotionelt ordforråd og praktiske håndteringsevner.' },
        { question: 'Hvordan integreres følelsesarbejdsark i 2. klasse med faglige skrivemål?', answer: 'Eleverne skriver personlige fortællinger om følelsesmæssige oplevelser med klar begyndelse, midte og afslutning. De skriver holdningsafsnit, der argumenterer for specifikke håndteringsstrategier med understøttende begrundelser. De producerer karakteranalyseafsnit med tekstbelæg. Denne vifte af skriveformål adresserer direkte Fælles Måls mål for fortællings-, holdnings- og informationsskrivning i 2. klasse.' },
      ],
    },
    'third-grade': {
      intro: 'Elever i 3. klasse bringer multiplikationsbaserede dataanalysefærdigheder, reflekterende skriveevne og voksende kapacitet for abstrakt tænkning til følelsestematiske arbejdsark, der bevæger sig ud over at navngive følelser til at undersøge følelsernes videnskab, analysere mønstre i følelsesdata og udvikle evidensbaserede strategier for emotionel regulering. Otte- og niårige kan multiplicere og dividere inden for hundrede, oprette og fortolke grafer og skrive organiserede essays med flere afsnit med strukturerede afsnit og præcist ordforråd, hvilket gør dem parate til arbejdsark, der nærmer sig emotionel intelligens med både videnskabelig stringens og personlig dybde. Multiplikation driver undersøgelsesdataanalyse med aktiviteter som hvis tolv elever rapporterede, at de følte sig selvsikre, ni rapporterede, at de følte sig nervøse, og seks rapporterede, at de følte sig begejstrede før en prøve, hvor mange totale svar blev indsamlet, og hvis undersøgelsen blev givet til tre forskellige klasser, brug multiplikation til at estimere skolens samlede totaler. Grafisk fremstilling bliver central, når elever opretter søjlediagrammer, der viser emotionelle tjek-ind-resultater over en uge, sammenligner frekvenser af forskellige følelser med multiplikationsbaseret skalering og fortolker mønstre i deres data for at drage konklusioner om, hvornår og hvorfor bestemte følelser dominerer. Læsetekster strækker sig til kapitellange tekster om emotionel intelligens, neurovidenskaben bag hvordan hjernen behandler følelser, hvordan forskellige kulturer udtrykker og værdsætter forskellige følelsestilstande, og evidensbaseret forskning om, hvilke håndteringsstrategier der er mest effektive til at håndtere stærke følelser. I den danske folkeskoles 3. klasse, hvor Fælles Mål vægter undersøgende, tværfaglige tilgange og elevernes trivsel, giver disse arbejdsark en autentisk ramme for at integrere dataanalyse, reflekterende skrivning og social-emotionel kompetence. Reflekterende skrivning når ny sofistikation, når eleverne skriver essays med flere afsnit om følelsesmæssige oplevelser, strukturerer deres refleksioner med indledninger, der etablerer kontekst, brødtekstafsnit, der analyserer deres følelsesmæssige reaktioner med præcist ordforråd som frustreret, overvældet og beslutsom, og konklusioner, der forbinder personlig erfaring med bredere indsigter om følelsesmæssig vækst. Integrationen af multiplikativ dataanalyse, kapitellang psykologisk og videnskabelig læsning, struktureret reflekterende skrivning og evidensbaseret strategivurdering sikrer, at følelsesarbejdsark i 3. klasse leverer ægte faglig stringens, mens de understøtter den social-emotionelle udvikling, der ligger til grund for al succesfuld læring.',
      objectives: [
        { skill: 'Brug multiplikation og grafisk fremstilling til at analysere undersøgelsesdata om følelsesmæssige mønstre og trivsel', area: 'math' },
        { skill: 'Skriv reflekterende essays med flere afsnit om følelsesmæssige oplevelser med strukturerede afsnit og præcist ordforråd', area: 'literacy' },
        { skill: 'Vurder emotionelle reguleringsstrategier ved at analysere belæg fra flere informationskilder', area: 'cognitive' },
      ],
      developmentalNotes: 'Elever i 3. klasse er udviklingsmæssigt parate til dybere emotionel analyse, hvor de bevæger sig fra at navngive følelser til at forstå, hvorfor følelser opstår, og hvordan de kan håndteres konstruktivt. Deres voksende kapacitet for abstrakt tænkning giver dem mulighed for at forstå hjernevidenskab på et introduktionsniveau og at skrive reflekterende om deres indre oplevelser.',
      teachingTips: [
        'Design et klasse-følelseundersøgelsesprojekt, hvor eleverne opretter spørgsmål om emotionel trivsel, indsamler data fra klassekammerater, bruger multiplikation til at beregne svartotaler på tværs af flere klasser, opretter søjlediagrammer over resultater og skriver analytiske afsnit, der fortolker de mønstre, de opdager.',
        'Lav et emotionelt reguleringsforskningsprojekt, hvor eleverne undersøger tre forskellige håndteringsstrategier fra flere kilder, organiserer belæg om effektivitet i et sammenligningsskema og skriver et essay med flere afsnit, der anbefaler den mest effektive strategi med understøttende begrundelser og belæg fra deres forskning.',
      ],
      faq: [
        { question: 'Hvordan udvikler følelsesarbejdsark i 3. klasse dataanalysefærdigheder gennem undersøgelser?', answer: 'Eleverne designer undersøgelsesspørgsmål om emotionel trivsel, indsamler svar fra klassekammerater, bruger multiplikation til at beregne totaler og estimere skoledækkende resultater, opretter søjlediagrammer over deres data, beregner gennemsnit med division og skriver analytiske afsnit, der fortolker mønstre. Denne proces underviser i den fulde cyklus af dataindsamling, organisering, analyse og kommunikation.' },
        { question: 'Hvilke reflekterende skrivefærdigheder opbygger følelsesarbejdsark i 3. klasse?', answer: 'Eleverne skriver essays med flere afsnit om følelsesmæssige oplevelser med strukturerede indledninger, brødtekstafsnit der analyserer deres reaktioner med præcist emotionelt ordforråd, og konklusioner der forbinder personlige oplevelser med bredere indsigter. De lærer at skelne mellem at beskrive, hvad der skete, og at analysere, hvorfor de følte på en bestemt måde.' },
        { question: 'Hvordan understøtter følelsesarbejdsark social-emotionel læring sideløbende med faglige færdigheder?', answer: 'Enhver faglig aktivitet opbygger samtidig emotionel intelligens. Undersøgelsesprojekter udvikler empati gennem forståelse af klassekammeraters følelser, forskning i håndteringsstrategier giver praktiske reguleringsværktøjer, reflekterende skrivning fordyber selvbevidsthed, og dataanalyse afslører, at følelsesmæssige oplevelser følger mønstre, der kan forstås og håndteres konstruktivt.' },
      ],
    },
  },

  // -- FAQ --
  faq: [
    { question: 'Hvilke typer følelsesarbejdsark kan jeg lave?', answer: 'Du kan lave en bred vifte af følelsestematiske arbejdsark, herunder matchning og sortering af ansigtsudtryk, følelsesordforråd-ordsøgninger og ordgættespil, malebilleder med udtryksfyldte ansigter, tegneaktiviteter hvor børn laver deres egne følelsesillustrationer, addition og tælling med følelsestematiske tælleenheder, skriveøvelser om følelser og find-den-der-ikke-hører-til-puslespil, der udfordrer børn til at identificere, hvilken følelse der ikke passer i en gruppe.' },
    { question: 'Er følelsesarbejdsarkene gratis at bruge?', answer: 'Ja, LessonCraftStudio lader dig lave og downloade følelsestematiske arbejdsark helt gratis. Vælg din foretrukne arbejdsarkstype, vælg følelsestemaet, tilpas indstillinger som sværhedsgrad og antal elementer, og generer en printvenlig PDF klar til dit klasselokale eller din hjemmelæringssession.' },
    { question: 'Hvilke aldersgrupper er følelsesarbejdsark velegnede til?', answer: 'Følelsesarbejdsark er designet til børn i alderen 3 til 9 og dækker førskole til 3. klasse. Yngre børn arbejder med basale følelser som glad, ked af det og vred med tydelige ansigtsudtryksillustrationeer, mens ældre elever udforsker nuancerede følelser som skuffet, taknemmelig og overvældet gennem scenariebaserede aktiviteter og læseforståelsestekster.' },
    { question: 'Hvordan understøtter følelsesarbejdsark social-emotionelle læringsprogrammer?', answer: 'Følelsesarbejdsark leverer konkrete øvelsesmaterialer, der forstærker social-emotionelle læringsmål. De opbygger de fire kernekompetencer inden for emotionel læsefærdighed: at identificere følelser hos sig selv, genkende følelser hos andre, forstå hvad der forårsager følelser og udvikle strategier til at håndtere dem. Arbejdsark øvet i rolige stunder bliver referenceredskaber, børn kan trække på under faktiske følelsesmæssige situationer.' },
    { question: 'Kan følelsesarbejdsark hjælpe børn, der har svært ved at udtrykke deres følelser?', answer: 'Absolut. For børn der finder det svært at verbalisere deres følelser, tilbyder arbejdsark et visuelt og skriftligt alternativ. At pege på et ansigt, der matcher deres følelse, sætte ring om et følelsesord eller tegne et udtryk giver disse børn en struktureret vej til emotionel kommunikation, der gradvist kan opbygges mod verbalt udtryk.' },
    { question: 'Hvordan underviser følelsesarbejdsark i empati?', answer: 'Match- og sorteringsaktiviteter beder børn om at overveje, hvordan karakterer føler i forskellige situationer, hvilket er grundlaget for perspektivtagning. Når et barn ser på et scenarie med nogen, der mister et kæledyr, og vælger det triste ansigt, øver det den kognitive færdighed at forestille sig en anden persons følelsesmæssige tilstand, hvilket direkte opbygger empatisk kapacitet.' },
    { question: 'Er følelsesarbejdsark passende under følelsesmæssigt svære perioder?', answer: 'Følelsesarbejdsark kan være særligt hjælpsomme i udfordrende perioder, fordi de normaliserer hele spektret af følelser. Aktiviteter løst roligt i neutrale øjeblikke opbygger ordforråd og strategier, som børn kan få adgang til i svære stunder. Dog bør man altid følge barnets initiativ og undgå at tvinge følelsesdiskussioner, når et barn er aktivt forpint.' },
    { question: 'Hvordan kobler følelsesarbejdsark sig til læsefærdigheder?', answer: 'Følelsesordforråd er blandt det mest personligt relevante sprog, børn lærer, hvilket gør det stærkt holdbart. Ordsøgninger opbygger bogstavgenkendelse og visuel scanning, skriveaktiviteter udvikler sætningsstruktur og personlige fortællefærdigheder, og ordgættespil styrker fonemisk bevidsthed og stavning, alt sammen mens de udvider den emotionelle ordliste, der understøtter læseforståelse af karakterdrevne historier.' },
    { question: 'Hvordan printer eller downloader jeg følelsesarbejdsarkene?', answer: 'Efter at have tilpasset dit arbejdsark klikker du på generer-knappen for at oprette en printvenlig PDF. Du kan derefter downloade filen til din computer eller bruge din browsers printfunktion. Alle arbejdsark er formateret til standard letter- og A4-papirstørrelser for nem udskrivning derhjemme eller i skolen.' },
    { question: 'Hvor ofte bør børn løse følelsesarbejdsark?', answer: 'To til tre sessioner om ugen fungerer godt, ideelt integreret i en bredere social-emotionel læringsrutine. Hver session bør vare ti til femten minutter for yngre børn og op til tyve minutter for ældre. Konsistens betyder mere end hyppighed, da regelmæssigt engagement med følelsesordforråd opbygger kumulativ flydende, der overføres til virkelige følelsesmæssige situationer.' },
  ],

  // -- Cross-linking (IDENTICAL to English) --
  relatedThemes: ['body', 'music', 'pets', 'fairy-tales', 'school'],
  relatedBlogCategories: [],
};

registerThemeContent('emotions', 'da', content);
