/**
 * Name Pools — locale-appropriate first names for templates
 * ==========================================================
 * Auto-generated by scripts/build-name-pools.js
 * DO NOT EDIT MANUALLY
 *
 * 15 names per gender per locale, 11 locales = 330 total names.
 *
 * Generated: 2026-03-01
 */

/* eslint-disable */
// @ts-nocheck

const NAME_POOLS = {
  "en": {
    "male": [
      "Tom",
      "Jack",
      "Ben",
      "Sam",
      "Max",
      "Leo",
      "Dan",
      "Eli",
      "Joe",
      "Luke",
      "Ryan",
      "Owen",
      "Noah",
      "Cole",
      "Liam"
    ],
    "female": [
      "Emma",
      "Lily",
      "Mia",
      "Zoe",
      "Amy",
      "Ella",
      "Ivy",
      "Ava",
      "Ruby",
      "Lucy",
      "Nora",
      "Sara",
      "Kate",
      "Rose",
      "Maya"
    ]
  },
  "de": {
    "male": [
      "Tim",
      "Max",
      "Leo",
      "Ben",
      "Paul",
      "Jan",
      "Tom",
      "Luca",
      "Finn",
      "Noah",
      "Emil",
      "Luis",
      "Nico",
      "Erik",
      "Theo"
    ],
    "female": [
      "Emma",
      "Mia",
      "Lena",
      "Anna",
      "Lea",
      "Marie",
      "Lina",
      "Jana",
      "Nele",
      "Clara",
      "Hanna",
      "Ida",
      "Mila",
      "Lisa",
      "Sarah"
    ]
  },
  "fr": {
    "male": [
      "Tom",
      "Hugo",
      "Adam",
      "Paul",
      "Noah",
      "Liam",
      "Léo",
      "Evan",
      "Jules",
      "Théo",
      "Enzo",
      "Marc",
      "Noé",
      "Axel",
      "Rémi"
    ],
    "female": [
      "Emma",
      "Léa",
      "Zoé",
      "Mia",
      "Jade",
      "Lina",
      "Clara",
      "Eva",
      "Alice",
      "Chloé",
      "Inès",
      "Rose",
      "Anna",
      "Nina",
      "Luna"
    ]
  },
  "es": {
    "male": [
      "Juan",
      "Pablo",
      "Luis",
      "Leo",
      "Hugo",
      "Marc",
      "Nico",
      "Iván",
      "Alex",
      "David",
      "Lucas",
      "Mateo",
      "Diego",
      "Raúl",
      "Tomás"
    ],
    "female": [
      "Emma",
      "Mia",
      "Lucía",
      "Ana",
      "Sara",
      "Elena",
      "Julia",
      "Clara",
      "Alba",
      "Paula",
      "Noa",
      "Luna",
      "Alma",
      "Sofía",
      "Lola"
    ]
  },
  "pt": {
    "male": [
      "João",
      "Pedro",
      "Tomás",
      "Luís",
      "Hugo",
      "David",
      "Lucas",
      "Tiago",
      "Rui",
      "Diogo",
      "André",
      "Bruno",
      "Luca",
      "Davi",
      "Nuno"
    ],
    "female": [
      "Emma",
      "Ana",
      "Mia",
      "Inês",
      "Clara",
      "Sara",
      "Maria",
      "Lara",
      "Eva",
      "Alice",
      "Leonor",
      "Marta",
      "Rita",
      "Lúcia",
      "Sofia"
    ]
  },
  "it": {
    "male": [
      "Luca",
      "Marco",
      "Leo",
      "Enzo",
      "Nico",
      "Dario",
      "Paolo",
      "Fabio",
      "Giulio",
      "Matteo",
      "Diego",
      "Edoardo",
      "Andrea",
      "Bruno",
      "Carlo"
    ],
    "female": [
      "Emma",
      "Mia",
      "Giulia",
      "Sara",
      "Anna",
      "Elena",
      "Alice",
      "Sofia",
      "Chiara",
      "Lucia",
      "Viola",
      "Gaia",
      "Rosa",
      "Nina",
      "Lisa"
    ]
  },
  "nl": {
    "male": [
      "Tom",
      "Max",
      "Sam",
      "Liam",
      "Daan",
      "Sem",
      "Finn",
      "Noah",
      "Levi",
      "Jan",
      "Luuk",
      "Lars",
      "Ruben",
      "Thijs",
      "Mees"
    ],
    "female": [
      "Emma",
      "Mila",
      "Lotte",
      "Sara",
      "Anna",
      "Eva",
      "Noor",
      "Tess",
      "Lisa",
      "Fien",
      "Roos",
      "Julia",
      "Saar",
      "Lieke",
      "Nina"
    ]
  },
  "sv": {
    "male": [
      "Erik",
      "Axel",
      "Hugo",
      "Nils",
      "Leo",
      "Lars",
      "Emil",
      "Olle",
      "Sven",
      "Liam",
      "Noah",
      "Adam",
      "Elias",
      "Oscar",
      "Albin"
    ],
    "female": [
      "Emma",
      "Ella",
      "Maja",
      "Ebba",
      "Saga",
      "Alma",
      "Elsa",
      "Freja",
      "Astrid",
      "Ida",
      "Wilma",
      "Vera",
      "Agnes",
      "Elin",
      "Klara"
    ]
  },
  "da": {
    "male": [
      "Emil",
      "Noah",
      "Oscar",
      "Liam",
      "Hugo",
      "Erik",
      "Lars",
      "Axel",
      "Mads",
      "Niels",
      "Carl",
      "Otto",
      "Viggo",
      "Aksel",
      "Malte"
    ],
    "female": [
      "Emma",
      "Ida",
      "Alma",
      "Ella",
      "Maja",
      "Nora",
      "Freja",
      "Clara",
      "Astrid",
      "Agnes",
      "Rosa",
      "Saga",
      "Signe",
      "Sofie",
      "Laura"
    ]
  },
  "no": {
    "male": [
      "Emil",
      "Noah",
      "Oscar",
      "Liam",
      "Hugo",
      "Erik",
      "Lars",
      "Aksel",
      "Odin",
      "Simen",
      "Jonas",
      "Mats",
      "Leif",
      "Iver",
      "Olav"
    ],
    "female": [
      "Emma",
      "Nora",
      "Ella",
      "Ida",
      "Maja",
      "Alma",
      "Saga",
      "Sofie",
      "Frida",
      "Ingrid",
      "Thea",
      "Astrid",
      "Hedda",
      "Tuva",
      "Solveig"
    ]
  },
  "fi": {
    "male": [
      "Eetu",
      "Onni",
      "Leo",
      "Elias",
      "Väinö",
      "Matti",
      "Veeti",
      "Leevi",
      "Niilo",
      "Akseli",
      "Eino",
      "Ville",
      "Aleksi",
      "Joel",
      "Hugo"
    ],
    "female": [
      "Emma",
      "Aino",
      "Eevi",
      "Lilja",
      "Venla",
      "Helmi",
      "Aada",
      "Ella",
      "Siiri",
      "Saimi",
      "Iida",
      "Hilla",
      "Isla",
      "Pihla",
      "Ronja"
    ]
  }
};

/**
 * NameHelper — pick names from pools
 *
 * Usage:
 *   NameHelper.pick('en', 'male', rng)            → "Tom"
 *   NameHelper.pick('de', 'female', rng)           → "Emma"
 *   NameHelper.pickUnique('en', 'male', 3, rng)    → ["Ben","Sam","Max"]
 *   NameHelper.pickPair('en', rng)                 → { name1: "Tom", name2: "Emma", g1: "male", g2: "female" }
 *   NameHelper.all('en', 'male')                   → ["Tom","Jack","Ben",...]
 */
const NameHelper = {
  /**
   * Pick a random name from the pool.
   * @param {string} locale - Locale code
   * @param {string} gender - "male" or "female"
   * @param {{ next: function }} rng - RNG with .next() returning [0,1)
   * @returns {string} A name
   */
  pick(locale, gender, rng) {
    var pool = (NAME_POOLS[locale] || NAME_POOLS.en)[gender];
    return pool[Math.floor(rng.next() * pool.length)];
  },

  /**
   * Pick N unique names from the pool.
   * @param {string} locale - Locale code
   * @param {string} gender - "male" or "female" or "mixed"
   * @param {number} count - How many names
   * @param {{ next: function }} rng - RNG with .next() returning [0,1)
   * @returns {string[]} Array of unique names
   */
  pickUnique(locale, gender, count, rng) {
    var localeData = NAME_POOLS[locale] || NAME_POOLS.en;
    var pool;
    if (gender === 'mixed') {
      pool = localeData.male.concat(localeData.female);
    } else {
      pool = localeData[gender];
    }

    // Fisher-Yates shuffle on a copy
    var shuffled = pool.slice();
    for (var i = shuffled.length - 1; i > 0; i--) {
      var j = Math.floor(rng.next() * (i + 1));
      var tmp = shuffled[i]; shuffled[i] = shuffled[j]; shuffled[j] = tmp;
    }

    return shuffled.slice(0, Math.min(count, shuffled.length));
  },

  /**
   * Pick a pair of names (one male, one female by default).
   * @param {string} locale - Locale code
   * @param {{ next: function }} rng - RNG with .next() returning [0,1)
   * @returns {{ name1: string, name2: string, g1: string, g2: string }}
   */
  pickPair(locale, rng) {
    return {
      name1: this.pick(locale, 'male', rng),
      name2: this.pick(locale, 'female', rng),
      g1: 'male',
      g2: 'female'
    };
  },

  /**
   * Get all names for a locale and gender.
   * @param {string} locale - Locale code
   * @param {string} gender - "male" or "female"
   * @returns {string[]}
   */
  all(locale, gender) {
    return (NAME_POOLS[locale] || NAME_POOLS.en)[gender].slice();
  }
};
